// Code generated by appservicegen. DO NOT EDIT.

//go:build server

package api

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// registerGeneratedOperatorRoutes 注册由 appservicegen 生成的运营路由。
func (s *OperatorService) registerGeneratedOperatorRoutes(router *gin.Engine) {
	router.GET("/deployment", s.loadDeployment)
}

// loadDeployment 返回部署形态与企业域名后缀。
func (s *OperatorService) loadDeployment(c *gin.Context) {
	output, err := s.application.LoadDeployment(c.Request.Context(), operatorRequestMeta(c))
	writeOperatorResult(c, http.StatusOK, output, err)
}
