// Code generated by appservicegen. DO NOT EDIT.

//go:build server

package api

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/runforyou-ai/cervi/internal/appservice"
)

// registerGeneratedRoutes 注册由 appservicegen 生成的业务路由。
func (s *Service) registerGeneratedRoutes(router *gin.Engine) {
	router.GET("/installation/status", s.installationStatus)
	router.POST("/auth/login", s.login)
	router.POST("/auth/logout", s.logout)
	router.GET("/auth/identity", s.loadIdentity)
	router.PATCH("/profile", s.updateProfile)
	router.POST("/files/uploads", s.createFileUpload)
	router.POST("/files/:fileID/complete", s.completeFileUpload)
	router.POST("/files/:fileID/parts", s.createFilePartUpload)
	router.POST("/files/:fileID/upload", s.prepareFileUpload)
	router.POST("/attachment-uploads/:fileID/complete", s.completeAttachmentUpload)
	router.DELETE("/files/:fileID/upload", s.cancelFileUpload)
	router.POST("/conversation-attachments", s.sendAttachmentMessage)
	router.POST("/direct-attachment-batches", s.sendAttachmentBatch)
	router.PATCH("/attachment-uploads", s.updateAttachmentUploads)
	router.GET("/conversations/:conversationID/attachments", s.listAttachmentStates)
	router.GET("/conversations/:conversationID/messages/:messageID/attachment", s.getAttachmentDownload)
	router.PATCH("/password", s.changePassword)
	router.PATCH("/preferences", s.updateUserPreferences)
	router.PATCH("/work-status", s.updateUserWorkStatus)
	router.GET("/inbox", s.loadInbox)
	router.POST("/inbox/context/query", s.getInboxContext)
	router.POST("/inbox/window/query", s.readInboxWindow)
	router.GET("/conversations/:conversationID/summary", s.getInboxConversation)
	router.POST("/inbox/conversations/query", s.readInboxConversations)
	router.GET("/inbox/assignees", s.listCustomerServiceAssignees)
	router.GET("/conversations/:conversationID/messages", s.listConversationMessages)
	router.GET("/conversations/:conversationID/message-references", s.listConversationMessageReferences)
	router.GET("/conversations/:conversationID/messages/:messageID/context", s.getConversationMessageContext)
	router.GET("/conversations/:conversationID/navigation", s.getConversationNavigationState)
	router.GET("/conversations/:conversationID/mentions/pending", s.listPendingConversationMentions)
	router.POST("/conversations/:conversationID/mentions/review", s.markConversationMentionReviewed)
	router.POST("/conversations/:conversationID/read", s.markConversationRead)
	router.PATCH("/conversations/:conversationID/unread-mark", s.updateConversationUnreadMark)
	router.PATCH("/conversations/:conversationID/notification-settings", s.updateConversationNotificationSettings)
	router.POST("/conversations/:conversationID/messages", s.sendCustomerTextMessage)
	router.GET("/conversations/:conversationID/deliveries", s.listCustomerMessageDeliveries)
	router.POST("/conversations/:conversationID/deliveries/:deliveryID/resolve", s.resolveCustomerMessageDelivery)
	router.POST("/conversations/:conversationID/claim", s.claimServiceSession)
	router.POST("/conversations/:conversationID/transfer", s.transferServiceSession)
	router.POST("/conversations/:conversationID/close", s.closeServiceSession)
	router.POST("/conversations/:conversationID/reopen", s.reopenServiceSession)
	router.POST("/direct-conversations/messages", s.sendFirstDirectTextMessage)
	router.POST("/agent-conversations/messages", s.sendFirstAgentTextMessage)
	router.POST("/agent-conversations/:conversationID/messages", s.sendAgentTextMessage)
	router.POST("/agent-conversations/:conversationID/runs/:runID/stop", s.stopAgentReply)
	router.GET("/direct-conversations/by-target/:targetIdentityID", s.findDirectConversation)
	router.POST("/direct-conversations/:conversationID/messages", s.sendDirectTextMessage)
	router.POST("/group-conversations", s.createGroupConversation)
	router.GET("/group-conversations/:conversationID", s.getGroupConversation)
	router.PATCH("/group-conversations/:conversationID", s.updateGroupConversation)
	router.POST("/group-conversations/:conversationID/members", s.addGroupConversationMembers)
	router.POST("/group-conversations/:conversationID/members/remove", s.removeGroupConversationMember)
	router.POST("/group-conversations/:conversationID/owner/transfer", s.transferGroupConversationOwner)
	router.POST("/group-conversations/:conversationID/leave", s.leaveGroupConversation)
	router.POST("/group-conversations/:conversationID/dissolve", s.dissolveGroupConversation)
	router.POST("/group-conversations/:conversationID/messages", s.sendGroupTextMessage)
	router.GET("/channels", s.listMessageChannels)
	router.GET("/channels/website/:channelID", s.getWebsiteChannel)
	router.GET("/channels/telegram/:channelID", s.getTelegramChannel)
	router.POST("/channels/telegram/:channelID/connection/test", s.testTelegramChannelConnection)
	router.PUT("/channels/telegram/:channelID/connection", s.saveTelegramChannelConnection)
	router.GET("/channels/:channelID", s.getMessageChannel)
	router.POST("/channels", s.createMessageChannel)
	router.PUT("/channels/:channelID", s.updateMessageChannel)
	router.PUT("/channels/website/:channelID/chat-interface", s.updateWebsiteChannelChatInterface)
	router.PUT("/channels/website/:channelID/access", s.updateWebsiteChannelAccess)
	router.POST("/channels/:channelID/deactivate", s.deactivateMessageChannel)
	router.POST("/channels/:channelID/activate", s.activateMessageChannel)
	router.GET("/channels/options", s.listChannelOptions)
	router.GET("/members/options", s.listMemberOptions)
	router.GET("/agents/model-options", s.listAgentModelOptions)
	router.POST("/agents", s.createAgent)
	router.GET("/agents", s.listAgents)
	router.GET("/agents/:agentID", s.getAgent)
	router.PUT("/agents/:agentID", s.updateAgent)
	router.PUT("/agents/:agentID/execution", s.updateAgentExecution)
	router.PUT("/agents/:agentID/work-status", s.updateAgentWorkStatus)
	router.POST("/agents/:agentID/deactivate", s.deactivateAgent)
	router.POST("/agents/:agentID/reactivate", s.reactivateAgent)
	router.GET("/users", s.listUsers)
	router.GET("/users/:userID", s.getUser)
	router.POST("/users", s.createUser)
	router.PUT("/users/:userID", s.updateUser)
	router.PATCH("/roles/assignments", s.updateRoleAssignments)
	router.POST("/users/:userID/deactivate", s.deactivateUser)
	router.POST("/users/:userID/reactivate", s.reactivateUser)
	router.GET("/teams", s.listTeams)
	router.POST("/teams", s.createTeam)
	router.PUT("/teams/:teamID", s.updateTeam)
	router.DELETE("/teams/:teamID", s.deleteTeam)
	router.GET("/teams/:teamID/members", s.listTeamMembers)
	router.GET("/teams/:teamID/member-candidates", s.listTeamMemberCandidates)
	router.POST("/teams/:teamID/members", s.addTeamMembers)
	router.POST("/teams/:teamID/members/remove", s.removeTeamMembers)
	router.GET("/knowledge-bases/:knowledgeBaseID/documents", s.listKnowledgeDocuments)
	router.GET("/knowledge-bases/:knowledgeBaseID/documents/:documentID", s.getKnowledgeDocument)
	router.POST("/knowledge-bases/:knowledgeBaseID/documents", s.createKnowledgeDocuments)
	router.PUT("/knowledge-bases/:knowledgeBaseID/documents/:documentID/group", s.moveKnowledgeDocument)
	router.DELETE("/knowledge-bases/:knowledgeBaseID/documents/:documentID", s.deleteKnowledgeDocument)
	router.GET("/knowledge-bases/:knowledgeBaseID/documents/:documentID/preview", s.getKnowledgeDocumentPreview)
	router.GET("/knowledge-bases/:knowledgeBaseID/qa-entries", s.listKnowledgeQAEntries)
	router.GET("/knowledge-bases/:knowledgeBaseID/qa-entries/:entryID", s.getKnowledgeQAEntry)
	router.POST("/knowledge-bases/:knowledgeBaseID/qa-entries", s.createKnowledgeQAEntry)
	router.PUT("/knowledge-bases/:knowledgeBaseID/qa-entries/:entryID", s.updateKnowledgeQAEntry)
	router.DELETE("/knowledge-bases/:knowledgeBaseID/qa-entries/:entryID", s.deleteKnowledgeQAEntry)
	router.GET("/knowledge-bases", s.listKnowledgeBases)
	router.GET("/knowledge-bases/:knowledgeBaseID", s.getKnowledgeBase)
	router.POST("/knowledge-bases", s.createKnowledgeBase)
	router.PUT("/knowledge-bases/:knowledgeBaseID", s.updateKnowledgeBase)
	router.DELETE("/knowledge-bases/:knowledgeBaseID", s.deleteKnowledgeBase)
	router.POST("/knowledge-bases/:knowledgeBaseID/groups", s.createKnowledgeGroup)
	router.PUT("/knowledge-bases/:knowledgeBaseID/groups/:groupID", s.updateKnowledgeGroup)
	router.DELETE("/knowledge-bases/:knowledgeBaseID/groups/:groupID", s.deleteKnowledgeGroup)
	router.GET("/contacts/:contactID", s.getContact)
	router.POST("/contacts", s.createContact)
	router.PUT("/contacts/:contactID", s.updateContact)
	router.DELETE("/contacts/:contactID", s.deleteContact)
	router.POST("/contacts/:contactID/restore", s.restoreContact)
	router.GET("/settings/roles", s.listRoles)
	router.GET("/settings/roles/:roleID", s.getRole)
	router.POST("/settings/roles", s.createRole)
	router.PUT("/settings/roles/:roleID", s.updateRole)
	router.DELETE("/settings/roles/:roleID", s.deleteRole)
	router.GET("/integrations/model-services", s.listAIProviders)
	router.GET("/integrations/model-services/:providerID", s.getAIProvider)
	router.GET("/integrations/model-services/models", s.listAvailableAIModels)
	router.POST("/integrations/model-services/test", s.testAIProviderConnection)
	router.POST("/integrations/model-services", s.createAIProvider)
	router.PUT("/integrations/model-services/:providerID", s.updateAIProvider)
	router.DELETE("/integrations/model-services/:providerID", s.deleteAIProvider)
	router.GET("/integrations/business-systems", s.listBusinessSystems)
	router.GET("/integrations/business-systems/:businessSystemID", s.getBusinessSystem)
	router.POST("/integrations/business-systems", s.createBusinessSystem)
	router.PUT("/integrations/business-systems/:businessSystemID", s.updateBusinessSystem)
	router.DELETE("/integrations/business-systems/:businessSystemID", s.deleteBusinessSystem)
	router.GET("/integrations/mcp-servers", s.listMCPServers)
	router.GET("/integrations/mcp-servers/:mcpServerID", s.getMCPServer)
	router.POST("/integrations/mcp-servers/test-connection", s.testMCPServerConnection)
	router.POST("/integrations/mcp-servers/:mcpServerID/test-connection", s.testSavedMCPServerConnection)
	router.POST("/integrations/mcp-servers/refresh-tools", s.refreshMCPServerTools)
	router.POST("/integrations/mcp-servers", s.createMCPServer)
	router.PUT("/integrations/mcp-servers/:mcpServerID", s.updateMCPServer)
	router.DELETE("/integrations/mcp-servers/:mcpServerID", s.deleteMCPServer)
	router.PUT("/settings/organization", s.updateOrganization)
	router.GET("/settings/storage/s3", s.getS3Setting)
	router.PUT("/settings/storage/s3", s.saveS3Setting)
	router.POST("/settings/storage/s3/test", s.testS3Setting)
}

// installationStatus 返回服务端初始化状态和公开企业名称。
func (s *Service) installationStatus(c *gin.Context) {
	output, err := s.application.InstallationStatus(c.Request.Context(), requestMeta(c))
	writeResult(c, http.StatusOK, output, err)
}

// login 校验账号密码并建立登录会话。
func (s *Service) login(c *gin.Context) {
	var input appservice.LoginInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.Login(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusOK, output, err)
}

// logout 退出当前登录会话。
func (s *Service) logout(c *gin.Context) {
	writeEmpty(c, s.application.Logout(c.Request.Context(), requestMeta(c)))
}

// loadIdentity 返回当前登录身份。
func (s *Service) loadIdentity(c *gin.Context) {
	output, err := s.application.LoadIdentity(c.Request.Context(), requestMeta(c))
	writeResult(c, http.StatusOK, output, err)
}

// updateProfile 修改当前用户的头像、姓名和邮箱。
func (s *Service) updateProfile(c *gin.Context) {
	var input appservice.ProfileInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.UpdateProfile(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusOK, output, err)
}

// createFileUpload 创建文件上传请求。
func (s *Service) createFileUpload(c *gin.Context) {
	var input appservice.FileUploadInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.CreateFileUpload(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusCreated, output, err)
}

// completeFileUpload 核验并完成文件上传。
func (s *Service) completeFileUpload(c *gin.Context) {
	output, err := s.application.CompleteFileUpload(c.Request.Context(), requestMeta(c), c.Param("fileID"))
	writeResult(c, http.StatusOK, output, err)
}

// createFilePartUpload 创建一个分片的直传请求。
func (s *Service) createFilePartUpload(c *gin.Context) {
	var input appservice.FilePartUploadInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.CreateFilePartUpload(c.Request.Context(), requestMeta(c), c.Param("fileID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// prepareFileUpload 为已有文件记录准备直传请求。
func (s *Service) prepareFileUpload(c *gin.Context) {
	output, err := s.application.PrepareFileUpload(c.Request.Context(), requestMeta(c), c.Param("fileID"))
	writeResult(c, http.StatusOK, output, err)
}

// completeAttachmentUpload 完成文件上传并激活原附件消息。
func (s *Service) completeAttachmentUpload(c *gin.Context) {
	writeEmpty(c, s.application.CompleteAttachmentUpload(c.Request.Context(), requestMeta(c), c.Param("fileID")))
}

// cancelFileUpload 将未发送的临时文件交给清理任务。
func (s *Service) cancelFileUpload(c *gin.Context) {
	writeEmpty(c, s.application.CancelFileUpload(c.Request.Context(), requestMeta(c), c.Param("fileID")))
}

// sendAttachmentMessage 发送内部单聊或群聊附件消息。
func (s *Service) sendAttachmentMessage(c *gin.Context) {
	var input appservice.AttachmentMessageInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.SendAttachmentMessage(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusCreated, output, err)
}

// sendAttachmentBatch 按选择顺序保存可带说明的单聊附件消息。
func (s *Service) sendAttachmentBatch(c *gin.Context) {
	var input appservice.AttachmentBatchInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.SendAttachmentBatch(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusCreated, output, err)
}

// updateAttachmentUploads 更新附件上传状态或取消尚未完成的消息。
func (s *Service) updateAttachmentUploads(c *gin.Context) {
	var input appservice.AttachmentUploadUpdate
	if !bindJSON(c, &input) {
		return
	}
	writeEmpty(c, s.application.UpdateAttachmentUploads(c.Request.Context(), requestMeta(c), input))
}

// listAttachmentStates 读取窗口内已存在附件消息的最新状态。
func (s *Service) listAttachmentStates(c *gin.Context) {
	input, ok := bindAttachmentStateListInputQuery(c)
	if !ok {
		return
	}
	output, err := s.application.ListAttachmentStates(c.Request.Context(), requestMeta(c), c.Param("conversationID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// getAttachmentDownload 签发当前成员可见消息附件的下载地址。
func (s *Service) getAttachmentDownload(c *gin.Context) {
	output, err := s.application.GetAttachmentDownload(c.Request.Context(), requestMeta(c), c.Param("conversationID"), c.Param("messageID"))
	writeResult(c, http.StatusOK, output, err)
}

// changePassword 核验当前密码并保存新密码。
func (s *Service) changePassword(c *gin.Context) {
	var input appservice.ChangePasswordInput
	if !bindJSON(c, &input) {
		return
	}
	writeEmpty(c, s.application.ChangePassword(c.Request.Context(), requestMeta(c), input))
}

// updateUserPreferences 保存当前用户的偏好设置。
func (s *Service) updateUserPreferences(c *gin.Context) {
	var input appservice.UserPreferencesInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.UpdateUserPreferences(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusOK, output, err)
}

// updateUserWorkStatus 保存当前用户主动设置的工作状态。
func (s *Service) updateUserWorkStatus(c *gin.Context) {
	var input appservice.UserWorkStatusInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.UpdateUserWorkStatus(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusOK, output, err)
}

// loadInbox 返回当前用户的统一收件箱。
func (s *Service) loadInbox(c *gin.Context) {
	input, ok := bindLoadInboxInputQuery(c)
	if !ok {
		return
	}
	output, err := s.application.LoadInbox(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusOK, output, err)
}

// getInboxContext 返回会话锚点的当前资格和原位置邻域。
func (s *Service) getInboxContext(c *gin.Context) {
	var input appservice.InboxContextInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.GetInboxContext(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusOK, output, err)
}

// readInboxWindow 重读已加载双向边界之间的完整列表范围。
func (s *Service) readInboxWindow(c *gin.Context) {
	var input appservice.InboxWindowInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.ReadInboxWindow(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusOK, output, err)
}

// getInboxConversation 返回当前用户有权阅读的独立会话摘要。
func (s *Service) getInboxConversation(c *gin.Context) {
	output, err := s.application.GetInboxConversation(c.Request.Context(), requestMeta(c), c.Param("conversationID"))
	writeResult(c, http.StatusOK, output, err)
}

// readInboxConversations 按 ID 批量返回会话摘要及当前筛选资格。
func (s *Service) readInboxConversations(c *gin.Context) {
	var input appservice.ReadInboxConversationsInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.ReadInboxConversations(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusOK, output, err)
}

// listCustomerServiceAssignees 返回有效真人和 AI 客服。
func (s *Service) listCustomerServiceAssignees(c *gin.Context) {
	output, err := s.application.ListCustomerServiceAssignees(c.Request.Context(), requestMeta(c))
	writeResult(c, http.StatusOK, output, err)
}

// listConversationMessages 返回成员可见的会话消息。
func (s *Service) listConversationMessages(c *gin.Context) {
	input, ok := bindConversationMessageListInputQuery(c)
	if !ok {
		return
	}
	output, err := s.application.ListConversationMessages(c.Request.Context(), requestMeta(c), c.Param("conversationID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// listConversationMessageReferences 读取当前窗口的引用摘要和回复可用状态。
func (s *Service) listConversationMessageReferences(c *gin.Context) {
	input, ok := bindConversationMessageReferenceListInputQuery(c)
	if !ok {
		return
	}
	output, err := s.application.ListConversationMessageReferences(c.Request.Context(), requestMeta(c), c.Param("conversationID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// getConversationMessageContext 返回目标消息及其前后上下文。
func (s *Service) getConversationMessageContext(c *gin.Context) {
	output, err := s.application.GetConversationMessageContext(c.Request.Context(), requestMeta(c), c.Param("conversationID"), c.Param("messageID"))
	writeResult(c, http.StatusOK, output, err)
}

// getConversationNavigationState 返回群聊提及进度和最新可见消息。
func (s *Service) getConversationNavigationState(c *gin.Context) {
	output, err := s.application.GetConversationNavigationState(c.Request.Context(), requestMeta(c), c.Param("conversationID"))
	writeResult(c, http.StatusOK, output, err)
}

// listPendingConversationMentions 返回本轮待查看提及目标。
func (s *Service) listPendingConversationMentions(c *gin.Context) {
	output, err := s.application.ListPendingConversationMentions(c.Request.Context(), requestMeta(c), c.Param("conversationID"))
	writeResult(c, http.StatusOK, output, err)
}

// markConversationMentionReviewed 确认已查看的群聊提及。
func (s *Service) markConversationMentionReviewed(c *gin.Context) {
	var input appservice.MarkConversationMentionReviewedInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.MarkConversationMentionReviewed(c.Request.Context(), requestMeta(c), c.Param("conversationID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// markConversationRead 单调推进当前用户的会话已读水位。
func (s *Service) markConversationRead(c *gin.Context) {
	var input appservice.MarkConversationReadInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.MarkConversationRead(c.Request.Context(), requestMeta(c), c.Param("conversationID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// updateConversationUnreadMark 保存当前用户独立于阅读水位的未读标记。
func (s *Service) updateConversationUnreadMark(c *gin.Context) {
	var input appservice.ConversationUnreadMarkInput
	if !bindJSON(c, &input) {
		return
	}
	writeEmpty(c, s.application.UpdateConversationUnreadMark(c.Request.Context(), requestMeta(c), c.Param("conversationID"), input))
}

// updateConversationNotificationSettings 保存当前用户的原生会话提醒设置。
func (s *Service) updateConversationNotificationSettings(c *gin.Context) {
	var input appservice.ConversationNotificationSettingsInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.UpdateConversationNotificationSettings(c.Request.Context(), requestMeta(c), c.Param("conversationID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// sendCustomerTextMessage 发送客户会话文本消息。
func (s *Service) sendCustomerTextMessage(c *gin.Context) {
	var input appservice.CustomerTextMessageInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.SendCustomerTextMessage(c.Request.Context(), requestMeta(c), c.Param("conversationID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// listCustomerMessageDeliveries 读取当前窗口的外部投递状态。
func (s *Service) listCustomerMessageDeliveries(c *gin.Context) {
	input, ok := bindCustomerDeliveryListInputQuery(c)
	if !ok {
		return
	}
	output, err := s.application.ListCustomerMessageDeliveries(c.Request.Context(), requestMeta(c), c.Param("conversationID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// resolveCustomerMessageDelivery 人工处理失败或待确认的投递。
func (s *Service) resolveCustomerMessageDelivery(c *gin.Context) {
	var input appservice.CustomerDeliveryResolveInput
	if !bindJSON(c, &input) {
		return
	}
	writeEmpty(c, s.application.ResolveCustomerMessageDelivery(c.Request.Context(), requestMeta(c), c.Param("conversationID"), c.Param("deliveryID"), input))
}

// claimServiceSession 领取或接管客户会话最新处理周期。
func (s *Service) claimServiceSession(c *gin.Context) {
	output, err := s.application.ClaimServiceSession(c.Request.Context(), requestMeta(c), c.Param("conversationID"))
	writeResult(c, http.StatusOK, output, err)
}

// transferServiceSession 把当前负责的处理周期转给另一位客服。
func (s *Service) transferServiceSession(c *gin.Context) {
	var input appservice.TransferServiceSessionInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.TransferServiceSession(c.Request.Context(), requestMeta(c), c.Param("conversationID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// closeServiceSession 关闭客户会话最新处理周期。
func (s *Service) closeServiceSession(c *gin.Context) {
	output, err := s.application.CloseServiceSession(c.Request.Context(), requestMeta(c), c.Param("conversationID"))
	writeResult(c, http.StatusOK, output, err)
}

// reopenServiceSession 重新打开客户会话最新处理周期并分配给当前身份。
func (s *Service) reopenServiceSession(c *gin.Context) {
	output, err := s.application.ReopenServiceSession(c.Request.Context(), requestMeta(c), c.Param("conversationID"))
	writeResult(c, http.StatusOK, output, err)
}

// sendFirstDirectTextMessage 向目标身份发送首条单聊消息并按需创建长期会话。
func (s *Service) sendFirstDirectTextMessage(c *gin.Context) {
	var input appservice.FirstDirectTextMessageInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.SendFirstDirectTextMessage(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusOK, output, err)
}

// sendFirstAgentTextMessage 在首次发送时创建独立 AI 聊天。
func (s *Service) sendFirstAgentTextMessage(c *gin.Context) {
	var input appservice.FirstAgentTextMessageInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.SendFirstAgentTextMessage(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusOK, output, err)
}

// sendAgentTextMessage 向已有 AI 会话发送文本消息。
func (s *Service) sendAgentTextMessage(c *gin.Context) {
	var input appservice.AgentTextMessageInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.SendAgentTextMessage(c.Request.Context(), requestMeta(c), c.Param("conversationID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// stopAgentReply 停止独立 AI 会话中指定的回复并返回实际运行状态。
func (s *Service) stopAgentReply(c *gin.Context) {
	output, err := s.application.StopAgentReply(c.Request.Context(), requestMeta(c), c.Param("conversationID"), c.Param("runID"))
	writeResult(c, http.StatusOK, output, err)
}

// findDirectConversation 按目标身份查找当前成员的活跃单聊。
func (s *Service) findDirectConversation(c *gin.Context) {
	output, err := s.application.FindDirectConversation(c.Request.Context(), requestMeta(c), c.Param("targetIdentityID"))
	writeResult(c, http.StatusOK, output, err)
}

// sendDirectTextMessage 发送内部单聊文本消息。
func (s *Service) sendDirectTextMessage(c *gin.Context) {
	var input appservice.DirectTextMessageInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.SendDirectTextMessage(c.Request.Context(), requestMeta(c), c.Param("conversationID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// createGroupConversation 创建企业内部群聊。
func (s *Service) createGroupConversation(c *gin.Context) {
	var input appservice.GroupConversationInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.CreateGroupConversation(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusCreated, output, err)
}

// getGroupConversation 返回当前成员可见的群聊资料。
func (s *Service) getGroupConversation(c *gin.Context) {
	output, err := s.application.GetGroupConversation(c.Request.Context(), requestMeta(c), c.Param("conversationID"))
	writeResult(c, http.StatusOK, output, err)
}

// updateGroupConversation 修改群聊资料。
func (s *Service) updateGroupConversation(c *gin.Context) {
	var input appservice.GroupConversationProfileInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.UpdateGroupConversation(c.Request.Context(), requestMeta(c), c.Param("conversationID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// addGroupConversationMembers 批量增加群聊成员。
func (s *Service) addGroupConversationMembers(c *gin.Context) {
	var input appservice.GroupConversationMembersInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.AddGroupConversationMembers(c.Request.Context(), requestMeta(c), c.Param("conversationID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// removeGroupConversationMember 移除单个群聊成员。
func (s *Service) removeGroupConversationMember(c *gin.Context) {
	var input appservice.GroupConversationMemberInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.RemoveGroupConversationMember(c.Request.Context(), requestMeta(c), c.Param("conversationID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// transferGroupConversationOwner 转让群主。
func (s *Service) transferGroupConversationOwner(c *gin.Context) {
	var input appservice.GroupConversationOwnerInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.TransferGroupConversationOwner(c.Request.Context(), requestMeta(c), c.Param("conversationID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// leaveGroupConversation 退出普通成员参与的群聊。
func (s *Service) leaveGroupConversation(c *gin.Context) {
	writeEmpty(c, s.application.LeaveGroupConversation(c.Request.Context(), requestMeta(c), c.Param("conversationID")))
}

// dissolveGroupConversation 解散群聊并保留当前成员的只读历史。
func (s *Service) dissolveGroupConversation(c *gin.Context) {
	output, err := s.application.DissolveGroupConversation(c.Request.Context(), requestMeta(c), c.Param("conversationID"))
	writeResult(c, http.StatusOK, output, err)
}

// sendGroupTextMessage 发送企业内部群聊文本消息。
func (s *Service) sendGroupTextMessage(c *gin.Context) {
	var input appservice.GroupTextMessageInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.SendGroupTextMessage(c.Request.Context(), requestMeta(c), c.Param("conversationID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// listMessageChannels 返回消息渠道列表。
func (s *Service) listMessageChannels(c *gin.Context) {
	output, err := s.application.ListMessageChannels(c.Request.Context(), requestMeta(c))
	writeResult(c, http.StatusOK, output, err)
}

// getWebsiteChannel 返回网站渠道详情。
func (s *Service) getWebsiteChannel(c *gin.Context) {
	output, err := s.application.GetWebsiteChannel(c.Request.Context(), requestMeta(c), c.Param("channelID"))
	writeResult(c, http.StatusOK, output, err)
}

// getTelegramChannel 返回 Telegram 渠道详情。
func (s *Service) getTelegramChannel(c *gin.Context) {
	output, err := s.application.GetTelegramChannel(c.Request.Context(), requestMeta(c), c.Param("channelID"))
	writeResult(c, http.StatusOK, output, err)
}

// testTelegramChannelConnection 测试 Telegram 草稿 Token。
func (s *Service) testTelegramChannelConnection(c *gin.Context) {
	var input appservice.TelegramChannelConnectionTestInput
	if !bindJSON(c, &input) {
		return
	}
	writeEmpty(c, s.application.TestTelegramChannelConnection(c.Request.Context(), requestMeta(c), c.Param("channelID"), input))
}

// saveTelegramChannelConnection 保存 Telegram 机器人和 Webhook 设置。
func (s *Service) saveTelegramChannelConnection(c *gin.Context) {
	var input appservice.TelegramChannelConnectionInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.SaveTelegramChannelConnection(c.Request.Context(), requestMeta(c), c.Param("channelID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// getMessageChannel 返回消息渠道基础信息。
func (s *Service) getMessageChannel(c *gin.Context) {
	output, err := s.application.GetMessageChannel(c.Request.Context(), requestMeta(c), c.Param("channelID"))
	writeResult(c, http.StatusOK, output, err)
}

// createMessageChannel 创建消息渠道。
func (s *Service) createMessageChannel(c *gin.Context) {
	var input appservice.CreateMessageChannelInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.CreateMessageChannel(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusCreated, output, err)
}

// updateMessageChannel 修改消息渠道基础信息。
func (s *Service) updateMessageChannel(c *gin.Context) {
	var input appservice.MessageChannelInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.UpdateMessageChannel(c.Request.Context(), requestMeta(c), c.Param("channelID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// updateWebsiteChannelChatInterface 修改网站渠道聊天界面。
func (s *Service) updateWebsiteChannelChatInterface(c *gin.Context) {
	var input appservice.WebsiteChannelChatInterfaceInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.UpdateWebsiteChannelChatInterface(c.Request.Context(), requestMeta(c), c.Param("channelID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// updateWebsiteChannelAccess 修改网站渠道允许使用的网站。
func (s *Service) updateWebsiteChannelAccess(c *gin.Context) {
	var input appservice.WebsiteChannelAccessInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.UpdateWebsiteChannelAccess(c.Request.Context(), requestMeta(c), c.Param("channelID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// deactivateMessageChannel 停用消息渠道。
func (s *Service) deactivateMessageChannel(c *gin.Context) {
	output, err := s.application.DeactivateMessageChannel(c.Request.Context(), requestMeta(c), c.Param("channelID"))
	writeResult(c, http.StatusOK, output, err)
}

// activateMessageChannel 启用消息渠道。
func (s *Service) activateMessageChannel(c *gin.Context) {
	output, err := s.application.ActivateMessageChannel(c.Request.Context(), requestMeta(c), c.Param("channelID"))
	writeResult(c, http.StatusOK, output, err)
}

// listChannelOptions 返回当前企业的渠道选择项。
func (s *Service) listChannelOptions(c *gin.Context) {
	output, err := s.application.ListChannelOptions(c.Request.Context(), requestMeta(c))
	writeResult(c, http.StatusOK, output, err)
}

// listMemberOptions 返回可分配的企业成员和 AI 员工。
func (s *Service) listMemberOptions(c *gin.Context) {
	input, ok := bindMemberOptionListInputQuery(c)
	if !ok {
		return
	}
	output, err := s.application.ListMemberOptions(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusOK, output, err)
}

// listAgentModelOptions 返回 AI 员工可使用的对话模型。
func (s *Service) listAgentModelOptions(c *gin.Context) {
	output, err := s.application.ListAgentModelOptions(c.Request.Context(), requestMeta(c))
	writeResult(c, http.StatusOK, output, err)
}

// createAgent 创建企业 AI 员工。
func (s *Service) createAgent(c *gin.Context) {
	var input appservice.CreateAgentInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.CreateAgent(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusCreated, output, err)
}

// listAgents 返回企业 AI 员工目录。
func (s *Service) listAgents(c *gin.Context) {
	input, ok := bindAgentListInputQuery(c)
	if !ok {
		return
	}
	output, err := s.application.ListAgents(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusOK, output, err)
}

// getAgent 返回企业 AI 员工详情。
func (s *Service) getAgent(c *gin.Context) {
	output, err := s.application.GetAgent(c.Request.Context(), requestMeta(c), c.Param("agentID"))
	writeResult(c, http.StatusOK, output, err)
}

// updateAgent 修改企业 AI 员工。
func (s *Service) updateAgent(c *gin.Context) {
	var input appservice.UpdateAgentInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.UpdateAgent(c.Request.Context(), requestMeta(c), c.Param("agentID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// updateAgentExecution 修改企业 AI 员工的执行配置。
func (s *Service) updateAgentExecution(c *gin.Context) {
	var input appservice.AgentExecutionInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.UpdateAgentExecution(c.Request.Context(), requestMeta(c), c.Param("agentID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// updateAgentWorkStatus 修改企业 AI 员工工作状态。
func (s *Service) updateAgentWorkStatus(c *gin.Context) {
	var input appservice.AgentWorkStatusInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.UpdateAgentWorkStatus(c.Request.Context(), requestMeta(c), c.Param("agentID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// deactivateAgent 禁用企业 AI 员工账号。
func (s *Service) deactivateAgent(c *gin.Context) {
	output, err := s.application.DeactivateAgent(c.Request.Context(), requestMeta(c), c.Param("agentID"))
	writeResult(c, http.StatusOK, output, err)
}

// reactivateAgent 恢复企业 AI 员工。
func (s *Service) reactivateAgent(c *gin.Context) {
	output, err := s.application.ReactivateAgent(c.Request.Context(), requestMeta(c), c.Param("agentID"))
	writeResult(c, http.StatusOK, output, err)
}

// listUsers 返回企业成员列表。
func (s *Service) listUsers(c *gin.Context) {
	input, ok := bindUserListInputQuery(c)
	if !ok {
		return
	}
	output, err := s.application.ListUsers(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusOK, output, err)
}

// getUser 返回企业成员详情。
func (s *Service) getUser(c *gin.Context) {
	output, err := s.application.GetUser(c.Request.Context(), requestMeta(c), c.Param("userID"))
	writeResult(c, http.StatusOK, output, err)
}

// createUser 创建企业成员账号。
func (s *Service) createUser(c *gin.Context) {
	var input appservice.CreateUserInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.CreateUser(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusCreated, output, err)
}

// updateUser 修改企业成员资料、角色和所属团队。
func (s *Service) updateUser(c *gin.Context) {
	var input appservice.UpdateUserInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.UpdateUser(c.Request.Context(), requestMeta(c), c.Param("userID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// updateRoleAssignments 在一个事务中批量调整真人和 AI 员工角色。
func (s *Service) updateRoleAssignments(c *gin.Context) {
	var input appservice.RoleAssignmentsInput
	if !bindJSON(c, &input) {
		return
	}
	writeEmpty(c, s.application.UpdateRoleAssignments(c.Request.Context(), requestMeta(c), input))
}

// deactivateUser 禁用企业成员账号。
func (s *Service) deactivateUser(c *gin.Context) {
	output, err := s.application.DeactivateUser(c.Request.Context(), requestMeta(c), c.Param("userID"))
	writeResult(c, http.StatusOK, output, err)
}

// reactivateUser 恢复企业成员账号。
func (s *Service) reactivateUser(c *gin.Context) {
	output, err := s.application.ReactivateUser(c.Request.Context(), requestMeta(c), c.Param("userID"))
	writeResult(c, http.StatusOK, output, err)
}

// listTeams 返回企业团队列表。
func (s *Service) listTeams(c *gin.Context) {
	input, ok := bindTeamListInputQuery(c)
	if !ok {
		return
	}
	output, err := s.application.ListTeams(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusOK, output, err)
}

// createTeam 创建企业团队。
func (s *Service) createTeam(c *gin.Context) {
	var input appservice.TeamInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.CreateTeam(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusCreated, output, err)
}

// updateTeam 修改企业团队。
func (s *Service) updateTeam(c *gin.Context) {
	var input appservice.TeamInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.UpdateTeam(c.Request.Context(), requestMeta(c), c.Param("teamID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// deleteTeam 删除企业团队及其成员关系。
func (s *Service) deleteTeam(c *gin.Context) {
	writeEmpty(c, s.application.DeleteTeam(c.Request.Context(), requestMeta(c), c.Param("teamID")))
}

// listTeamMembers 返回团队成员列表。
func (s *Service) listTeamMembers(c *gin.Context) {
	input, ok := bindTeamMemberListInputQuery(c)
	if !ok {
		return
	}
	output, err := s.application.ListTeamMembers(c.Request.Context(), requestMeta(c), c.Param("teamID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// listTeamMemberCandidates 返回尚未加入团队的企业身份。
func (s *Service) listTeamMemberCandidates(c *gin.Context) {
	input, ok := bindTeamMemberCandidateInputQuery(c)
	if !ok {
		return
	}
	output, err := s.application.ListTeamMemberCandidates(c.Request.Context(), requestMeta(c), c.Param("teamID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// addTeamMembers 将企业身份批量加入团队。
func (s *Service) addTeamMembers(c *gin.Context) {
	var input appservice.TeamMemberInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.AddTeamMembers(c.Request.Context(), requestMeta(c), c.Param("teamID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// removeTeamMembers 将企业身份批量移出团队。
func (s *Service) removeTeamMembers(c *gin.Context) {
	var input appservice.TeamMemberInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.RemoveTeamMembers(c.Request.Context(), requestMeta(c), c.Param("teamID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// listKnowledgeDocuments 返回当前分组的文档列表。
func (s *Service) listKnowledgeDocuments(c *gin.Context) {
	input, ok := bindKnowledgeDocumentListInputQuery(c)
	if !ok {
		return
	}
	output, err := s.application.ListKnowledgeDocuments(c.Request.Context(), requestMeta(c), c.Param("knowledgeBaseID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// getKnowledgeDocument 返回文档详情。
func (s *Service) getKnowledgeDocument(c *gin.Context) {
	output, err := s.application.GetKnowledgeDocument(c.Request.Context(), requestMeta(c), c.Param("knowledgeBaseID"), c.Param("documentID"))
	writeResult(c, http.StatusOK, output, err)
}

// createKnowledgeDocuments 保存最多十个已上传的文档原件。
func (s *Service) createKnowledgeDocuments(c *gin.Context) {
	var input appservice.KnowledgeDocumentBatchInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.CreateKnowledgeDocuments(c.Request.Context(), requestMeta(c), c.Param("knowledgeBaseID"), input)
	writeResult(c, http.StatusCreated, output, err)
}

// moveKnowledgeDocument 移动文档到同库分组。
func (s *Service) moveKnowledgeDocument(c *gin.Context) {
	var input appservice.KnowledgeDocumentMoveInput
	if !bindJSON(c, &input) {
		return
	}
	writeEmpty(c, s.application.MoveKnowledgeDocument(c.Request.Context(), requestMeta(c), c.Param("knowledgeBaseID"), c.Param("documentID"), input))
}

// deleteKnowledgeDocument 删除文档并释放原件。
func (s *Service) deleteKnowledgeDocument(c *gin.Context) {
	writeEmpty(c, s.application.DeleteKnowledgeDocument(c.Request.Context(), requestMeta(c), c.Param("knowledgeBaseID"), c.Param("documentID")))
}

// getKnowledgeDocumentPreview 签发当前文档的原件预览请求。
func (s *Service) getKnowledgeDocumentPreview(c *gin.Context) {
	output, err := s.application.GetKnowledgeDocumentPreview(c.Request.Context(), requestMeta(c), c.Param("knowledgeBaseID"), c.Param("documentID"))
	writeResult(c, http.StatusOK, output, err)
}

// listKnowledgeQAEntries 返回分组中的本地问答列表。
func (s *Service) listKnowledgeQAEntries(c *gin.Context) {
	input, ok := bindKnowledgeQAListInputQuery(c)
	if !ok {
		return
	}
	output, err := s.application.ListKnowledgeQAEntries(c.Request.Context(), requestMeta(c), c.Param("knowledgeBaseID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// getKnowledgeQAEntry 返回完整的本地问答。
func (s *Service) getKnowledgeQAEntry(c *gin.Context) {
	output, err := s.application.GetKnowledgeQAEntry(c.Request.Context(), requestMeta(c), c.Param("knowledgeBaseID"), c.Param("entryID"))
	writeResult(c, http.StatusOK, output, err)
}

// createKnowledgeQAEntry 创建本地问答。
func (s *Service) createKnowledgeQAEntry(c *gin.Context) {
	var input appservice.KnowledgeQAInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.CreateKnowledgeQAEntry(c.Request.Context(), requestMeta(c), c.Param("knowledgeBaseID"), input)
	writeResult(c, http.StatusCreated, output, err)
}

// updateKnowledgeQAEntry 修改本地问答。
func (s *Service) updateKnowledgeQAEntry(c *gin.Context) {
	var input appservice.KnowledgeQAInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.UpdateKnowledgeQAEntry(c.Request.Context(), requestMeta(c), c.Param("knowledgeBaseID"), c.Param("entryID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// deleteKnowledgeQAEntry 删除本地问答。
func (s *Service) deleteKnowledgeQAEntry(c *gin.Context) {
	writeEmpty(c, s.application.DeleteKnowledgeQAEntry(c.Request.Context(), requestMeta(c), c.Param("knowledgeBaseID"), c.Param("entryID")))
}

// listKnowledgeBases 返回当前企业的知识库列表。
func (s *Service) listKnowledgeBases(c *gin.Context) {
	output, err := s.application.ListKnowledgeBases(c.Request.Context(), requestMeta(c))
	writeResult(c, http.StatusOK, output, err)
}

// getKnowledgeBase 返回当前企业中的知识库详情。
func (s *Service) getKnowledgeBase(c *gin.Context) {
	output, err := s.application.GetKnowledgeBase(c.Request.Context(), requestMeta(c), c.Param("knowledgeBaseID"))
	writeResult(c, http.StatusOK, output, err)
}

// createKnowledgeBase 创建企业知识库。
func (s *Service) createKnowledgeBase(c *gin.Context) {
	var input appservice.KnowledgeBaseInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.CreateKnowledgeBase(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusCreated, output, err)
}

// updateKnowledgeBase 修改企业知识库。
func (s *Service) updateKnowledgeBase(c *gin.Context) {
	var input appservice.KnowledgeBaseInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.UpdateKnowledgeBase(c.Request.Context(), requestMeta(c), c.Param("knowledgeBaseID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// deleteKnowledgeBase 删除企业知识库。
func (s *Service) deleteKnowledgeBase(c *gin.Context) {
	writeEmpty(c, s.application.DeleteKnowledgeBase(c.Request.Context(), requestMeta(c), c.Param("knowledgeBaseID")))
}

// createKnowledgeGroup 创建知识库分组。
func (s *Service) createKnowledgeGroup(c *gin.Context) {
	var input appservice.KnowledgeGroupInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.CreateKnowledgeGroup(c.Request.Context(), requestMeta(c), c.Param("knowledgeBaseID"), input)
	writeResult(c, http.StatusCreated, output, err)
}

// updateKnowledgeGroup 修改知识库分组。
func (s *Service) updateKnowledgeGroup(c *gin.Context) {
	var input appservice.KnowledgeGroupInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.UpdateKnowledgeGroup(c.Request.Context(), requestMeta(c), c.Param("knowledgeBaseID"), c.Param("groupID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// deleteKnowledgeGroup 删除不含子分组和问答的知识库分组。
func (s *Service) deleteKnowledgeGroup(c *gin.Context) {
	output, err := s.application.DeleteKnowledgeGroup(c.Request.Context(), requestMeta(c), c.Param("knowledgeBaseID"), c.Param("groupID"))
	writeResult(c, http.StatusOK, output, err)
}

// getContact 返回联系人详情。
func (s *Service) getContact(c *gin.Context) {
	output, err := s.application.GetContact(c.Request.Context(), requestMeta(c), c.Param("contactID"))
	writeResult(c, http.StatusOK, output, err)
}

// createContact 创建联系人。
func (s *Service) createContact(c *gin.Context) {
	var input appservice.ContactInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.CreateContact(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusCreated, output, err)
}

// updateContact 修改联系人。
func (s *Service) updateContact(c *gin.Context) {
	var input appservice.ContactInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.UpdateContact(c.Request.Context(), requestMeta(c), c.Param("contactID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// deleteContact 将联系人移入回收站。
func (s *Service) deleteContact(c *gin.Context) {
	writeEmpty(c, s.application.DeleteContact(c.Request.Context(), requestMeta(c), c.Param("contactID")))
}

// restoreContact 恢复联系人。
func (s *Service) restoreContact(c *gin.Context) {
	output, err := s.application.RestoreContact(c.Request.Context(), requestMeta(c), c.Param("contactID"))
	writeResult(c, http.StatusOK, output, err)
}

// listRoles 返回当前企业的角色和预定义权限目录。
func (s *Service) listRoles(c *gin.Context) {
	output, err := s.application.ListRoles(c.Request.Context(), requestMeta(c))
	writeResult(c, http.StatusOK, output, err)
}

// getRole 返回当前企业的角色详情。
func (s *Service) getRole(c *gin.Context) {
	output, err := s.application.GetRole(c.Request.Context(), requestMeta(c), c.Param("roleID"))
	writeResult(c, http.StatusOK, output, err)
}

// createRole 创建自定义角色。
func (s *Service) createRole(c *gin.Context) {
	var input appservice.RoleInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.CreateRole(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusCreated, output, err)
}

// updateRole 修改角色信息和权限。
func (s *Service) updateRole(c *gin.Context) {
	var input appservice.RoleInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.UpdateRole(c.Request.Context(), requestMeta(c), c.Param("roleID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// deleteRole 删除自定义角色。
func (s *Service) deleteRole(c *gin.Context) {
	writeEmpty(c, s.application.DeleteRole(c.Request.Context(), requestMeta(c), c.Param("roleID")))
}

// listAIProviders 返回当前企业的模型服务供应商列表。
func (s *Service) listAIProviders(c *gin.Context) {
	output, err := s.application.ListAIProviders(c.Request.Context(), requestMeta(c))
	writeResult(c, http.StatusOK, output, err)
}

// getAIProvider 返回当前企业中的模型服务供应商详情。
func (s *Service) getAIProvider(c *gin.Context) {
	output, err := s.application.GetAIProvider(c.Request.Context(), requestMeta(c), c.Param("providerID"))
	writeResult(c, http.StatusOK, output, err)
}

// listAvailableAIModels 返回指定品牌的预设模型目录。
func (s *Service) listAvailableAIModels(c *gin.Context) {
	output, err := s.application.ListAvailableAIModels(c.Request.Context(), requestMeta(c), appservice.AIProviderBrand(c.Query("brand")))
	writeResult(c, http.StatusOK, output, err)
}

// testAIProviderConnection 测试模型服务供应商草稿配置。
func (s *Service) testAIProviderConnection(c *gin.Context) {
	var input appservice.AIProviderConnectionInput
	if !bindJSON(c, &input) {
		return
	}
	writeEmpty(c, s.application.TestAIProviderConnection(c.Request.Context(), requestMeta(c), input))
}

// createAIProvider 创建模型服务供应商。
func (s *Service) createAIProvider(c *gin.Context) {
	var input appservice.AIProviderInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.CreateAIProvider(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusCreated, output, err)
}

// updateAIProvider 修改模型服务供应商。
func (s *Service) updateAIProvider(c *gin.Context) {
	var input appservice.AIProviderInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.UpdateAIProvider(c.Request.Context(), requestMeta(c), c.Param("providerID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// deleteAIProvider 删除模型服务供应商。
func (s *Service) deleteAIProvider(c *gin.Context) {
	writeEmpty(c, s.application.DeleteAIProvider(c.Request.Context(), requestMeta(c), c.Param("providerID")))
}

// listBusinessSystems 返回当前企业配置的业务系统。
func (s *Service) listBusinessSystems(c *gin.Context) {
	output, err := s.application.ListBusinessSystems(c.Request.Context(), requestMeta(c))
	writeResult(c, http.StatusOK, output, err)
}

// getBusinessSystem 返回当前企业中的业务系统详情。
func (s *Service) getBusinessSystem(c *gin.Context) {
	output, err := s.application.GetBusinessSystem(c.Request.Context(), requestMeta(c), c.Param("businessSystemID"))
	writeResult(c, http.StatusOK, output, err)
}

// createBusinessSystem 创建业务系统。
func (s *Service) createBusinessSystem(c *gin.Context) {
	var input appservice.BusinessSystemInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.CreateBusinessSystem(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusCreated, output, err)
}

// updateBusinessSystem 修改业务系统。
func (s *Service) updateBusinessSystem(c *gin.Context) {
	var input appservice.BusinessSystemInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.UpdateBusinessSystem(c.Request.Context(), requestMeta(c), c.Param("businessSystemID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// deleteBusinessSystem 删除业务系统。
func (s *Service) deleteBusinessSystem(c *gin.Context) {
	writeEmpty(c, s.application.DeleteBusinessSystem(c.Request.Context(), requestMeta(c), c.Param("businessSystemID")))
}

// listMCPServers 返回当前企业配置的 MCP 服务。
func (s *Service) listMCPServers(c *gin.Context) {
	output, err := s.application.ListMCPServers(c.Request.Context(), requestMeta(c))
	writeResult(c, http.StatusOK, output, err)
}

// getMCPServer 返回当前企业中的 MCP 服务详情。
func (s *Service) getMCPServer(c *gin.Context) {
	output, err := s.application.GetMCPServer(c.Request.Context(), requestMeta(c), c.Param("mcpServerID"))
	writeResult(c, http.StatusOK, output, err)
}

// testMCPServerConnection 测试 MCP 草稿连接配置。
func (s *Service) testMCPServerConnection(c *gin.Context) {
	var input appservice.MCPServerConnectionInput
	if !bindJSON(c, &input) {
		return
	}
	writeEmpty(c, s.application.TestMCPServerConnection(c.Request.Context(), requestMeta(c), input))
}

// testSavedMCPServerConnection 测试已保存的 MCP 服务。
func (s *Service) testSavedMCPServerConnection(c *gin.Context) {
	writeEmpty(c, s.application.TestSavedMCPServerConnection(c.Request.Context(), requestMeta(c), c.Param("mcpServerID")))
}

// refreshMCPServerTools 提交当前企业的 MCP 工具更新任务。
func (s *Service) refreshMCPServerTools(c *gin.Context) {
	writeEmpty(c, s.application.RefreshMCPServerTools(c.Request.Context(), requestMeta(c)))
}

// createMCPServer 创建 MCP 服务。
func (s *Service) createMCPServer(c *gin.Context) {
	var input appservice.MCPServerInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.CreateMCPServer(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusCreated, output, err)
}

// updateMCPServer 修改 MCP 服务。
func (s *Service) updateMCPServer(c *gin.Context) {
	var input appservice.MCPServerInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.UpdateMCPServer(c.Request.Context(), requestMeta(c), c.Param("mcpServerID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// deleteMCPServer 删除 MCP 服务。
func (s *Service) deleteMCPServer(c *gin.Context) {
	writeEmpty(c, s.application.DeleteMCPServer(c.Request.Context(), requestMeta(c), c.Param("mcpServerID")))
}

// updateOrganization 修改当前企业通用设置。
func (s *Service) updateOrganization(c *gin.Context) {
	var input appservice.OrganizationInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.UpdateOrganization(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusOK, output, err)
}

// getS3Setting 返回当前企业的对象存储设置。
func (s *Service) getS3Setting(c *gin.Context) {
	output, err := s.application.GetS3Setting(c.Request.Context(), requestMeta(c))
	writeResult(c, http.StatusOK, output, err)
}

// saveS3Setting 保存当前企业的对象存储设置。
func (s *Service) saveS3Setting(c *gin.Context) {
	var input appservice.S3SettingInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.SaveS3Setting(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusOK, output, err)
}

// testS3Setting 测试对象存储连接。
func (s *Service) testS3Setting(c *gin.Context) {
	var input appservice.S3SettingInput
	if !bindJSON(c, &input) {
		return
	}
	writeEmpty(c, s.application.TestS3Setting(c.Request.Context(), requestMeta(c), input))
}

// bindAgentListInputQuery 从查询参数解析 appservice.AgentListInput。
func bindAgentListInputQuery(c *gin.Context) (appservice.AgentListInput, bool) {
	page, ok := positiveQueryInteger(c, "page", 1)
	if !ok {
		return appservice.AgentListInput{}, false
	}
	pageSize, ok := positiveQueryInteger(c, "pageSize", 50)
	if !ok {
		return appservice.AgentListInput{}, false
	}
	return appservice.AgentListInput{
		Query:    c.Query("query"),
		Status:   optionalEnum[appservice.UserStatus](c.Query("status")),
		Page:     page,
		PageSize: pageSize,
	}, true
}

// bindAttachmentStateListInputQuery 从查询参数解析 appservice.AttachmentStateListInput。
func bindAttachmentStateListInputQuery(c *gin.Context) (appservice.AttachmentStateListInput, bool) {
	return appservice.AttachmentStateListInput{
		MessageIDs: c.Query("messageIds"),
	}, true
}

// bindConversationMessageListInputQuery 从查询参数解析 appservice.ConversationMessageListInput。
func bindConversationMessageListInputQuery(c *gin.Context) (appservice.ConversationMessageListInput, bool) {
	return appservice.ConversationMessageListInput{
		Before: c.Query("before"),
		After:  c.Query("after"),
	}, true
}

// bindConversationMessageReferenceListInputQuery 从查询参数解析 appservice.ConversationMessageReferenceListInput。
func bindConversationMessageReferenceListInputQuery(c *gin.Context) (appservice.ConversationMessageReferenceListInput, bool) {
	return appservice.ConversationMessageReferenceListInput{
		MessageIDs: c.Query("messageIds"),
	}, true
}

// bindCustomerDeliveryListInputQuery 从查询参数解析 appservice.CustomerDeliveryListInput。
func bindCustomerDeliveryListInputQuery(c *gin.Context) (appservice.CustomerDeliveryListInput, bool) {
	return appservice.CustomerDeliveryListInput{
		MessageIDs: c.Query("messageIds"),
	}, true
}

// bindKnowledgeDocumentListInputQuery 从查询参数解析 appservice.KnowledgeDocumentListInput。
func bindKnowledgeDocumentListInputQuery(c *gin.Context) (appservice.KnowledgeDocumentListInput, bool) {
	page, ok := positiveQueryInteger(c, "page", 1)
	if !ok {
		return appservice.KnowledgeDocumentListInput{}, false
	}
	pageSize, ok := positiveQueryInteger(c, "pageSize", 20)
	if !ok {
		return appservice.KnowledgeDocumentListInput{}, false
	}
	return appservice.KnowledgeDocumentListInput{
		GroupID:  c.Query("groupId"),
		Keyword:  c.Query("keyword"),
		Page:     page,
		PageSize: pageSize,
	}, true
}

// bindKnowledgeQAListInputQuery 从查询参数解析 appservice.KnowledgeQAListInput。
func bindKnowledgeQAListInputQuery(c *gin.Context) (appservice.KnowledgeQAListInput, bool) {
	page, ok := positiveQueryInteger(c, "page", 1)
	if !ok {
		return appservice.KnowledgeQAListInput{}, false
	}
	pageSize, ok := positiveQueryInteger(c, "pageSize", 20)
	if !ok {
		return appservice.KnowledgeQAListInput{}, false
	}
	return appservice.KnowledgeQAListInput{
		GroupID:  c.Query("groupId"),
		Keyword:  c.Query("keyword"),
		Page:     page,
		PageSize: pageSize,
	}, true
}

// bindLoadInboxInputQuery 从查询参数解析 appservice.LoadInboxInput。
func bindLoadInboxInputQuery(c *gin.Context) (appservice.LoadInboxInput, bool) {
	limit, ok := positiveQueryInteger(c, "limit", 50)
	if !ok {
		return appservice.LoadInboxInput{}, false
	}
	return appservice.LoadInboxInput{
		Scope:              appservice.InboxScope(c.Query("scope")),
		CustomerView:       appservice.CustomerInboxView(c.Query("customerView")),
		AssigneeIdentityID: c.Query("assigneeIdentityId"),
		Cursor:             c.Query("cursor"),
		BeforeCursor:       c.Query("beforeCursor"),
		Limit:              limit,
	}, true
}

// bindMemberOptionListInputQuery 从查询参数解析 appservice.MemberOptionListInput。
func bindMemberOptionListInputQuery(c *gin.Context) (appservice.MemberOptionListInput, bool) {
	page, ok := positiveQueryInteger(c, "page", 1)
	if !ok {
		return appservice.MemberOptionListInput{}, false
	}
	pageSize, ok := positiveQueryInteger(c, "pageSize", 50)
	if !ok {
		return appservice.MemberOptionListInput{}, false
	}
	return appservice.MemberOptionListInput{
		Query:    c.Query("query"),
		Page:     page,
		PageSize: pageSize,
	}, true
}

// bindTeamListInputQuery 从查询参数解析 appservice.TeamListInput。
func bindTeamListInputQuery(c *gin.Context) (appservice.TeamListInput, bool) {
	page, ok := positiveQueryInteger(c, "page", 1)
	if !ok {
		return appservice.TeamListInput{}, false
	}
	pageSize, ok := positiveQueryInteger(c, "pageSize", 50)
	if !ok {
		return appservice.TeamListInput{}, false
	}
	return appservice.TeamListInput{
		Query:    c.Query("query"),
		Page:     page,
		PageSize: pageSize,
	}, true
}

// bindTeamMemberCandidateInputQuery 从查询参数解析 appservice.TeamMemberCandidateInput。
func bindTeamMemberCandidateInputQuery(c *gin.Context) (appservice.TeamMemberCandidateInput, bool) {
	page, ok := positiveQueryInteger(c, "page", 1)
	if !ok {
		return appservice.TeamMemberCandidateInput{}, false
	}
	pageSize, ok := positiveQueryInteger(c, "pageSize", 50)
	if !ok {
		return appservice.TeamMemberCandidateInput{}, false
	}
	return appservice.TeamMemberCandidateInput{
		Query:    c.Query("query"),
		Page:     page,
		PageSize: pageSize,
	}, true
}

// bindTeamMemberListInputQuery 从查询参数解析 appservice.TeamMemberListInput。
func bindTeamMemberListInputQuery(c *gin.Context) (appservice.TeamMemberListInput, bool) {
	page, ok := positiveQueryInteger(c, "page", 1)
	if !ok {
		return appservice.TeamMemberListInput{}, false
	}
	pageSize, ok := positiveQueryInteger(c, "pageSize", 50)
	if !ok {
		return appservice.TeamMemberListInput{}, false
	}
	return appservice.TeamMemberListInput{
		Query:      c.Query("query"),
		WorkStatus: optionalEnum[appservice.WorkStatus](c.Query("workStatus")),
		Page:       page,
		PageSize:   pageSize,
	}, true
}

// bindUserListInputQuery 从查询参数解析 appservice.UserListInput。
func bindUserListInputQuery(c *gin.Context) (appservice.UserListInput, bool) {
	page, ok := positiveQueryInteger(c, "page", 1)
	if !ok {
		return appservice.UserListInput{}, false
	}
	pageSize, ok := positiveQueryInteger(c, "pageSize", 50)
	if !ok {
		return appservice.UserListInput{}, false
	}
	return appservice.UserListInput{
		Query:    c.Query("query"),
		Status:   optionalEnum[appservice.UserStatus](c.Query("status")),
		RoleID:   c.Query("roleId"),
		TeamID:   c.Query("teamId"),
		Page:     page,
		PageSize: pageSize,
	}, true
}
