// Code generated by appservicegen. DO NOT EDIT.

//go:build server

package api

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/runforyou-ai/cervi/internal/appservice"
)

// registerGeneratedRoutes 注册由 appservicegen 生成的业务路由。
func (s *Service) registerGeneratedRoutes(router *gin.Engine) {
	router.GET("/installation/status", s.installationStatus)
	router.POST("/auth/login", s.login)
	router.POST("/auth/logout", s.logout)
	router.GET("/auth/identity", s.loadIdentity)
	router.PATCH("/profile", s.updateProfile)
	router.POST("/files/uploads", s.createFileUpload)
	router.POST("/files/:fileID/complete", s.completeFileUpload)
	router.PATCH("/password", s.changePassword)
	router.PATCH("/preferences", s.updateUserPreferences)
	router.PATCH("/work-status", s.updateUserWorkStatus)
	router.GET("/inbox", s.loadInbox)
	router.GET("/conversations/:conversationID/messages", s.listConversationMessages)
	router.GET("/channels", s.listMessageChannels)
	router.GET("/channels/website/:channelID", s.getWebsiteChannel)
	router.GET("/channels/:channelID", s.getMessageChannel)
	router.POST("/channels", s.createMessageChannel)
	router.PUT("/channels/:channelID", s.updateMessageChannel)
	router.PUT("/channels/website/:channelID/chat-interface", s.updateWebsiteChannelChatInterface)
	router.PUT("/channels/website/:channelID/access", s.updateWebsiteChannelAccess)
	router.POST("/channels/:channelID/deactivate", s.deactivateMessageChannel)
	router.POST("/channels/:channelID/activate", s.activateMessageChannel)
	router.GET("/channels/options", s.listChannelOptions)
	router.GET("/members/options", s.listMemberOptions)
	router.GET("/agents/model-options", s.listAgentModelOptions)
	router.POST("/agents", s.createAgent)
	router.GET("/agents", s.listAgents)
	router.GET("/agents/:agentID", s.getAgent)
	router.PUT("/agents/:agentID", s.updateAgent)
	router.PUT("/agents/:agentID/execution", s.updateAgentExecution)
	router.PUT("/agents/:agentID/work-status", s.updateAgentWorkStatus)
	router.POST("/agents/:agentID/deactivate", s.deactivateAgent)
	router.POST("/agents/:agentID/reactivate", s.reactivateAgent)
	router.GET("/users", s.listUsers)
	router.GET("/users/:userID", s.getUser)
	router.POST("/users", s.createUser)
	router.PUT("/users/:userID", s.updateUser)
	router.PATCH("/users/roles", s.updateUserRoles)
	router.POST("/users/:userID/deactivate", s.deactivateUser)
	router.POST("/users/:userID/reactivate", s.reactivateUser)
	router.GET("/teams", s.listTeams)
	router.POST("/teams", s.createTeam)
	router.PUT("/teams/:teamID", s.updateTeam)
	router.DELETE("/teams/:teamID", s.deleteTeam)
	router.GET("/teams/:teamID/members", s.listTeamMembers)
	router.GET("/teams/:teamID/member-candidates", s.listTeamMemberCandidates)
	router.POST("/teams/:teamID/members", s.addTeamMembers)
	router.POST("/teams/:teamID/members/remove", s.removeTeamMembers)
	router.GET("/knowledge-bases", s.listKnowledgeBases)
	router.GET("/integration-connections/:connectionID/knowledge-bases", s.listExternalKnowledgeBaseOptions)
	router.GET("/knowledge-bases/:knowledgeBaseID", s.getKnowledgeBase)
	router.POST("/knowledge-bases", s.createKnowledgeBase)
	router.PUT("/knowledge-bases/:knowledgeBaseID", s.updateKnowledgeBase)
	router.DELETE("/knowledge-bases/:knowledgeBaseID", s.deleteKnowledgeBase)
	router.POST("/knowledge-bases/:knowledgeBaseID/groups", s.createKnowledgeGroup)
	router.PUT("/knowledge-bases/:knowledgeBaseID/groups/:groupID", s.updateKnowledgeGroup)
	router.DELETE("/knowledge-bases/:knowledgeBaseID/groups/:groupID", s.deleteKnowledgeGroup)
	router.GET("/contacts/:contactID", s.getContact)
	router.POST("/contacts", s.createContact)
	router.PUT("/contacts/:contactID", s.updateContact)
	router.DELETE("/contacts/:contactID", s.deleteContact)
	router.POST("/contacts/:contactID/restore", s.restoreContact)
	router.GET("/settings/roles", s.listRoles)
	router.GET("/settings/roles/:roleID", s.getRole)
	router.POST("/settings/roles", s.createRole)
	router.PUT("/settings/roles/:roleID", s.updateRole)
	router.DELETE("/settings/roles/:roleID", s.deleteRole)
	router.GET("/integrations/model-services", s.listAIProviders)
	router.GET("/integrations/model-services/:providerID", s.getAIProvider)
	router.GET("/integrations/model-services/models", s.listAvailableAIModels)
	router.POST("/integrations/model-services/test", s.testAIProviderConnection)
	router.POST("/integrations/model-services", s.createAIProvider)
	router.PUT("/integrations/model-services/:providerID", s.updateAIProvider)
	router.DELETE("/integrations/model-services/:providerID", s.deleteAIProvider)
	router.GET("/integrations/business-systems", s.listBusinessSystems)
	router.GET("/integrations/business-systems/:businessSystemID", s.getBusinessSystem)
	router.POST("/integrations/business-systems", s.createBusinessSystem)
	router.PUT("/integrations/business-systems/:businessSystemID", s.updateBusinessSystem)
	router.DELETE("/integrations/business-systems/:businessSystemID", s.deleteBusinessSystem)
	router.GET("/integrations/connectors", s.listIntegrationConnections)
	router.GET("/integrations/connectors/:connectionID", s.getIntegrationConnection)
	router.POST("/integrations/connectors/test", s.testIntegrationConnection)
	router.POST("/integrations/connectors", s.createIntegrationConnection)
	router.PUT("/integrations/connectors/:connectionID", s.updateIntegrationConnection)
	router.DELETE("/integrations/connectors/:connectionID", s.deleteIntegrationConnection)
	router.PUT("/settings/organization", s.updateOrganization)
	router.GET("/settings/storage/s3", s.getS3Setting)
	router.PUT("/settings/storage/s3", s.saveS3Setting)
	router.POST("/settings/storage/s3/test", s.testS3Setting)
}

// installationStatus 返回服务端初始化状态和公开企业名称。
func (s *Service) installationStatus(c *gin.Context) {
	output, err := s.application.InstallationStatus(c.Request.Context(), requestMeta(c))
	writeResult(c, http.StatusOK, output, err)
}

// login 校验账号密码并建立登录会话。
func (s *Service) login(c *gin.Context) {
	var input appservice.LoginInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.Login(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusOK, output, err)
}

// logout 退出当前登录会话。
func (s *Service) logout(c *gin.Context) {
	writeEmpty(c, s.application.Logout(c.Request.Context(), requestMeta(c)))
}

// loadIdentity 返回当前登录身份。
func (s *Service) loadIdentity(c *gin.Context) {
	output, err := s.application.LoadIdentity(c.Request.Context(), requestMeta(c))
	writeResult(c, http.StatusOK, output, err)
}

// updateProfile 修改当前用户的头像、姓名和邮箱。
func (s *Service) updateProfile(c *gin.Context) {
	var input appservice.ProfileInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.UpdateProfile(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusOK, output, err)
}

// createFileUpload 创建文件上传请求。
func (s *Service) createFileUpload(c *gin.Context) {
	var input appservice.FileUploadInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.CreateFileUpload(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusCreated, output, err)
}

// completeFileUpload 核验并完成文件上传。
func (s *Service) completeFileUpload(c *gin.Context) {
	output, err := s.application.CompleteFileUpload(c.Request.Context(), requestMeta(c), c.Param("fileID"))
	writeResult(c, http.StatusOK, output, err)
}

// changePassword 核验当前密码并保存新密码。
func (s *Service) changePassword(c *gin.Context) {
	var input appservice.ChangePasswordInput
	if !bindJSON(c, &input) {
		return
	}
	writeEmpty(c, s.application.ChangePassword(c.Request.Context(), requestMeta(c), input))
}

// updateUserPreferences 保存当前用户的偏好设置。
func (s *Service) updateUserPreferences(c *gin.Context) {
	var input appservice.UserPreferencesInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.UpdateUserPreferences(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusOK, output, err)
}

// updateUserWorkStatus 保存当前用户主动设置的工作状态。
func (s *Service) updateUserWorkStatus(c *gin.Context) {
	var input appservice.UserWorkStatusInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.UpdateUserWorkStatus(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusOK, output, err)
}

// loadInbox 返回当前用户的统一收件箱。
func (s *Service) loadInbox(c *gin.Context) {
	output, err := s.application.LoadInbox(c.Request.Context(), requestMeta(c))
	writeResult(c, http.StatusOK, output, err)
}

// listConversationMessages 返回成员可见的会话消息。
func (s *Service) listConversationMessages(c *gin.Context) {
	input, ok := bindConversationMessageListInputQuery(c)
	if !ok {
		return
	}
	output, err := s.application.ListConversationMessages(c.Request.Context(), requestMeta(c), c.Param("conversationID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// listMessageChannels 返回消息渠道列表。
func (s *Service) listMessageChannels(c *gin.Context) {
	output, err := s.application.ListMessageChannels(c.Request.Context(), requestMeta(c))
	writeResult(c, http.StatusOK, output, err)
}

// getWebsiteChannel 返回网站渠道详情。
func (s *Service) getWebsiteChannel(c *gin.Context) {
	output, err := s.application.GetWebsiteChannel(c.Request.Context(), requestMeta(c), c.Param("channelID"))
	writeResult(c, http.StatusOK, output, err)
}

// getMessageChannel 返回消息渠道基础信息。
func (s *Service) getMessageChannel(c *gin.Context) {
	output, err := s.application.GetMessageChannel(c.Request.Context(), requestMeta(c), c.Param("channelID"))
	writeResult(c, http.StatusOK, output, err)
}

// createMessageChannel 创建消息渠道。
func (s *Service) createMessageChannel(c *gin.Context) {
	var input appservice.CreateMessageChannelInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.CreateMessageChannel(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusCreated, output, err)
}

// updateMessageChannel 修改消息渠道基础信息。
func (s *Service) updateMessageChannel(c *gin.Context) {
	var input appservice.MessageChannelInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.UpdateMessageChannel(c.Request.Context(), requestMeta(c), c.Param("channelID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// updateWebsiteChannelChatInterface 修改网站渠道聊天界面。
func (s *Service) updateWebsiteChannelChatInterface(c *gin.Context) {
	var input appservice.WebsiteChannelChatInterfaceInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.UpdateWebsiteChannelChatInterface(c.Request.Context(), requestMeta(c), c.Param("channelID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// updateWebsiteChannelAccess 修改网站渠道允许使用的网站。
func (s *Service) updateWebsiteChannelAccess(c *gin.Context) {
	var input appservice.WebsiteChannelAccessInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.UpdateWebsiteChannelAccess(c.Request.Context(), requestMeta(c), c.Param("channelID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// deactivateMessageChannel 停用消息渠道。
func (s *Service) deactivateMessageChannel(c *gin.Context) {
	output, err := s.application.DeactivateMessageChannel(c.Request.Context(), requestMeta(c), c.Param("channelID"))
	writeResult(c, http.StatusOK, output, err)
}

// activateMessageChannel 启用消息渠道。
func (s *Service) activateMessageChannel(c *gin.Context) {
	output, err := s.application.ActivateMessageChannel(c.Request.Context(), requestMeta(c), c.Param("channelID"))
	writeResult(c, http.StatusOK, output, err)
}

// listChannelOptions 返回当前企业的渠道选择项。
func (s *Service) listChannelOptions(c *gin.Context) {
	output, err := s.application.ListChannelOptions(c.Request.Context(), requestMeta(c))
	writeResult(c, http.StatusOK, output, err)
}

// listMemberOptions 返回可分配的企业成员和 AI 员工。
func (s *Service) listMemberOptions(c *gin.Context) {
	input, ok := bindMemberOptionListInputQuery(c)
	if !ok {
		return
	}
	output, err := s.application.ListMemberOptions(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusOK, output, err)
}

// listAgentModelOptions 返回 AI 员工可使用的对话模型。
func (s *Service) listAgentModelOptions(c *gin.Context) {
	output, err := s.application.ListAgentModelOptions(c.Request.Context(), requestMeta(c))
	writeResult(c, http.StatusOK, output, err)
}

// createAgent 创建企业 AI 员工。
func (s *Service) createAgent(c *gin.Context) {
	var input appservice.CreateAgentInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.CreateAgent(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusCreated, output, err)
}

// listAgents 返回企业 AI 员工目录。
func (s *Service) listAgents(c *gin.Context) {
	input, ok := bindAgentListInputQuery(c)
	if !ok {
		return
	}
	output, err := s.application.ListAgents(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusOK, output, err)
}

// getAgent 返回企业 AI 员工详情。
func (s *Service) getAgent(c *gin.Context) {
	output, err := s.application.GetAgent(c.Request.Context(), requestMeta(c), c.Param("agentID"))
	writeResult(c, http.StatusOK, output, err)
}

// updateAgent 修改企业 AI 员工。
func (s *Service) updateAgent(c *gin.Context) {
	var input appservice.UpdateAgentInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.UpdateAgent(c.Request.Context(), requestMeta(c), c.Param("agentID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// updateAgentExecution 修改企业 AI 员工的执行配置。
func (s *Service) updateAgentExecution(c *gin.Context) {
	var input appservice.AgentExecutionInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.UpdateAgentExecution(c.Request.Context(), requestMeta(c), c.Param("agentID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// updateAgentWorkStatus 修改企业 AI 员工工作状态。
func (s *Service) updateAgentWorkStatus(c *gin.Context) {
	var input appservice.AgentWorkStatusInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.UpdateAgentWorkStatus(c.Request.Context(), requestMeta(c), c.Param("agentID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// deactivateAgent 禁用企业 AI 员工账号。
func (s *Service) deactivateAgent(c *gin.Context) {
	output, err := s.application.DeactivateAgent(c.Request.Context(), requestMeta(c), c.Param("agentID"))
	writeResult(c, http.StatusOK, output, err)
}

// reactivateAgent 恢复企业 AI 员工。
func (s *Service) reactivateAgent(c *gin.Context) {
	output, err := s.application.ReactivateAgent(c.Request.Context(), requestMeta(c), c.Param("agentID"))
	writeResult(c, http.StatusOK, output, err)
}

// listUsers 返回企业成员列表。
func (s *Service) listUsers(c *gin.Context) {
	input, ok := bindUserListInputQuery(c)
	if !ok {
		return
	}
	output, err := s.application.ListUsers(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusOK, output, err)
}

// getUser 返回企业成员详情。
func (s *Service) getUser(c *gin.Context) {
	output, err := s.application.GetUser(c.Request.Context(), requestMeta(c), c.Param("userID"))
	writeResult(c, http.StatusOK, output, err)
}

// createUser 创建企业成员账号。
func (s *Service) createUser(c *gin.Context) {
	var input appservice.CreateUserInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.CreateUser(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusCreated, output, err)
}

// updateUser 修改企业成员资料、角色和所属团队。
func (s *Service) updateUser(c *gin.Context) {
	var input appservice.UpdateUserInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.UpdateUser(c.Request.Context(), requestMeta(c), c.Param("userID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// updateUserRoles 在一个事务中批量调整企业成员角色。
func (s *Service) updateUserRoles(c *gin.Context) {
	var input appservice.UserRoleChangesInput
	if !bindJSON(c, &input) {
		return
	}
	writeEmpty(c, s.application.UpdateUserRoles(c.Request.Context(), requestMeta(c), input))
}

// deactivateUser 禁用企业成员账号。
func (s *Service) deactivateUser(c *gin.Context) {
	output, err := s.application.DeactivateUser(c.Request.Context(), requestMeta(c), c.Param("userID"))
	writeResult(c, http.StatusOK, output, err)
}

// reactivateUser 恢复企业成员账号。
func (s *Service) reactivateUser(c *gin.Context) {
	output, err := s.application.ReactivateUser(c.Request.Context(), requestMeta(c), c.Param("userID"))
	writeResult(c, http.StatusOK, output, err)
}

// listTeams 返回企业团队列表。
func (s *Service) listTeams(c *gin.Context) {
	input, ok := bindTeamListInputQuery(c)
	if !ok {
		return
	}
	output, err := s.application.ListTeams(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusOK, output, err)
}

// createTeam 创建企业团队。
func (s *Service) createTeam(c *gin.Context) {
	var input appservice.TeamInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.CreateTeam(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusCreated, output, err)
}

// updateTeam 修改企业团队。
func (s *Service) updateTeam(c *gin.Context) {
	var input appservice.TeamInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.UpdateTeam(c.Request.Context(), requestMeta(c), c.Param("teamID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// deleteTeam 删除企业团队及其成员关系。
func (s *Service) deleteTeam(c *gin.Context) {
	writeEmpty(c, s.application.DeleteTeam(c.Request.Context(), requestMeta(c), c.Param("teamID")))
}

// listTeamMembers 返回团队成员列表。
func (s *Service) listTeamMembers(c *gin.Context) {
	input, ok := bindTeamMemberListInputQuery(c)
	if !ok {
		return
	}
	output, err := s.application.ListTeamMembers(c.Request.Context(), requestMeta(c), c.Param("teamID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// listTeamMemberCandidates 返回尚未加入团队的企业身份。
func (s *Service) listTeamMemberCandidates(c *gin.Context) {
	input, ok := bindTeamMemberCandidateInputQuery(c)
	if !ok {
		return
	}
	output, err := s.application.ListTeamMemberCandidates(c.Request.Context(), requestMeta(c), c.Param("teamID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// addTeamMembers 将企业身份批量加入团队。
func (s *Service) addTeamMembers(c *gin.Context) {
	var input appservice.TeamMemberInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.AddTeamMembers(c.Request.Context(), requestMeta(c), c.Param("teamID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// removeTeamMembers 将企业身份批量移出团队。
func (s *Service) removeTeamMembers(c *gin.Context) {
	var input appservice.TeamMemberInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.RemoveTeamMembers(c.Request.Context(), requestMeta(c), c.Param("teamID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// listKnowledgeBases 返回当前企业的知识库列表。
func (s *Service) listKnowledgeBases(c *gin.Context) {
	output, err := s.application.ListKnowledgeBases(c.Request.Context(), requestMeta(c))
	writeResult(c, http.StatusOK, output, err)
}

// listExternalKnowledgeBaseOptions 返回指定连接可访问的外部知识库选项。
func (s *Service) listExternalKnowledgeBaseOptions(c *gin.Context) {
	output, err := s.application.ListExternalKnowledgeBaseOptions(c.Request.Context(), requestMeta(c), c.Param("connectionID"))
	writeResult(c, http.StatusOK, output, err)
}

// getKnowledgeBase 返回当前企业中的知识库详情。
func (s *Service) getKnowledgeBase(c *gin.Context) {
	output, err := s.application.GetKnowledgeBase(c.Request.Context(), requestMeta(c), c.Param("knowledgeBaseID"))
	writeResult(c, http.StatusOK, output, err)
}

// createKnowledgeBase 创建企业知识库。
func (s *Service) createKnowledgeBase(c *gin.Context) {
	var input appservice.KnowledgeBaseInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.CreateKnowledgeBase(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusCreated, output, err)
}

// updateKnowledgeBase 修改企业知识库。
func (s *Service) updateKnowledgeBase(c *gin.Context) {
	var input appservice.KnowledgeBaseInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.UpdateKnowledgeBase(c.Request.Context(), requestMeta(c), c.Param("knowledgeBaseID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// deleteKnowledgeBase 删除企业知识库。
func (s *Service) deleteKnowledgeBase(c *gin.Context) {
	writeEmpty(c, s.application.DeleteKnowledgeBase(c.Request.Context(), requestMeta(c), c.Param("knowledgeBaseID")))
}

// createKnowledgeGroup 创建知识库分组。
func (s *Service) createKnowledgeGroup(c *gin.Context) {
	var input appservice.KnowledgeGroupInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.CreateKnowledgeGroup(c.Request.Context(), requestMeta(c), c.Param("knowledgeBaseID"), input)
	writeResult(c, http.StatusCreated, output, err)
}

// updateKnowledgeGroup 修改知识库分组。
func (s *Service) updateKnowledgeGroup(c *gin.Context) {
	var input appservice.KnowledgeGroupInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.UpdateKnowledgeGroup(c.Request.Context(), requestMeta(c), c.Param("knowledgeBaseID"), c.Param("groupID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// deleteKnowledgeGroup 删除不含子分组的知识库分组。
func (s *Service) deleteKnowledgeGroup(c *gin.Context) {
	output, err := s.application.DeleteKnowledgeGroup(c.Request.Context(), requestMeta(c), c.Param("knowledgeBaseID"), c.Param("groupID"))
	writeResult(c, http.StatusOK, output, err)
}

// getContact 返回联系人详情。
func (s *Service) getContact(c *gin.Context) {
	output, err := s.application.GetContact(c.Request.Context(), requestMeta(c), c.Param("contactID"))
	writeResult(c, http.StatusOK, output, err)
}

// createContact 创建联系人。
func (s *Service) createContact(c *gin.Context) {
	var input appservice.ContactInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.CreateContact(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusCreated, output, err)
}

// updateContact 修改联系人。
func (s *Service) updateContact(c *gin.Context) {
	var input appservice.ContactInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.UpdateContact(c.Request.Context(), requestMeta(c), c.Param("contactID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// deleteContact 将联系人移入回收站。
func (s *Service) deleteContact(c *gin.Context) {
	writeEmpty(c, s.application.DeleteContact(c.Request.Context(), requestMeta(c), c.Param("contactID")))
}

// restoreContact 恢复联系人。
func (s *Service) restoreContact(c *gin.Context) {
	output, err := s.application.RestoreContact(c.Request.Context(), requestMeta(c), c.Param("contactID"))
	writeResult(c, http.StatusOK, output, err)
}

// listRoles 返回当前企业的角色和预定义权限目录。
func (s *Service) listRoles(c *gin.Context) {
	output, err := s.application.ListRoles(c.Request.Context(), requestMeta(c))
	writeResult(c, http.StatusOK, output, err)
}

// getRole 返回当前企业的角色详情。
func (s *Service) getRole(c *gin.Context) {
	output, err := s.application.GetRole(c.Request.Context(), requestMeta(c), c.Param("roleID"))
	writeResult(c, http.StatusOK, output, err)
}

// createRole 创建自定义角色。
func (s *Service) createRole(c *gin.Context) {
	var input appservice.RoleInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.CreateRole(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusCreated, output, err)
}

// updateRole 修改角色信息和权限。
func (s *Service) updateRole(c *gin.Context) {
	var input appservice.RoleInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.UpdateRole(c.Request.Context(), requestMeta(c), c.Param("roleID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// deleteRole 删除自定义角色。
func (s *Service) deleteRole(c *gin.Context) {
	writeEmpty(c, s.application.DeleteRole(c.Request.Context(), requestMeta(c), c.Param("roleID")))
}

// listAIProviders 返回当前企业的模型服务供应商列表。
func (s *Service) listAIProviders(c *gin.Context) {
	output, err := s.application.ListAIProviders(c.Request.Context(), requestMeta(c))
	writeResult(c, http.StatusOK, output, err)
}

// getAIProvider 返回当前企业中的模型服务供应商详情。
func (s *Service) getAIProvider(c *gin.Context) {
	output, err := s.application.GetAIProvider(c.Request.Context(), requestMeta(c), c.Param("providerID"))
	writeResult(c, http.StatusOK, output, err)
}

// listAvailableAIModels 返回指定品牌的预设模型目录。
func (s *Service) listAvailableAIModels(c *gin.Context) {
	output, err := s.application.ListAvailableAIModels(c.Request.Context(), requestMeta(c), appservice.AIProviderBrand(c.Query("brand")))
	writeResult(c, http.StatusOK, output, err)
}

// testAIProviderConnection 测试模型服务供应商草稿配置。
func (s *Service) testAIProviderConnection(c *gin.Context) {
	var input appservice.AIProviderConnectionInput
	if !bindJSON(c, &input) {
		return
	}
	writeEmpty(c, s.application.TestAIProviderConnection(c.Request.Context(), requestMeta(c), input))
}

// createAIProvider 创建模型服务供应商。
func (s *Service) createAIProvider(c *gin.Context) {
	var input appservice.AIProviderInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.CreateAIProvider(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusCreated, output, err)
}

// updateAIProvider 修改模型服务供应商。
func (s *Service) updateAIProvider(c *gin.Context) {
	var input appservice.AIProviderInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.UpdateAIProvider(c.Request.Context(), requestMeta(c), c.Param("providerID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// deleteAIProvider 删除模型服务供应商。
func (s *Service) deleteAIProvider(c *gin.Context) {
	writeEmpty(c, s.application.DeleteAIProvider(c.Request.Context(), requestMeta(c), c.Param("providerID")))
}

// listBusinessSystems 返回当前企业配置的业务系统。
func (s *Service) listBusinessSystems(c *gin.Context) {
	output, err := s.application.ListBusinessSystems(c.Request.Context(), requestMeta(c))
	writeResult(c, http.StatusOK, output, err)
}

// getBusinessSystem 返回当前企业中的业务系统详情。
func (s *Service) getBusinessSystem(c *gin.Context) {
	output, err := s.application.GetBusinessSystem(c.Request.Context(), requestMeta(c), c.Param("businessSystemID"))
	writeResult(c, http.StatusOK, output, err)
}

// createBusinessSystem 创建业务系统。
func (s *Service) createBusinessSystem(c *gin.Context) {
	var input appservice.BusinessSystemInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.CreateBusinessSystem(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusCreated, output, err)
}

// updateBusinessSystem 修改业务系统。
func (s *Service) updateBusinessSystem(c *gin.Context) {
	var input appservice.BusinessSystemInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.UpdateBusinessSystem(c.Request.Context(), requestMeta(c), c.Param("businessSystemID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// deleteBusinessSystem 删除业务系统。
func (s *Service) deleteBusinessSystem(c *gin.Context) {
	writeEmpty(c, s.application.DeleteBusinessSystem(c.Request.Context(), requestMeta(c), c.Param("businessSystemID")))
}

// listIntegrationConnections 返回当前企业的连接器列表。
func (s *Service) listIntegrationConnections(c *gin.Context) {
	output, err := s.application.ListIntegrationConnections(c.Request.Context(), requestMeta(c))
	writeResult(c, http.StatusOK, output, err)
}

// getIntegrationConnection 返回当前企业中的连接器详情。
func (s *Service) getIntegrationConnection(c *gin.Context) {
	output, err := s.application.GetIntegrationConnection(c.Request.Context(), requestMeta(c), c.Param("connectionID"))
	writeResult(c, http.StatusOK, output, err)
}

// testIntegrationConnection 测试连接器草稿配置。
func (s *Service) testIntegrationConnection(c *gin.Context) {
	var input appservice.IntegrationConnectionTestInput
	if !bindJSON(c, &input) {
		return
	}
	writeEmpty(c, s.application.TestIntegrationConnection(c.Request.Context(), requestMeta(c), input))
}

// createIntegrationConnection 创建外部系统连接器。
func (s *Service) createIntegrationConnection(c *gin.Context) {
	var input appservice.IntegrationConnectionInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.CreateIntegrationConnection(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusCreated, output, err)
}

// updateIntegrationConnection 修改外部系统连接器。
func (s *Service) updateIntegrationConnection(c *gin.Context) {
	var input appservice.IntegrationConnectionInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.UpdateIntegrationConnection(c.Request.Context(), requestMeta(c), c.Param("connectionID"), input)
	writeResult(c, http.StatusOK, output, err)
}

// deleteIntegrationConnection 删除外部系统连接器。
func (s *Service) deleteIntegrationConnection(c *gin.Context) {
	writeEmpty(c, s.application.DeleteIntegrationConnection(c.Request.Context(), requestMeta(c), c.Param("connectionID")))
}

// updateOrganization 修改当前企业通用设置。
func (s *Service) updateOrganization(c *gin.Context) {
	var input appservice.OrganizationInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.UpdateOrganization(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusOK, output, err)
}

// getS3Setting 返回当前企业的对象存储设置。
func (s *Service) getS3Setting(c *gin.Context) {
	output, err := s.application.GetS3Setting(c.Request.Context(), requestMeta(c))
	writeResult(c, http.StatusOK, output, err)
}

// saveS3Setting 保存当前企业的对象存储设置。
func (s *Service) saveS3Setting(c *gin.Context) {
	var input appservice.S3SettingInput
	if !bindJSON(c, &input) {
		return
	}
	output, err := s.application.SaveS3Setting(c.Request.Context(), requestMeta(c), input)
	writeResult(c, http.StatusOK, output, err)
}

// testS3Setting 测试对象存储连接。
func (s *Service) testS3Setting(c *gin.Context) {
	var input appservice.S3SettingInput
	if !bindJSON(c, &input) {
		return
	}
	writeEmpty(c, s.application.TestS3Setting(c.Request.Context(), requestMeta(c), input))
}

// bindAgentListInputQuery 从查询参数解析 appservice.AgentListInput。
func bindAgentListInputQuery(c *gin.Context) (appservice.AgentListInput, bool) {
	page, ok := positiveQueryInteger(c, "page", 1)
	if !ok {
		return appservice.AgentListInput{}, false
	}
	pageSize, ok := positiveQueryInteger(c, "pageSize", 50)
	if !ok {
		return appservice.AgentListInput{}, false
	}
	return appservice.AgentListInput{
		Query:    c.Query("query"),
		Status:   optionalEnum[appservice.UserStatus](c.Query("status")),
		Page:     page,
		PageSize: pageSize,
	}, true
}

// bindConversationMessageListInputQuery 从查询参数解析 appservice.ConversationMessageListInput。
func bindConversationMessageListInputQuery(c *gin.Context) (appservice.ConversationMessageListInput, bool) {
	return appservice.ConversationMessageListInput{
		Before: c.Query("before"),
		After:  c.Query("after"),
	}, true
}

// bindMemberOptionListInputQuery 从查询参数解析 appservice.MemberOptionListInput。
func bindMemberOptionListInputQuery(c *gin.Context) (appservice.MemberOptionListInput, bool) {
	page, ok := positiveQueryInteger(c, "page", 1)
	if !ok {
		return appservice.MemberOptionListInput{}, false
	}
	pageSize, ok := positiveQueryInteger(c, "pageSize", 50)
	if !ok {
		return appservice.MemberOptionListInput{}, false
	}
	return appservice.MemberOptionListInput{
		Query:    c.Query("query"),
		Page:     page,
		PageSize: pageSize,
	}, true
}

// bindTeamListInputQuery 从查询参数解析 appservice.TeamListInput。
func bindTeamListInputQuery(c *gin.Context) (appservice.TeamListInput, bool) {
	page, ok := positiveQueryInteger(c, "page", 1)
	if !ok {
		return appservice.TeamListInput{}, false
	}
	pageSize, ok := positiveQueryInteger(c, "pageSize", 50)
	if !ok {
		return appservice.TeamListInput{}, false
	}
	return appservice.TeamListInput{
		Query:    c.Query("query"),
		Page:     page,
		PageSize: pageSize,
	}, true
}

// bindTeamMemberCandidateInputQuery 从查询参数解析 appservice.TeamMemberCandidateInput。
func bindTeamMemberCandidateInputQuery(c *gin.Context) (appservice.TeamMemberCandidateInput, bool) {
	page, ok := positiveQueryInteger(c, "page", 1)
	if !ok {
		return appservice.TeamMemberCandidateInput{}, false
	}
	pageSize, ok := positiveQueryInteger(c, "pageSize", 50)
	if !ok {
		return appservice.TeamMemberCandidateInput{}, false
	}
	return appservice.TeamMemberCandidateInput{
		Query:    c.Query("query"),
		Page:     page,
		PageSize: pageSize,
	}, true
}

// bindTeamMemberListInputQuery 从查询参数解析 appservice.TeamMemberListInput。
func bindTeamMemberListInputQuery(c *gin.Context) (appservice.TeamMemberListInput, bool) {
	page, ok := positiveQueryInteger(c, "page", 1)
	if !ok {
		return appservice.TeamMemberListInput{}, false
	}
	pageSize, ok := positiveQueryInteger(c, "pageSize", 50)
	if !ok {
		return appservice.TeamMemberListInput{}, false
	}
	return appservice.TeamMemberListInput{
		Query:      c.Query("query"),
		WorkStatus: optionalEnum[appservice.WorkStatus](c.Query("workStatus")),
		Page:       page,
		PageSize:   pageSize,
	}, true
}

// bindUserListInputQuery 从查询参数解析 appservice.UserListInput。
func bindUserListInputQuery(c *gin.Context) (appservice.UserListInput, bool) {
	page, ok := positiveQueryInteger(c, "page", 1)
	if !ok {
		return appservice.UserListInput{}, false
	}
	pageSize, ok := positiveQueryInteger(c, "pageSize", 50)
	if !ok {
		return appservice.UserListInput{}, false
	}
	return appservice.UserListInput{
		Query:    c.Query("query"),
		Status:   optionalEnum[appservice.UserStatus](c.Query("status")),
		RoleID:   c.Query("roleId"),
		TeamID:   c.Query("teamId"),
		Page:     page,
		PageSize: pageSize,
	}, true
}
