// Code generated by appservicegen. DO NOT EDIT.

//go:build !server

package apiproxy

import (
	"context"
	"net/http"
	"net/url"

	"github.com/runforyou-ai/cervi/internal/appservice"
)

// LoadIdentity 返回当前登录身份。
func (b *Backend) LoadIdentity(ctx context.Context, meta appservice.RequestMeta) (appservice.Identity, error) {
	var output appservice.Identity
	err := b.do(ctx, meta, http.MethodGet, "/auth/identity", nil, nil, &output)
	b.normalizeOutput(&output)
	return output, err
}

// UpdateProfile 修改当前用户的头像、姓名和邮箱。
func (b *Backend) UpdateProfile(ctx context.Context, meta appservice.RequestMeta, input appservice.ProfileInput) (appservice.CurrentUser, error) {
	var output appservice.CurrentUser
	err := b.do(ctx, meta, http.MethodPatch, "/profile", nil, input, &output)
	b.normalizeOutput(&output)
	return output, err
}

// CreateFileUpload 创建文件上传请求。
func (b *Backend) CreateFileUpload(ctx context.Context, meta appservice.RequestMeta, input appservice.FileUploadInput) (appservice.FileUpload, error) {
	var output appservice.FileUpload
	err := b.do(ctx, meta, http.MethodPost, "/files/uploads", nil, input, &output)
	b.normalizeOutput(&output)
	return output, err
}

// CompleteFileUpload 核验并完成文件上传。
func (b *Backend) CompleteFileUpload(ctx context.Context, meta appservice.RequestMeta, fileID string) (appservice.File, error) {
	var output appservice.File
	err := b.do(ctx, meta, http.MethodPost, "/files/"+url.PathEscape(fileID)+"/complete", nil, nil, &output)
	b.normalizeOutput(&output)
	return output, err
}

// ChangePassword 核验当前密码并保存新密码。
func (b *Backend) ChangePassword(ctx context.Context, meta appservice.RequestMeta, input appservice.ChangePasswordInput) error {
	return b.do(ctx, meta, http.MethodPatch, "/password", nil, input, nil)
}

// UpdateUserPreferences 保存当前用户的偏好设置。
func (b *Backend) UpdateUserPreferences(ctx context.Context, meta appservice.RequestMeta, input appservice.UserPreferencesInput) (appservice.CurrentUser, error) {
	var output appservice.CurrentUser
	err := b.do(ctx, meta, http.MethodPatch, "/preferences", nil, input, &output)
	b.normalizeOutput(&output)
	return output, err
}

// UpdateUserWorkStatus 保存当前用户主动设置的工作状态。
func (b *Backend) UpdateUserWorkStatus(ctx context.Context, meta appservice.RequestMeta, input appservice.UserWorkStatusInput) (appservice.CurrentUser, error) {
	var output appservice.CurrentUser
	err := b.do(ctx, meta, http.MethodPatch, "/work-status", nil, input, &output)
	b.normalizeOutput(&output)
	return output, err
}

// LoadInbox 返回当前用户的统一收件箱。
func (b *Backend) LoadInbox(ctx context.Context, meta appservice.RequestMeta) (appservice.Inbox, error) {
	var output appservice.Inbox
	err := b.do(ctx, meta, http.MethodGet, "/inbox", nil, nil, &output)
	b.normalizeOutput(&output)
	return output, err
}

// ListConversationMessages 返回成员可见的会话消息。
func (b *Backend) ListConversationMessages(ctx context.Context, meta appservice.RequestMeta, conversationID string, input appservice.ConversationMessageListInput) (appservice.ConversationMessageList, error) {
	var output appservice.ConversationMessageList
	err := b.do(ctx, meta, http.MethodGet, "/conversations/"+url.PathEscape(conversationID)+"/messages", encodeConversationMessageListInputQuery(input), nil, &output)
	b.normalizeOutput(&output)
	return output, err
}

// ListMessageChannels 返回消息渠道列表。
func (b *Backend) ListMessageChannels(ctx context.Context, meta appservice.RequestMeta) (appservice.MessageChannelList, error) {
	var output appservice.MessageChannelList
	err := b.do(ctx, meta, http.MethodGet, "/channels", nil, nil, &output)
	b.normalizeOutput(&output)
	return output, err
}

// GetWebsiteChannel 返回网站渠道详情。
func (b *Backend) GetWebsiteChannel(ctx context.Context, meta appservice.RequestMeta, channelID string) (appservice.WebsiteChannel, error) {
	var output appservice.WebsiteChannel
	err := b.do(ctx, meta, http.MethodGet, "/channels/website/"+url.PathEscape(channelID), nil, nil, &output)
	b.normalizeOutput(&output)
	return output, err
}

// GetMessageChannel 返回消息渠道基础信息。
func (b *Backend) GetMessageChannel(ctx context.Context, meta appservice.RequestMeta, channelID string) (appservice.MessageChannelSummary, error) {
	var output appservice.MessageChannelSummary
	err := b.do(ctx, meta, http.MethodGet, "/channels/"+url.PathEscape(channelID), nil, nil, &output)
	b.normalizeOutput(&output)
	return output, err
}

// CreateMessageChannel 创建消息渠道。
func (b *Backend) CreateMessageChannel(ctx context.Context, meta appservice.RequestMeta, input appservice.CreateMessageChannelInput) (appservice.MessageChannelSummary, error) {
	var output appservice.MessageChannelSummary
	err := b.do(ctx, meta, http.MethodPost, "/channels", nil, input, &output)
	b.normalizeOutput(&output)
	return output, err
}

// UpdateMessageChannel 修改消息渠道基础信息。
func (b *Backend) UpdateMessageChannel(ctx context.Context, meta appservice.RequestMeta, channelID string, input appservice.MessageChannelInput) (appservice.MessageChannelSummary, error) {
	var output appservice.MessageChannelSummary
	err := b.do(ctx, meta, http.MethodPut, "/channels/"+url.PathEscape(channelID), nil, input, &output)
	b.normalizeOutput(&output)
	return output, err
}

// UpdateWebsiteChannelChatInterface 修改网站渠道聊天界面。
func (b *Backend) UpdateWebsiteChannelChatInterface(ctx context.Context, meta appservice.RequestMeta, channelID string, input appservice.WebsiteChannelChatInterfaceInput) (appservice.WebsiteChannelChatInterface, error) {
	var output appservice.WebsiteChannelChatInterface
	err := b.do(ctx, meta, http.MethodPut, "/channels/website/"+url.PathEscape(channelID)+"/chat-interface", nil, input, &output)
	b.normalizeOutput(&output)
	return output, err
}

// UpdateWebsiteChannelAccess 修改网站渠道允许使用的网站。
func (b *Backend) UpdateWebsiteChannelAccess(ctx context.Context, meta appservice.RequestMeta, channelID string, input appservice.WebsiteChannelAccessInput) (appservice.WebsiteChannelAccess, error) {
	var output appservice.WebsiteChannelAccess
	err := b.do(ctx, meta, http.MethodPut, "/channels/website/"+url.PathEscape(channelID)+"/access", nil, input, &output)
	b.normalizeOutput(&output)
	return output, err
}

// DeactivateMessageChannel 停用消息渠道。
func (b *Backend) DeactivateMessageChannel(ctx context.Context, meta appservice.RequestMeta, channelID string) (appservice.MessageChannelSummary, error) {
	var output appservice.MessageChannelSummary
	err := b.do(ctx, meta, http.MethodPost, "/channels/"+url.PathEscape(channelID)+"/deactivate", nil, nil, &output)
	b.normalizeOutput(&output)
	return output, err
}

// ActivateMessageChannel 启用消息渠道。
func (b *Backend) ActivateMessageChannel(ctx context.Context, meta appservice.RequestMeta, channelID string) (appservice.MessageChannelSummary, error) {
	var output appservice.MessageChannelSummary
	err := b.do(ctx, meta, http.MethodPost, "/channels/"+url.PathEscape(channelID)+"/activate", nil, nil, &output)
	b.normalizeOutput(&output)
	return output, err
}

// ListChannelOptions 返回当前企业的渠道选择项。
func (b *Backend) ListChannelOptions(ctx context.Context, meta appservice.RequestMeta) (appservice.ChannelOptionList, error) {
	var output appservice.ChannelOptionList
	err := b.do(ctx, meta, http.MethodGet, "/channels/options", nil, nil, &output)
	b.normalizeOutput(&output)
	return output, err
}

// ListMemberOptions 返回可分配的企业成员和 AI 员工。
func (b *Backend) ListMemberOptions(ctx context.Context, meta appservice.RequestMeta, input appservice.MemberOptionListInput) (appservice.MemberOptionList, error) {
	var output appservice.MemberOptionList
	err := b.do(ctx, meta, http.MethodGet, "/members/options", encodeMemberOptionListInputQuery(input), nil, &output)
	b.normalizeOutput(&output)
	return output, err
}

// ListAgentModelOptions 返回 AI 员工可使用的对话模型。
func (b *Backend) ListAgentModelOptions(ctx context.Context, meta appservice.RequestMeta) (appservice.AgentModelOptionList, error) {
	var output appservice.AgentModelOptionList
	err := b.do(ctx, meta, http.MethodGet, "/agents/model-options", nil, nil, &output)
	b.normalizeOutput(&output)
	return output, err
}

// CreateAgent 创建企业 AI 员工。
func (b *Backend) CreateAgent(ctx context.Context, meta appservice.RequestMeta, input appservice.CreateAgentInput) (appservice.Agent, error) {
	var output appservice.Agent
	err := b.do(ctx, meta, http.MethodPost, "/agents", nil, input, &output)
	b.normalizeOutput(&output)
	return output, err
}

// ListAgents 返回企业 AI 员工目录。
func (b *Backend) ListAgents(ctx context.Context, meta appservice.RequestMeta, input appservice.AgentListInput) (appservice.AgentList, error) {
	var output appservice.AgentList
	err := b.do(ctx, meta, http.MethodGet, "/agents", encodeAgentListInputQuery(input), nil, &output)
	b.normalizeOutput(&output)
	return output, err
}

// GetAgent 返回企业 AI 员工详情。
func (b *Backend) GetAgent(ctx context.Context, meta appservice.RequestMeta, agentID string) (appservice.Agent, error) {
	var output appservice.Agent
	err := b.do(ctx, meta, http.MethodGet, "/agents/"+url.PathEscape(agentID), nil, nil, &output)
	b.normalizeOutput(&output)
	return output, err
}

// UpdateAgent 修改企业 AI 员工。
func (b *Backend) UpdateAgent(ctx context.Context, meta appservice.RequestMeta, agentID string, input appservice.UpdateAgentInput) (appservice.Agent, error) {
	var output appservice.Agent
	err := b.do(ctx, meta, http.MethodPut, "/agents/"+url.PathEscape(agentID), nil, input, &output)
	b.normalizeOutput(&output)
	return output, err
}

// UpdateAgentExecution 修改企业 AI 员工的执行配置。
func (b *Backend) UpdateAgentExecution(ctx context.Context, meta appservice.RequestMeta, agentID string, input appservice.AgentExecutionInput) (appservice.Agent, error) {
	var output appservice.Agent
	err := b.do(ctx, meta, http.MethodPut, "/agents/"+url.PathEscape(agentID)+"/execution", nil, input, &output)
	b.normalizeOutput(&output)
	return output, err
}

// UpdateAgentWorkStatus 修改企业 AI 员工工作状态。
func (b *Backend) UpdateAgentWorkStatus(ctx context.Context, meta appservice.RequestMeta, agentID string, input appservice.AgentWorkStatusInput) (appservice.Agent, error) {
	var output appservice.Agent
	err := b.do(ctx, meta, http.MethodPut, "/agents/"+url.PathEscape(agentID)+"/work-status", nil, input, &output)
	b.normalizeOutput(&output)
	return output, err
}

// DeactivateAgent 禁用企业 AI 员工账号。
func (b *Backend) DeactivateAgent(ctx context.Context, meta appservice.RequestMeta, agentID string) (appservice.Agent, error) {
	var output appservice.Agent
	err := b.do(ctx, meta, http.MethodPost, "/agents/"+url.PathEscape(agentID)+"/deactivate", nil, nil, &output)
	b.normalizeOutput(&output)
	return output, err
}

// ReactivateAgent 恢复企业 AI 员工。
func (b *Backend) ReactivateAgent(ctx context.Context, meta appservice.RequestMeta, agentID string) (appservice.Agent, error) {
	var output appservice.Agent
	err := b.do(ctx, meta, http.MethodPost, "/agents/"+url.PathEscape(agentID)+"/reactivate", nil, nil, &output)
	b.normalizeOutput(&output)
	return output, err
}

// ListUsers 返回企业成员列表。
func (b *Backend) ListUsers(ctx context.Context, meta appservice.RequestMeta, input appservice.UserListInput) (appservice.UserList, error) {
	var output appservice.UserList
	err := b.do(ctx, meta, http.MethodGet, "/users", encodeUserListInputQuery(input), nil, &output)
	b.normalizeOutput(&output)
	return output, err
}

// GetUser 返回企业成员详情。
func (b *Backend) GetUser(ctx context.Context, meta appservice.RequestMeta, userID string) (appservice.User, error) {
	var output appservice.User
	err := b.do(ctx, meta, http.MethodGet, "/users/"+url.PathEscape(userID), nil, nil, &output)
	b.normalizeOutput(&output)
	return output, err
}

// CreateUser 创建企业成员账号。
func (b *Backend) CreateUser(ctx context.Context, meta appservice.RequestMeta, input appservice.CreateUserInput) (appservice.User, error) {
	var output appservice.User
	err := b.do(ctx, meta, http.MethodPost, "/users", nil, input, &output)
	b.normalizeOutput(&output)
	return output, err
}

// UpdateUser 修改企业成员资料、角色和所属团队。
func (b *Backend) UpdateUser(ctx context.Context, meta appservice.RequestMeta, userID string, input appservice.UpdateUserInput) (appservice.User, error) {
	var output appservice.User
	err := b.do(ctx, meta, http.MethodPut, "/users/"+url.PathEscape(userID), nil, input, &output)
	b.normalizeOutput(&output)
	return output, err
}

// UpdateUserRoles 在一个事务中批量调整企业成员角色。
func (b *Backend) UpdateUserRoles(ctx context.Context, meta appservice.RequestMeta, input appservice.UserRoleChangesInput) error {
	return b.do(ctx, meta, http.MethodPatch, "/users/roles", nil, input, nil)
}

// DeactivateUser 禁用企业成员账号。
func (b *Backend) DeactivateUser(ctx context.Context, meta appservice.RequestMeta, userID string) (appservice.User, error) {
	var output appservice.User
	err := b.do(ctx, meta, http.MethodPost, "/users/"+url.PathEscape(userID)+"/deactivate", nil, nil, &output)
	b.normalizeOutput(&output)
	return output, err
}

// ReactivateUser 恢复企业成员账号。
func (b *Backend) ReactivateUser(ctx context.Context, meta appservice.RequestMeta, userID string) (appservice.User, error) {
	var output appservice.User
	err := b.do(ctx, meta, http.MethodPost, "/users/"+url.PathEscape(userID)+"/reactivate", nil, nil, &output)
	b.normalizeOutput(&output)
	return output, err
}

// ListTeams 返回企业团队列表。
func (b *Backend) ListTeams(ctx context.Context, meta appservice.RequestMeta, input appservice.TeamListInput) (appservice.TeamList, error) {
	var output appservice.TeamList
	err := b.do(ctx, meta, http.MethodGet, "/teams", encodeTeamListInputQuery(input), nil, &output)
	b.normalizeOutput(&output)
	return output, err
}

// CreateTeam 创建企业团队。
func (b *Backend) CreateTeam(ctx context.Context, meta appservice.RequestMeta, input appservice.TeamInput) (appservice.Team, error) {
	var output appservice.Team
	err := b.do(ctx, meta, http.MethodPost, "/teams", nil, input, &output)
	b.normalizeOutput(&output)
	return output, err
}

// UpdateTeam 修改企业团队。
func (b *Backend) UpdateTeam(ctx context.Context, meta appservice.RequestMeta, teamID string, input appservice.TeamInput) (appservice.Team, error) {
	var output appservice.Team
	err := b.do(ctx, meta, http.MethodPut, "/teams/"+url.PathEscape(teamID), nil, input, &output)
	b.normalizeOutput(&output)
	return output, err
}

// DeleteTeam 删除企业团队及其成员关系。
func (b *Backend) DeleteTeam(ctx context.Context, meta appservice.RequestMeta, teamID string) error {
	return b.do(ctx, meta, http.MethodDelete, "/teams/"+url.PathEscape(teamID), nil, nil, nil)
}

// ListTeamMembers 返回团队成员列表。
func (b *Backend) ListTeamMembers(ctx context.Context, meta appservice.RequestMeta, teamID string, input appservice.TeamMemberListInput) (appservice.TeamMemberList, error) {
	var output appservice.TeamMemberList
	err := b.do(ctx, meta, http.MethodGet, "/teams/"+url.PathEscape(teamID)+"/members", encodeTeamMemberListInputQuery(input), nil, &output)
	b.normalizeOutput(&output)
	return output, err
}

// ListTeamMemberCandidates 返回尚未加入团队的企业身份。
func (b *Backend) ListTeamMemberCandidates(ctx context.Context, meta appservice.RequestMeta, teamID string, input appservice.TeamMemberCandidateInput) (appservice.TeamMemberCandidateList, error) {
	var output appservice.TeamMemberCandidateList
	err := b.do(ctx, meta, http.MethodGet, "/teams/"+url.PathEscape(teamID)+"/member-candidates", encodeTeamMemberCandidateInputQuery(input), nil, &output)
	b.normalizeOutput(&output)
	return output, err
}

// AddTeamMembers 将企业身份批量加入团队。
func (b *Backend) AddTeamMembers(ctx context.Context, meta appservice.RequestMeta, teamID string, input appservice.TeamMemberInput) (appservice.Team, error) {
	var output appservice.Team
	err := b.do(ctx, meta, http.MethodPost, "/teams/"+url.PathEscape(teamID)+"/members", nil, input, &output)
	b.normalizeOutput(&output)
	return output, err
}

// RemoveTeamMembers 将企业身份批量移出团队。
func (b *Backend) RemoveTeamMembers(ctx context.Context, meta appservice.RequestMeta, teamID string, input appservice.TeamMemberInput) (appservice.Team, error) {
	var output appservice.Team
	err := b.do(ctx, meta, http.MethodPost, "/teams/"+url.PathEscape(teamID)+"/members/remove", nil, input, &output)
	b.normalizeOutput(&output)
	return output, err
}

// ListKnowledgeBases 返回当前企业的知识库列表。
func (b *Backend) ListKnowledgeBases(ctx context.Context, meta appservice.RequestMeta) (appservice.KnowledgeBaseList, error) {
	var output appservice.KnowledgeBaseList
	err := b.do(ctx, meta, http.MethodGet, "/knowledge-bases", nil, nil, &output)
	b.normalizeOutput(&output)
	return output, err
}

// ListExternalKnowledgeBaseOptions 返回指定连接可访问的外部知识库选项。
func (b *Backend) ListExternalKnowledgeBaseOptions(ctx context.Context, meta appservice.RequestMeta, connectionID string) (appservice.ExternalKnowledgeBaseOptionList, error) {
	var output appservice.ExternalKnowledgeBaseOptionList
	err := b.do(ctx, meta, http.MethodGet, "/integration-connections/"+url.PathEscape(connectionID)+"/knowledge-bases", nil, nil, &output)
	b.normalizeOutput(&output)
	return output, err
}

// GetKnowledgeBase 返回当前企业中的知识库详情。
func (b *Backend) GetKnowledgeBase(ctx context.Context, meta appservice.RequestMeta, knowledgeBaseID string) (appservice.KnowledgeBase, error) {
	var output appservice.KnowledgeBase
	err := b.do(ctx, meta, http.MethodGet, "/knowledge-bases/"+url.PathEscape(knowledgeBaseID), nil, nil, &output)
	b.normalizeOutput(&output)
	return output, err
}

// CreateKnowledgeBase 创建企业知识库。
func (b *Backend) CreateKnowledgeBase(ctx context.Context, meta appservice.RequestMeta, input appservice.KnowledgeBaseInput) (appservice.KnowledgeBase, error) {
	var output appservice.KnowledgeBase
	err := b.do(ctx, meta, http.MethodPost, "/knowledge-bases", nil, input, &output)
	b.normalizeOutput(&output)
	return output, err
}

// UpdateKnowledgeBase 修改企业知识库。
func (b *Backend) UpdateKnowledgeBase(ctx context.Context, meta appservice.RequestMeta, knowledgeBaseID string, input appservice.KnowledgeBaseInput) (appservice.KnowledgeBase, error) {
	var output appservice.KnowledgeBase
	err := b.do(ctx, meta, http.MethodPut, "/knowledge-bases/"+url.PathEscape(knowledgeBaseID), nil, input, &output)
	b.normalizeOutput(&output)
	return output, err
}

// DeleteKnowledgeBase 删除企业知识库。
func (b *Backend) DeleteKnowledgeBase(ctx context.Context, meta appservice.RequestMeta, knowledgeBaseID string) error {
	return b.do(ctx, meta, http.MethodDelete, "/knowledge-bases/"+url.PathEscape(knowledgeBaseID), nil, nil, nil)
}

// CreateKnowledgeGroup 创建知识库分组。
func (b *Backend) CreateKnowledgeGroup(ctx context.Context, meta appservice.RequestMeta, knowledgeBaseID string, input appservice.KnowledgeGroupInput) (appservice.KnowledgeBase, error) {
	var output appservice.KnowledgeBase
	err := b.do(ctx, meta, http.MethodPost, "/knowledge-bases/"+url.PathEscape(knowledgeBaseID)+"/groups", nil, input, &output)
	b.normalizeOutput(&output)
	return output, err
}

// UpdateKnowledgeGroup 修改知识库分组。
func (b *Backend) UpdateKnowledgeGroup(ctx context.Context, meta appservice.RequestMeta, knowledgeBaseID string, groupID string, input appservice.KnowledgeGroupInput) (appservice.KnowledgeBase, error) {
	var output appservice.KnowledgeBase
	err := b.do(ctx, meta, http.MethodPut, "/knowledge-bases/"+url.PathEscape(knowledgeBaseID)+"/groups/"+url.PathEscape(groupID), nil, input, &output)
	b.normalizeOutput(&output)
	return output, err
}

// DeleteKnowledgeGroup 删除不含子分组的知识库分组。
func (b *Backend) DeleteKnowledgeGroup(ctx context.Context, meta appservice.RequestMeta, knowledgeBaseID string, groupID string) (appservice.KnowledgeBase, error) {
	var output appservice.KnowledgeBase
	err := b.do(ctx, meta, http.MethodDelete, "/knowledge-bases/"+url.PathEscape(knowledgeBaseID)+"/groups/"+url.PathEscape(groupID), nil, nil, &output)
	b.normalizeOutput(&output)
	return output, err
}

// GetContact 返回联系人详情。
func (b *Backend) GetContact(ctx context.Context, meta appservice.RequestMeta, contactID string) (appservice.Contact, error) {
	var output appservice.Contact
	err := b.do(ctx, meta, http.MethodGet, "/contacts/"+url.PathEscape(contactID), nil, nil, &output)
	b.normalizeOutput(&output)
	return output, err
}

// CreateContact 创建联系人。
func (b *Backend) CreateContact(ctx context.Context, meta appservice.RequestMeta, input appservice.ContactInput) (appservice.Contact, error) {
	var output appservice.Contact
	err := b.do(ctx, meta, http.MethodPost, "/contacts", nil, input, &output)
	b.normalizeOutput(&output)
	return output, err
}

// UpdateContact 修改联系人。
func (b *Backend) UpdateContact(ctx context.Context, meta appservice.RequestMeta, contactID string, input appservice.ContactInput) (appservice.Contact, error) {
	var output appservice.Contact
	err := b.do(ctx, meta, http.MethodPut, "/contacts/"+url.PathEscape(contactID), nil, input, &output)
	b.normalizeOutput(&output)
	return output, err
}

// DeleteContact 将联系人移入回收站。
func (b *Backend) DeleteContact(ctx context.Context, meta appservice.RequestMeta, contactID string) error {
	return b.do(ctx, meta, http.MethodDelete, "/contacts/"+url.PathEscape(contactID), nil, nil, nil)
}

// RestoreContact 恢复联系人。
func (b *Backend) RestoreContact(ctx context.Context, meta appservice.RequestMeta, contactID string) (appservice.Contact, error) {
	var output appservice.Contact
	err := b.do(ctx, meta, http.MethodPost, "/contacts/"+url.PathEscape(contactID)+"/restore", nil, nil, &output)
	b.normalizeOutput(&output)
	return output, err
}

// ListRoles 返回当前企业的角色和预定义权限目录。
func (b *Backend) ListRoles(ctx context.Context, meta appservice.RequestMeta) (appservice.RoleList, error) {
	var output appservice.RoleList
	err := b.do(ctx, meta, http.MethodGet, "/settings/roles", nil, nil, &output)
	b.normalizeOutput(&output)
	return output, err
}

// GetRole 返回当前企业的角色详情。
func (b *Backend) GetRole(ctx context.Context, meta appservice.RequestMeta, roleID string) (appservice.Role, error) {
	var output appservice.Role
	err := b.do(ctx, meta, http.MethodGet, "/settings/roles/"+url.PathEscape(roleID), nil, nil, &output)
	b.normalizeOutput(&output)
	return output, err
}

// CreateRole 创建自定义角色。
func (b *Backend) CreateRole(ctx context.Context, meta appservice.RequestMeta, input appservice.RoleInput) (appservice.Role, error) {
	var output appservice.Role
	err := b.do(ctx, meta, http.MethodPost, "/settings/roles", nil, input, &output)
	b.normalizeOutput(&output)
	return output, err
}

// UpdateRole 修改角色信息和权限。
func (b *Backend) UpdateRole(ctx context.Context, meta appservice.RequestMeta, roleID string, input appservice.RoleInput) (appservice.Role, error) {
	var output appservice.Role
	err := b.do(ctx, meta, http.MethodPut, "/settings/roles/"+url.PathEscape(roleID), nil, input, &output)
	b.normalizeOutput(&output)
	return output, err
}

// DeleteRole 删除自定义角色。
func (b *Backend) DeleteRole(ctx context.Context, meta appservice.RequestMeta, roleID string) error {
	return b.do(ctx, meta, http.MethodDelete, "/settings/roles/"+url.PathEscape(roleID), nil, nil, nil)
}

// ListAIProviders 返回当前企业的模型服务供应商列表。
func (b *Backend) ListAIProviders(ctx context.Context, meta appservice.RequestMeta) (appservice.AIProviderList, error) {
	var output appservice.AIProviderList
	err := b.do(ctx, meta, http.MethodGet, "/integrations/model-services", nil, nil, &output)
	b.normalizeOutput(&output)
	return output, err
}

// GetAIProvider 返回当前企业中的模型服务供应商详情。
func (b *Backend) GetAIProvider(ctx context.Context, meta appservice.RequestMeta, providerID string) (appservice.AIProvider, error) {
	var output appservice.AIProvider
	err := b.do(ctx, meta, http.MethodGet, "/integrations/model-services/"+url.PathEscape(providerID), nil, nil, &output)
	b.normalizeOutput(&output)
	return output, err
}

// ListAvailableAIModels 返回指定品牌的预设模型目录。
func (b *Backend) ListAvailableAIModels(ctx context.Context, meta appservice.RequestMeta, brand appservice.AIProviderBrand) (appservice.AIProviderModelList, error) {
	query := url.Values{}
	query.Set("brand", string(brand))
	var output appservice.AIProviderModelList
	err := b.do(ctx, meta, http.MethodGet, "/integrations/model-services/models", query, nil, &output)
	b.normalizeOutput(&output)
	return output, err
}

// TestAIProviderConnection 测试模型服务供应商草稿配置。
func (b *Backend) TestAIProviderConnection(ctx context.Context, meta appservice.RequestMeta, input appservice.AIProviderConnectionInput) error {
	return b.do(ctx, meta, http.MethodPost, "/integrations/model-services/test", nil, input, nil)
}

// CreateAIProvider 创建模型服务供应商。
func (b *Backend) CreateAIProvider(ctx context.Context, meta appservice.RequestMeta, input appservice.AIProviderInput) (appservice.AIProvider, error) {
	var output appservice.AIProvider
	err := b.do(ctx, meta, http.MethodPost, "/integrations/model-services", nil, input, &output)
	b.normalizeOutput(&output)
	return output, err
}

// UpdateAIProvider 修改模型服务供应商。
func (b *Backend) UpdateAIProvider(ctx context.Context, meta appservice.RequestMeta, providerID string, input appservice.AIProviderInput) (appservice.AIProvider, error) {
	var output appservice.AIProvider
	err := b.do(ctx, meta, http.MethodPut, "/integrations/model-services/"+url.PathEscape(providerID), nil, input, &output)
	b.normalizeOutput(&output)
	return output, err
}

// DeleteAIProvider 删除模型服务供应商。
func (b *Backend) DeleteAIProvider(ctx context.Context, meta appservice.RequestMeta, providerID string) error {
	return b.do(ctx, meta, http.MethodDelete, "/integrations/model-services/"+url.PathEscape(providerID), nil, nil, nil)
}

// ListBusinessSystems 返回当前企业配置的业务系统。
func (b *Backend) ListBusinessSystems(ctx context.Context, meta appservice.RequestMeta) (appservice.BusinessSystemList, error) {
	var output appservice.BusinessSystemList
	err := b.do(ctx, meta, http.MethodGet, "/integrations/business-systems", nil, nil, &output)
	b.normalizeOutput(&output)
	return output, err
}

// GetBusinessSystem 返回当前企业中的业务系统详情。
func (b *Backend) GetBusinessSystem(ctx context.Context, meta appservice.RequestMeta, businessSystemID string) (appservice.BusinessSystem, error) {
	var output appservice.BusinessSystem
	err := b.do(ctx, meta, http.MethodGet, "/integrations/business-systems/"+url.PathEscape(businessSystemID), nil, nil, &output)
	b.normalizeOutput(&output)
	return output, err
}

// CreateBusinessSystem 创建业务系统。
func (b *Backend) CreateBusinessSystem(ctx context.Context, meta appservice.RequestMeta, input appservice.BusinessSystemInput) (appservice.BusinessSystem, error) {
	var output appservice.BusinessSystem
	err := b.do(ctx, meta, http.MethodPost, "/integrations/business-systems", nil, input, &output)
	b.normalizeOutput(&output)
	return output, err
}

// UpdateBusinessSystem 修改业务系统。
func (b *Backend) UpdateBusinessSystem(ctx context.Context, meta appservice.RequestMeta, businessSystemID string, input appservice.BusinessSystemInput) (appservice.BusinessSystem, error) {
	var output appservice.BusinessSystem
	err := b.do(ctx, meta, http.MethodPut, "/integrations/business-systems/"+url.PathEscape(businessSystemID), nil, input, &output)
	b.normalizeOutput(&output)
	return output, err
}

// DeleteBusinessSystem 删除业务系统。
func (b *Backend) DeleteBusinessSystem(ctx context.Context, meta appservice.RequestMeta, businessSystemID string) error {
	return b.do(ctx, meta, http.MethodDelete, "/integrations/business-systems/"+url.PathEscape(businessSystemID), nil, nil, nil)
}

// ListIntegrationConnections 返回当前企业的连接器列表。
func (b *Backend) ListIntegrationConnections(ctx context.Context, meta appservice.RequestMeta) (appservice.IntegrationConnectionList, error) {
	var output appservice.IntegrationConnectionList
	err := b.do(ctx, meta, http.MethodGet, "/integrations/connectors", nil, nil, &output)
	b.normalizeOutput(&output)
	return output, err
}

// GetIntegrationConnection 返回当前企业中的连接器详情。
func (b *Backend) GetIntegrationConnection(ctx context.Context, meta appservice.RequestMeta, connectionID string) (appservice.IntegrationConnection, error) {
	var output appservice.IntegrationConnection
	err := b.do(ctx, meta, http.MethodGet, "/integrations/connectors/"+url.PathEscape(connectionID), nil, nil, &output)
	b.normalizeOutput(&output)
	return output, err
}

// TestIntegrationConnection 测试连接器草稿配置。
func (b *Backend) TestIntegrationConnection(ctx context.Context, meta appservice.RequestMeta, input appservice.IntegrationConnectionTestInput) error {
	return b.do(ctx, meta, http.MethodPost, "/integrations/connectors/test", nil, input, nil)
}

// CreateIntegrationConnection 创建外部系统连接器。
func (b *Backend) CreateIntegrationConnection(ctx context.Context, meta appservice.RequestMeta, input appservice.IntegrationConnectionInput) (appservice.IntegrationConnection, error) {
	var output appservice.IntegrationConnection
	err := b.do(ctx, meta, http.MethodPost, "/integrations/connectors", nil, input, &output)
	b.normalizeOutput(&output)
	return output, err
}

// UpdateIntegrationConnection 修改外部系统连接器。
func (b *Backend) UpdateIntegrationConnection(ctx context.Context, meta appservice.RequestMeta, connectionID string, input appservice.IntegrationConnectionInput) (appservice.IntegrationConnection, error) {
	var output appservice.IntegrationConnection
	err := b.do(ctx, meta, http.MethodPut, "/integrations/connectors/"+url.PathEscape(connectionID), nil, input, &output)
	b.normalizeOutput(&output)
	return output, err
}

// DeleteIntegrationConnection 删除外部系统连接器。
func (b *Backend) DeleteIntegrationConnection(ctx context.Context, meta appservice.RequestMeta, connectionID string) error {
	return b.do(ctx, meta, http.MethodDelete, "/integrations/connectors/"+url.PathEscape(connectionID), nil, nil, nil)
}

// UpdateOrganization 修改当前企业通用设置。
func (b *Backend) UpdateOrganization(ctx context.Context, meta appservice.RequestMeta, input appservice.OrganizationInput) (appservice.Organization, error) {
	var output appservice.Organization
	err := b.do(ctx, meta, http.MethodPut, "/settings/organization", nil, input, &output)
	b.normalizeOutput(&output)
	return output, err
}

// GetS3Setting 返回当前企业的对象存储设置。
func (b *Backend) GetS3Setting(ctx context.Context, meta appservice.RequestMeta) (appservice.S3Setting, error) {
	var output appservice.S3Setting
	err := b.do(ctx, meta, http.MethodGet, "/settings/storage/s3", nil, nil, &output)
	b.normalizeOutput(&output)
	return output, err
}

// SaveS3Setting 保存当前企业的对象存储设置。
func (b *Backend) SaveS3Setting(ctx context.Context, meta appservice.RequestMeta, input appservice.S3SettingInput) (appservice.S3Setting, error) {
	var output appservice.S3Setting
	err := b.do(ctx, meta, http.MethodPut, "/settings/storage/s3", nil, input, &output)
	b.normalizeOutput(&output)
	return output, err
}

// TestS3Setting 测试对象存储连接。
func (b *Backend) TestS3Setting(ctx context.Context, meta appservice.RequestMeta, input appservice.S3SettingInput) error {
	return b.do(ctx, meta, http.MethodPost, "/settings/storage/s3/test", nil, input, nil)
}

// encodeAgentListInputQuery 将 appservice.AgentListInput 编码为查询参数。
func encodeAgentListInputQuery(input appservice.AgentListInput) url.Values {
	query := url.Values{}
	setQuery(query, "query", input.Query)
	setOptionalQuery(query, "status", input.Status)
	setPositiveQuery(query, "page", input.Page)
	setPositiveQuery(query, "pageSize", input.PageSize)
	return query
}

// encodeConversationMessageListInputQuery 将 appservice.ConversationMessageListInput 编码为查询参数。
func encodeConversationMessageListInputQuery(input appservice.ConversationMessageListInput) url.Values {
	query := url.Values{}
	setQuery(query, "before", input.Before)
	setQuery(query, "after", input.After)
	return query
}

// encodeMemberOptionListInputQuery 将 appservice.MemberOptionListInput 编码为查询参数。
func encodeMemberOptionListInputQuery(input appservice.MemberOptionListInput) url.Values {
	query := url.Values{}
	setQuery(query, "query", input.Query)
	setPositiveQuery(query, "page", input.Page)
	setPositiveQuery(query, "pageSize", input.PageSize)
	return query
}

// encodeTeamListInputQuery 将 appservice.TeamListInput 编码为查询参数。
func encodeTeamListInputQuery(input appservice.TeamListInput) url.Values {
	query := url.Values{}
	setQuery(query, "query", input.Query)
	setPositiveQuery(query, "page", input.Page)
	setPositiveQuery(query, "pageSize", input.PageSize)
	return query
}

// encodeTeamMemberCandidateInputQuery 将 appservice.TeamMemberCandidateInput 编码为查询参数。
func encodeTeamMemberCandidateInputQuery(input appservice.TeamMemberCandidateInput) url.Values {
	query := url.Values{}
	setQuery(query, "query", input.Query)
	setPositiveQuery(query, "page", input.Page)
	setPositiveQuery(query, "pageSize", input.PageSize)
	return query
}

// encodeTeamMemberListInputQuery 将 appservice.TeamMemberListInput 编码为查询参数。
func encodeTeamMemberListInputQuery(input appservice.TeamMemberListInput) url.Values {
	query := url.Values{}
	setQuery(query, "query", input.Query)
	setOptionalQuery(query, "workStatus", input.WorkStatus)
	setPositiveQuery(query, "page", input.Page)
	setPositiveQuery(query, "pageSize", input.PageSize)
	return query
}

// encodeUserListInputQuery 将 appservice.UserListInput 编码为查询参数。
func encodeUserListInputQuery(input appservice.UserListInput) url.Values {
	query := url.Values{}
	setQuery(query, "query", input.Query)
	setOptionalQuery(query, "status", input.Status)
	setQuery(query, "roleId", input.RoleID)
	setQuery(query, "teamId", input.TeamID)
	setPositiveQuery(query, "page", input.Page)
	setPositiveQuery(query, "pageSize", input.PageSize)
	return query
}
