// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ChannelType 定义渠道类型。
 */
export enum ChannelType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ChannelTypeWebsite = "website",
};

/**
 * ContactMethodType 定义联系人联系方式类型。
 */
export enum ContactMethodType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ContactMethodTypeEmail = "email",
    ContactMethodTypePhone = "phone",
};

/**
 * ContactSort 定义联系人列表排序方式。
 */
export enum ContactSort {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ContactSortUpdatedAtDescending = "updatedAt.desc",
    ContactSortCreatedAtDescending = "createdAt.desc",
    ContactSortDisplayNameAscending = "displayName.asc",
};

/**
 * ContactStage 定义联系人阶段。
 */
export enum ContactStage {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ContactStageVisitor = "visitor",
    ContactStageLead = "lead",
    ContactStageCustomer = "customer",
};

/**
 * Locale 定义应用支持的本地化语言。
 */
export enum Locale {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LocaleChineseSimplified = "zh-CN",
    LocaleEnglishUnitedStates = "en-US",
};

/**
 * MessageAuthor 定义消息发送方。
 */
export enum MessageAuthor {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    MessageAuthorVisitor = "visitor",
    MessageAuthorAgent = "agent",
};

/**
 * StorageProvider 定义 S3 兼容对象存储提供商。
 */
export enum StorageProvider {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StorageProviderGeneric = "generic",
    StorageProviderAWS = "aws",
    StorageProviderR2 = "r2",
    StorageProviderAliyun = "aliyun",
    StorageProviderTencent = "tencent",
    StorageProviderBaidu = "baidu",
    StorageProviderQiniu = "qiniu",
    StorageProviderHuawei = "huawei",
    StorageProviderUCloud = "ucloud",
    StorageProviderMinIO = "minio",
    StorageProviderRustFS = "rustfs",
};

/**
 * UserRole 定义企业成员角色。
 */
export enum UserRole {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    UserRoleOwner = "owner",
    UserRoleMember = "member",
};

/**
 * UserStatus 定义企业成员状态。
 */
export enum UserStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    UserStatusActive = "active",
    UserStatusInactive = "inactive",
};
