// Code generated by appservicegen. DO NOT EDIT.

//go:build server

package appservice

import "context"

// GetDeviceWork 返回本设备的工作水位与待领取运行。
func (b *DirectBackend) GetDeviceWork(ctx context.Context, meta RequestMeta) (DeviceWork, error) {
	device, err := b.ops.authenticateDevice(ctx, meta)
	if err != nil {
		var zero DeviceWork
		return zero, err
	}
	return withNormalizedSlices(b.ops.GetDeviceWork(ctx, meta, device))
}

// ClaimDeviceRun 领取派发给本设备的排队运行并取得租约。
func (b *DirectBackend) ClaimDeviceRun(ctx context.Context, meta RequestMeta, runID string) (DeviceRunClaim, error) {
	device, err := b.ops.authenticateDevice(ctx, meta)
	if err != nil {
		var zero DeviceRunClaim
		return zero, err
	}
	return withNormalizedSlices(b.ops.ClaimDeviceRun(ctx, meta, device, runID))
}

// RenewDeviceRunLease 为本设备持有的运行续租，运行已结束时返回 ended。
func (b *DirectBackend) RenewDeviceRunLease(ctx context.Context, meta RequestMeta, runID string) (DeviceRunLease, error) {
	device, err := b.ops.authenticateDevice(ctx, meta)
	if err != nil {
		var zero DeviceRunLease
		return zero, err
	}
	return withNormalizedSlices(b.ops.RenewDeviceRunLease(ctx, meta, device, runID))
}

// PeekDeviceRunInputs 返回本设备持有运行尚未认领的输入信号。
func (b *DirectBackend) PeekDeviceRunInputs(ctx context.Context, meta RequestMeta, runID string, input DeviceRunInputPeekInput) (DeviceRunInputSignals, error) {
	device, err := b.ops.authenticateDevice(ctx, meta)
	if err != nil {
		var zero DeviceRunInputSignals
		return zero, err
	}
	return withNormalizedSlices(b.ops.PeekDeviceRunInputs(ctx, meta, device, runID, input))
}

// ClaimDeviceRunInputs 为本设备持有的运行认领输入并返回截至该边界的上下文消息。
func (b *DirectBackend) ClaimDeviceRunInputs(ctx context.Context, meta RequestMeta, runID string, input DeviceRunInputClaimInput) (DeviceRunClaimedInput, error) {
	device, err := b.ops.authenticateDevice(ctx, meta)
	if err != nil {
		var zero DeviceRunClaimedInput
		return zero, err
	}
	return withNormalizedSlices(b.ops.ClaimDeviceRunInputs(ctx, meta, device, runID, input))
}

// SearchDeviceRunKnowledge 在本设备持有运行绑定的知识库中检索。
func (b *DirectBackend) SearchDeviceRunKnowledge(ctx context.Context, meta RequestMeta, runID string, input DeviceRunKnowledgeSearchInput) (DeviceRunKnowledgeSearchResult, error) {
	device, err := b.ops.authenticateDevice(ctx, meta)
	if err != nil {
		var zero DeviceRunKnowledgeSearchResult
		return zero, err
	}
	return withNormalizedSlices(b.ops.SearchDeviceRunKnowledge(ctx, meta, device, runID, input))
}

// CompleteDeviceRun 以成功结果收尾本设备持有的运行。
func (b *DirectBackend) CompleteDeviceRun(ctx context.Context, meta RequestMeta, runID string, input DeviceRunResultInput) error {
	device, err := b.ops.authenticateDevice(ctx, meta)
	if err != nil {
		return err
	}
	return b.ops.CompleteDeviceRun(ctx, meta, device, runID, input)
}

// FailDeviceRun 以失败原因收尾派发给本设备的运行。
func (b *DirectBackend) FailDeviceRun(ctx context.Context, meta RequestMeta, runID string, input DeviceRunFailureInput) error {
	device, err := b.ops.authenticateDevice(ctx, meta)
	if err != nil {
		return err
	}
	return b.ops.FailDeviceRun(ctx, meta, device, runID, input)
}
