// Code generated by appservicegen. DO NOT EDIT.

//go:build server

package appservice

import "context"

// InstallationStatus 返回服务端初始化状态和公开企业名称。
func (b *DirectBackend) InstallationStatus(ctx context.Context, meta RequestMeta) (InstallationStatus, error) {
	return b.ops.InstallationStatus(ctx, meta)
}

// Login 校验账号密码并建立登录会话。
func (b *DirectBackend) Login(ctx context.Context, meta RequestMeta, input LoginInput) (Auth, error) {
	return b.ops.Login(ctx, meta, input)
}

// Logout 退出当前登录会话。
func (b *DirectBackend) Logout(ctx context.Context, meta RequestMeta) error {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		return err
	}
	return b.ops.Logout(ctx, meta, identity)
}

// LoadIdentity 返回当前登录身份。
func (b *DirectBackend) LoadIdentity(ctx context.Context, meta RequestMeta) (Identity, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero Identity
		return zero, err
	}
	return b.ops.LoadIdentity(ctx, meta, identity)
}

// UpdateProfile 修改当前用户的头像、姓名和邮箱。
func (b *DirectBackend) UpdateProfile(ctx context.Context, meta RequestMeta, input ProfileInput) (CurrentUser, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero CurrentUser
		return zero, err
	}
	return b.ops.UpdateProfile(ctx, meta, identity, input)
}

// CreateFileUpload 创建文件上传请求。
func (b *DirectBackend) CreateFileUpload(ctx context.Context, meta RequestMeta, input FileUploadInput) (FileUpload, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero FileUpload
		return zero, err
	}
	return b.ops.CreateFileUpload(ctx, meta, identity, input)
}

// CompleteFileUpload 核验并完成文件上传。
func (b *DirectBackend) CompleteFileUpload(ctx context.Context, meta RequestMeta, fileID string) (File, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero File
		return zero, err
	}
	return b.ops.CompleteFileUpload(ctx, meta, identity, fileID)
}

// CreateFilePartUpload 创建一个分片的直传请求。
func (b *DirectBackend) CreateFilePartUpload(ctx context.Context, meta RequestMeta, fileID string, input FilePartUploadInput) (FileUploadRequest, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero FileUploadRequest
		return zero, err
	}
	return b.ops.CreateFilePartUpload(ctx, meta, identity, fileID, input)
}

// PrepareFileUpload 为已有文件记录准备直传请求。
func (b *DirectBackend) PrepareFileUpload(ctx context.Context, meta RequestMeta, fileID string) (FileUpload, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero FileUpload
		return zero, err
	}
	return b.ops.PrepareFileUpload(ctx, meta, identity, fileID)
}

// CompleteAttachmentUpload 完成文件上传并激活原附件消息。
func (b *DirectBackend) CompleteAttachmentUpload(ctx context.Context, meta RequestMeta, fileID string) error {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		return err
	}
	return b.ops.CompleteAttachmentUpload(ctx, meta, identity, fileID)
}

// CancelFileUpload 将未发送的临时文件交给清理任务。
func (b *DirectBackend) CancelFileUpload(ctx context.Context, meta RequestMeta, fileID string) error {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		return err
	}
	return b.ops.CancelFileUpload(ctx, meta, identity, fileID)
}

// SendAttachmentMessage 发送内部单聊或群聊附件消息。
func (b *DirectBackend) SendAttachmentMessage(ctx context.Context, meta RequestMeta, input AttachmentMessageInput) (AttachmentMessageResult, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero AttachmentMessageResult
		return zero, err
	}
	return b.ops.SendAttachmentMessage(ctx, meta, identity, input)
}

// SendAttachmentBatch 按选择顺序保存可带说明的单聊附件消息。
func (b *DirectBackend) SendAttachmentBatch(ctx context.Context, meta RequestMeta, input AttachmentBatchInput) (AttachmentBatchResult, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero AttachmentBatchResult
		return zero, err
	}
	return b.ops.SendAttachmentBatch(ctx, meta, identity, input)
}

// UpdateAttachmentUploads 更新附件上传状态或取消尚未完成的消息。
func (b *DirectBackend) UpdateAttachmentUploads(ctx context.Context, meta RequestMeta, input AttachmentUploadUpdate) error {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		return err
	}
	return b.ops.UpdateAttachmentUploads(ctx, meta, identity, input)
}

// ListAttachmentStates 读取窗口内已存在附件消息的最新状态。
func (b *DirectBackend) ListAttachmentStates(ctx context.Context, meta RequestMeta, conversationID string, input AttachmentStateListInput) (AttachmentStateList, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero AttachmentStateList
		return zero, err
	}
	return b.ops.ListAttachmentStates(ctx, meta, identity, conversationID, input)
}

// GetAttachmentDownload 签发当前成员可见消息附件的下载地址。
func (b *DirectBackend) GetAttachmentDownload(ctx context.Context, meta RequestMeta, conversationID string, messageID string) (FileDownload, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero FileDownload
		return zero, err
	}
	return b.ops.GetAttachmentDownload(ctx, meta, identity, conversationID, messageID)
}

// ChangePassword 核验当前密码并保存新密码。
func (b *DirectBackend) ChangePassword(ctx context.Context, meta RequestMeta, input ChangePasswordInput) error {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		return err
	}
	return b.ops.ChangePassword(ctx, meta, identity, input)
}

// UpdateUserPreferences 保存当前用户的偏好设置。
func (b *DirectBackend) UpdateUserPreferences(ctx context.Context, meta RequestMeta, input UserPreferencesInput) (CurrentUser, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero CurrentUser
		return zero, err
	}
	return b.ops.UpdateUserPreferences(ctx, meta, identity, input)
}

// UpdateUserWorkStatus 保存当前用户主动设置的工作状态。
func (b *DirectBackend) UpdateUserWorkStatus(ctx context.Context, meta RequestMeta, input UserWorkStatusInput) (CurrentUser, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero CurrentUser
		return zero, err
	}
	return b.ops.UpdateUserWorkStatus(ctx, meta, identity, input)
}

// LoadInbox 返回当前用户的统一收件箱。
func (b *DirectBackend) LoadInbox(ctx context.Context, meta RequestMeta, input LoadInboxInput) (Inbox, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero Inbox
		return zero, err
	}
	return b.ops.LoadInbox(ctx, meta, identity, input)
}

// GetInboxContext 返回会话锚点的当前资格和原位置邻域。
func (b *DirectBackend) GetInboxContext(ctx context.Context, meta RequestMeta, input InboxContextInput) (InboxContext, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero InboxContext
		return zero, err
	}
	return b.ops.GetInboxContext(ctx, meta, identity, input)
}

// ReadInboxWindow 重读已加载双向边界之间的完整列表范围。
func (b *DirectBackend) ReadInboxWindow(ctx context.Context, meta RequestMeta, input InboxWindowInput) (InboxWindow, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero InboxWindow
		return zero, err
	}
	return b.ops.ReadInboxWindow(ctx, meta, identity, input)
}

// GetInboxConversation 返回当前用户有权阅读的独立会话摘要。
func (b *DirectBackend) GetInboxConversation(ctx context.Context, meta RequestMeta, conversationID string) (InboxConversation, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero InboxConversation
		return zero, err
	}
	return b.ops.GetInboxConversation(ctx, meta, identity, conversationID)
}

// ReadInboxConversations 按 ID 批量返回会话摘要及当前筛选资格。
func (b *DirectBackend) ReadInboxConversations(ctx context.Context, meta RequestMeta, input ReadInboxConversationsInput) (InboxConversationResults, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero InboxConversationResults
		return zero, err
	}
	return b.ops.ReadInboxConversations(ctx, meta, identity, input)
}

// ListCustomerServiceAssignees 返回有效真人和 AI 客服。
func (b *DirectBackend) ListCustomerServiceAssignees(ctx context.Context, meta RequestMeta) (CustomerServiceAssigneeList, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero CustomerServiceAssigneeList
		return zero, err
	}
	return b.ops.ListCustomerServiceAssignees(ctx, meta, identity)
}

// ListConversationMessages 返回成员可见的会话消息。
func (b *DirectBackend) ListConversationMessages(ctx context.Context, meta RequestMeta, conversationID string, input ConversationMessageListInput) (ConversationMessageList, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero ConversationMessageList
		return zero, err
	}
	return b.ops.ListConversationMessages(ctx, meta, identity, conversationID, input)
}

// ListConversationMessageReferences 读取当前窗口的引用摘要和回复可用状态。
func (b *DirectBackend) ListConversationMessageReferences(ctx context.Context, meta RequestMeta, conversationID string, input ConversationMessageReferenceListInput) (ConversationMessageReferenceList, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero ConversationMessageReferenceList
		return zero, err
	}
	return b.ops.ListConversationMessageReferences(ctx, meta, identity, conversationID, input)
}

// GetConversationMessageContext 返回目标消息及其前后上下文。
func (b *DirectBackend) GetConversationMessageContext(ctx context.Context, meta RequestMeta, conversationID string, messageID string) (ConversationMessageList, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero ConversationMessageList
		return zero, err
	}
	return b.ops.GetConversationMessageContext(ctx, meta, identity, conversationID, messageID)
}

// GetConversationNavigationState 返回群聊提及进度和最新可见消息。
func (b *DirectBackend) GetConversationNavigationState(ctx context.Context, meta RequestMeta, conversationID string) (ConversationNavigationState, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero ConversationNavigationState
		return zero, err
	}
	return b.ops.GetConversationNavigationState(ctx, meta, identity, conversationID)
}

// ListPendingConversationMentions 返回本轮待查看提及目标。
func (b *DirectBackend) ListPendingConversationMentions(ctx context.Context, meta RequestMeta, conversationID string) (PendingConversationMentions, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero PendingConversationMentions
		return zero, err
	}
	return b.ops.ListPendingConversationMentions(ctx, meta, identity, conversationID)
}

// MarkConversationMentionReviewed 确认已查看的群聊提及。
func (b *DirectBackend) MarkConversationMentionReviewed(ctx context.Context, meta RequestMeta, conversationID string, input MarkConversationMentionReviewedInput) (ConversationMentionReview, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero ConversationMentionReview
		return zero, err
	}
	return b.ops.MarkConversationMentionReviewed(ctx, meta, identity, conversationID, input)
}

// MarkConversationRead 单调推进当前用户的会话已读水位。
func (b *DirectBackend) MarkConversationRead(ctx context.Context, meta RequestMeta, conversationID string, input MarkConversationReadInput) (ConversationReadState, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero ConversationReadState
		return zero, err
	}
	return b.ops.MarkConversationRead(ctx, meta, identity, conversationID, input)
}

// UpdateConversationUnreadMark 保存当前用户独立于阅读水位的未读标记。
func (b *DirectBackend) UpdateConversationUnreadMark(ctx context.Context, meta RequestMeta, conversationID string, input ConversationUnreadMarkInput) error {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		return err
	}
	return b.ops.UpdateConversationUnreadMark(ctx, meta, identity, conversationID, input)
}

// UpdateConversationNotificationSettings 保存当前用户的原生会话提醒设置。
func (b *DirectBackend) UpdateConversationNotificationSettings(ctx context.Context, meta RequestMeta, conversationID string, input ConversationNotificationSettingsInput) (ConversationNotificationSettings, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero ConversationNotificationSettings
		return zero, err
	}
	return b.ops.UpdateConversationNotificationSettings(ctx, meta, identity, conversationID, input)
}

// SendCustomerTextMessage 发送客户会话文本消息。
func (b *DirectBackend) SendCustomerTextMessage(ctx context.Context, meta RequestMeta, conversationID string, input CustomerTextMessageInput) (ConversationMessage, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero ConversationMessage
		return zero, err
	}
	return b.ops.SendCustomerTextMessage(ctx, meta, identity, conversationID, input)
}

// ListCustomerMessageDeliveries 读取当前窗口的外部投递状态。
func (b *DirectBackend) ListCustomerMessageDeliveries(ctx context.Context, meta RequestMeta, conversationID string, input CustomerDeliveryListInput) (CustomerDeliveryList, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero CustomerDeliveryList
		return zero, err
	}
	return b.ops.ListCustomerMessageDeliveries(ctx, meta, identity, conversationID, input)
}

// ResolveCustomerMessageDelivery 人工处理失败或待确认的投递。
func (b *DirectBackend) ResolveCustomerMessageDelivery(ctx context.Context, meta RequestMeta, conversationID string, deliveryID string, input CustomerDeliveryResolveInput) error {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		return err
	}
	return b.ops.ResolveCustomerMessageDelivery(ctx, meta, identity, conversationID, deliveryID, input)
}

// ClaimServiceSession 领取或接管客户会话最新处理周期。
func (b *DirectBackend) ClaimServiceSession(ctx context.Context, meta RequestMeta, conversationID string) (CustomerServiceSession, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero CustomerServiceSession
		return zero, err
	}
	return b.ops.ClaimServiceSession(ctx, meta, identity, conversationID)
}

// TransferServiceSession 把当前负责的处理周期转给另一位客服。
func (b *DirectBackend) TransferServiceSession(ctx context.Context, meta RequestMeta, conversationID string, input TransferServiceSessionInput) (CustomerServiceSession, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero CustomerServiceSession
		return zero, err
	}
	return b.ops.TransferServiceSession(ctx, meta, identity, conversationID, input)
}

// CloseServiceSession 关闭客户会话最新处理周期。
func (b *DirectBackend) CloseServiceSession(ctx context.Context, meta RequestMeta, conversationID string) (CustomerServiceSession, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero CustomerServiceSession
		return zero, err
	}
	return b.ops.CloseServiceSession(ctx, meta, identity, conversationID)
}

// ReopenServiceSession 重新打开客户会话最新处理周期并分配给当前身份。
func (b *DirectBackend) ReopenServiceSession(ctx context.Context, meta RequestMeta, conversationID string) (CustomerServiceSession, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero CustomerServiceSession
		return zero, err
	}
	return b.ops.ReopenServiceSession(ctx, meta, identity, conversationID)
}

// SendFirstDirectTextMessage 向目标身份发送首条单聊消息并按需创建长期会话。
func (b *DirectBackend) SendFirstDirectTextMessage(ctx context.Context, meta RequestMeta, input FirstDirectTextMessageInput) (FirstDirectTextMessageResult, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero FirstDirectTextMessageResult
		return zero, err
	}
	return b.ops.SendFirstDirectTextMessage(ctx, meta, identity, input)
}

// SendFirstAgentTextMessage 在首次发送时创建独立 AI 聊天。
func (b *DirectBackend) SendFirstAgentTextMessage(ctx context.Context, meta RequestMeta, input FirstAgentTextMessageInput) (FirstAgentTextMessageResult, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero FirstAgentTextMessageResult
		return zero, err
	}
	return b.ops.SendFirstAgentTextMessage(ctx, meta, identity, input)
}

// SendAgentTextMessage 向已有 AI 会话发送文本消息。
func (b *DirectBackend) SendAgentTextMessage(ctx context.Context, meta RequestMeta, conversationID string, input AgentTextMessageInput) (ConversationMessage, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero ConversationMessage
		return zero, err
	}
	return b.ops.SendAgentTextMessage(ctx, meta, identity, conversationID, input)
}

// StopAgentReply 停止独立 AI 会话中指定的回复并返回实际运行状态。
func (b *DirectBackend) StopAgentReply(ctx context.Context, meta RequestMeta, conversationID string, runID string) (AgentRunStatus, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero AgentRunStatus
		return zero, err
	}
	return b.ops.StopAgentReply(ctx, meta, identity, conversationID, runID)
}

// FindDirectConversation 按目标身份查找当前成员的活跃单聊。
func (b *DirectBackend) FindDirectConversation(ctx context.Context, meta RequestMeta, targetIdentityID string) (DirectConversationLookup, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero DirectConversationLookup
		return zero, err
	}
	return b.ops.FindDirectConversation(ctx, meta, identity, targetIdentityID)
}

// SendDirectTextMessage 发送内部单聊文本消息。
func (b *DirectBackend) SendDirectTextMessage(ctx context.Context, meta RequestMeta, conversationID string, input DirectTextMessageInput) (ConversationMessage, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero ConversationMessage
		return zero, err
	}
	return b.ops.SendDirectTextMessage(ctx, meta, identity, conversationID, input)
}

// CreateGroupConversation 创建企业内部群聊。
func (b *DirectBackend) CreateGroupConversation(ctx context.Context, meta RequestMeta, input GroupConversationInput) (InboxConversation, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero InboxConversation
		return zero, err
	}
	return b.ops.CreateGroupConversation(ctx, meta, identity, input)
}

// GetGroupConversation 返回当前成员可见的群聊资料。
func (b *DirectBackend) GetGroupConversation(ctx context.Context, meta RequestMeta, conversationID string) (GroupConversation, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero GroupConversation
		return zero, err
	}
	return b.ops.GetGroupConversation(ctx, meta, identity, conversationID)
}

// UpdateGroupConversation 修改群聊资料。
func (b *DirectBackend) UpdateGroupConversation(ctx context.Context, meta RequestMeta, conversationID string, input GroupConversationProfileInput) (GroupConversation, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero GroupConversation
		return zero, err
	}
	return b.ops.UpdateGroupConversation(ctx, meta, identity, conversationID, input)
}

// AddGroupConversationMembers 批量增加群聊成员。
func (b *DirectBackend) AddGroupConversationMembers(ctx context.Context, meta RequestMeta, conversationID string, input GroupConversationMembersInput) (GroupConversation, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero GroupConversation
		return zero, err
	}
	return b.ops.AddGroupConversationMembers(ctx, meta, identity, conversationID, input)
}

// RemoveGroupConversationMember 移除单个群聊成员。
func (b *DirectBackend) RemoveGroupConversationMember(ctx context.Context, meta RequestMeta, conversationID string, input GroupConversationMemberInput) (GroupConversation, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero GroupConversation
		return zero, err
	}
	return b.ops.RemoveGroupConversationMember(ctx, meta, identity, conversationID, input)
}

// TransferGroupConversationOwner 转让群主。
func (b *DirectBackend) TransferGroupConversationOwner(ctx context.Context, meta RequestMeta, conversationID string, input GroupConversationOwnerInput) (GroupConversation, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero GroupConversation
		return zero, err
	}
	return b.ops.TransferGroupConversationOwner(ctx, meta, identity, conversationID, input)
}

// LeaveGroupConversation 退出普通成员参与的群聊。
func (b *DirectBackend) LeaveGroupConversation(ctx context.Context, meta RequestMeta, conversationID string) error {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		return err
	}
	return b.ops.LeaveGroupConversation(ctx, meta, identity, conversationID)
}

// DissolveGroupConversation 解散群聊并保留当前成员的只读历史。
func (b *DirectBackend) DissolveGroupConversation(ctx context.Context, meta RequestMeta, conversationID string) (GroupConversation, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero GroupConversation
		return zero, err
	}
	return b.ops.DissolveGroupConversation(ctx, meta, identity, conversationID)
}

// SendGroupTextMessage 发送企业内部群聊文本消息。
func (b *DirectBackend) SendGroupTextMessage(ctx context.Context, meta RequestMeta, conversationID string, input GroupTextMessageInput) (ConversationMessage, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero ConversationMessage
		return zero, err
	}
	return b.ops.SendGroupTextMessage(ctx, meta, identity, conversationID, input)
}

// ListMessageChannels 返回消息渠道列表。
func (b *DirectBackend) ListMessageChannels(ctx context.Context, meta RequestMeta) (MessageChannelList, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero MessageChannelList
		return zero, err
	}
	return b.ops.ListMessageChannels(ctx, meta, identity)
}

// GetWebsiteChannel 返回网站渠道详情。
func (b *DirectBackend) GetWebsiteChannel(ctx context.Context, meta RequestMeta, channelID string) (WebsiteChannel, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero WebsiteChannel
		return zero, err
	}
	return b.ops.GetWebsiteChannel(ctx, meta, identity, channelID)
}

// GetTelegramChannel 返回 Telegram 渠道详情。
func (b *DirectBackend) GetTelegramChannel(ctx context.Context, meta RequestMeta, channelID string) (TelegramChannel, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero TelegramChannel
		return zero, err
	}
	return b.ops.GetTelegramChannel(ctx, meta, identity, channelID)
}

// TestTelegramChannelConnection 测试 Telegram 草稿 Token。
func (b *DirectBackend) TestTelegramChannelConnection(ctx context.Context, meta RequestMeta, channelID string, input TelegramChannelConnectionTestInput) error {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		return err
	}
	return b.ops.TestTelegramChannelConnection(ctx, meta, identity, channelID, input)
}

// SaveTelegramChannelConnection 保存 Telegram 机器人和 Webhook 设置。
func (b *DirectBackend) SaveTelegramChannelConnection(ctx context.Context, meta RequestMeta, channelID string, input TelegramChannelConnectionInput) (TelegramChannel, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero TelegramChannel
		return zero, err
	}
	return b.ops.SaveTelegramChannelConnection(ctx, meta, identity, channelID, input)
}

// GetMessageChannel 返回消息渠道基础信息。
func (b *DirectBackend) GetMessageChannel(ctx context.Context, meta RequestMeta, channelID string) (MessageChannelSummary, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero MessageChannelSummary
		return zero, err
	}
	return b.ops.GetMessageChannel(ctx, meta, identity, channelID)
}

// CreateMessageChannel 创建消息渠道。
func (b *DirectBackend) CreateMessageChannel(ctx context.Context, meta RequestMeta, input CreateMessageChannelInput) (MessageChannelSummary, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero MessageChannelSummary
		return zero, err
	}
	return b.ops.CreateMessageChannel(ctx, meta, identity, input)
}

// UpdateMessageChannel 修改消息渠道基础信息。
func (b *DirectBackend) UpdateMessageChannel(ctx context.Context, meta RequestMeta, channelID string, input MessageChannelInput) (MessageChannelSummary, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero MessageChannelSummary
		return zero, err
	}
	return b.ops.UpdateMessageChannel(ctx, meta, identity, channelID, input)
}

// UpdateWebsiteChannelChatInterface 修改网站渠道聊天界面。
func (b *DirectBackend) UpdateWebsiteChannelChatInterface(ctx context.Context, meta RequestMeta, channelID string, input WebsiteChannelChatInterfaceInput) (WebsiteChannelChatInterface, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero WebsiteChannelChatInterface
		return zero, err
	}
	return b.ops.UpdateWebsiteChannelChatInterface(ctx, meta, identity, channelID, input)
}

// UpdateWebsiteChannelAccess 修改网站渠道允许使用的网站。
func (b *DirectBackend) UpdateWebsiteChannelAccess(ctx context.Context, meta RequestMeta, channelID string, input WebsiteChannelAccessInput) (WebsiteChannelAccess, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero WebsiteChannelAccess
		return zero, err
	}
	return b.ops.UpdateWebsiteChannelAccess(ctx, meta, identity, channelID, input)
}

// DeactivateMessageChannel 停用消息渠道。
func (b *DirectBackend) DeactivateMessageChannel(ctx context.Context, meta RequestMeta, channelID string) (MessageChannelSummary, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero MessageChannelSummary
		return zero, err
	}
	return b.ops.DeactivateMessageChannel(ctx, meta, identity, channelID)
}

// ActivateMessageChannel 启用消息渠道。
func (b *DirectBackend) ActivateMessageChannel(ctx context.Context, meta RequestMeta, channelID string) (MessageChannelSummary, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero MessageChannelSummary
		return zero, err
	}
	return b.ops.ActivateMessageChannel(ctx, meta, identity, channelID)
}

// ListChannelOptions 返回当前企业的渠道选择项。
func (b *DirectBackend) ListChannelOptions(ctx context.Context, meta RequestMeta) (ChannelOptionList, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero ChannelOptionList
		return zero, err
	}
	return b.ops.ListChannelOptions(ctx, meta, identity)
}

// ListMemberOptions 返回可分配的企业成员和 AI 员工。
func (b *DirectBackend) ListMemberOptions(ctx context.Context, meta RequestMeta, input MemberOptionListInput) (MemberOptionList, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero MemberOptionList
		return zero, err
	}
	return b.ops.ListMemberOptions(ctx, meta, identity, input)
}

// ListAgentMCPServerOptions 返回当前企业可配置的 MCP 服务。
func (b *DirectBackend) ListAgentMCPServerOptions(ctx context.Context, meta RequestMeta) (AgentMCPServerOptionList, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero AgentMCPServerOptionList
		return zero, err
	}
	return b.ops.ListAgentMCPServerOptions(ctx, meta, identity)
}

// ListAgentModelOptions 返回 AI 员工可使用的对话模型。
func (b *DirectBackend) ListAgentModelOptions(ctx context.Context, meta RequestMeta) (AgentModelOptionList, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero AgentModelOptionList
		return zero, err
	}
	return b.ops.ListAgentModelOptions(ctx, meta, identity)
}

// CreateAgent 创建企业 AI 员工。
func (b *DirectBackend) CreateAgent(ctx context.Context, meta RequestMeta, input CreateAgentInput) (Agent, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero Agent
		return zero, err
	}
	return b.ops.CreateAgent(ctx, meta, identity, input)
}

// ListAgents 返回企业 AI 员工目录。
func (b *DirectBackend) ListAgents(ctx context.Context, meta RequestMeta, input AgentListInput) (AgentList, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero AgentList
		return zero, err
	}
	return b.ops.ListAgents(ctx, meta, identity, input)
}

// GetAgent 返回企业 AI 员工详情。
func (b *DirectBackend) GetAgent(ctx context.Context, meta RequestMeta, agentID string) (Agent, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero Agent
		return zero, err
	}
	return b.ops.GetAgent(ctx, meta, identity, agentID)
}

// UpdateAgent 修改企业 AI 员工。
func (b *DirectBackend) UpdateAgent(ctx context.Context, meta RequestMeta, agentID string, input UpdateAgentInput) (Agent, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero Agent
		return zero, err
	}
	return b.ops.UpdateAgent(ctx, meta, identity, agentID, input)
}

// UpdateAgentExecution 修改企业 AI 员工的执行配置。
func (b *DirectBackend) UpdateAgentExecution(ctx context.Context, meta RequestMeta, agentID string, input UpdateAgentExecutionInput) (Agent, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero Agent
		return zero, err
	}
	return b.ops.UpdateAgentExecution(ctx, meta, identity, agentID, input)
}

// DeactivateAgent 禁用企业 AI 员工账号。
func (b *DirectBackend) DeactivateAgent(ctx context.Context, meta RequestMeta, agentID string) (Agent, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero Agent
		return zero, err
	}
	return b.ops.DeactivateAgent(ctx, meta, identity, agentID)
}

// ReactivateAgent 恢复企业 AI 员工。
func (b *DirectBackend) ReactivateAgent(ctx context.Context, meta RequestMeta, agentID string) (Agent, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero Agent
		return zero, err
	}
	return b.ops.ReactivateAgent(ctx, meta, identity, agentID)
}

// ListUsers 返回企业成员列表。
func (b *DirectBackend) ListUsers(ctx context.Context, meta RequestMeta, input UserListInput) (UserList, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero UserList
		return zero, err
	}
	return b.ops.ListUsers(ctx, meta, identity, input)
}

// GetUser 返回企业成员详情。
func (b *DirectBackend) GetUser(ctx context.Context, meta RequestMeta, userID string) (User, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero User
		return zero, err
	}
	return b.ops.GetUser(ctx, meta, identity, userID)
}

// CreateUser 创建企业成员账号。
func (b *DirectBackend) CreateUser(ctx context.Context, meta RequestMeta, input CreateUserInput) (User, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero User
		return zero, err
	}
	return b.ops.CreateUser(ctx, meta, identity, input)
}

// UpdateUser 修改企业成员资料、角色和所属团队。
func (b *DirectBackend) UpdateUser(ctx context.Context, meta RequestMeta, userID string, input UpdateUserInput) (User, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero User
		return zero, err
	}
	return b.ops.UpdateUser(ctx, meta, identity, userID, input)
}

// UpdateRoleAssignments 在一个事务中批量调整真人和 AI 员工角色。
func (b *DirectBackend) UpdateRoleAssignments(ctx context.Context, meta RequestMeta, input RoleAssignmentsInput) error {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		return err
	}
	return b.ops.UpdateRoleAssignments(ctx, meta, identity, input)
}

// DeactivateUser 禁用企业成员账号。
func (b *DirectBackend) DeactivateUser(ctx context.Context, meta RequestMeta, userID string) (User, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero User
		return zero, err
	}
	return b.ops.DeactivateUser(ctx, meta, identity, userID)
}

// ReactivateUser 恢复企业成员账号。
func (b *DirectBackend) ReactivateUser(ctx context.Context, meta RequestMeta, userID string) (User, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero User
		return zero, err
	}
	return b.ops.ReactivateUser(ctx, meta, identity, userID)
}

// ListTeams 返回企业团队列表。
func (b *DirectBackend) ListTeams(ctx context.Context, meta RequestMeta, input TeamListInput) (TeamList, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero TeamList
		return zero, err
	}
	return b.ops.ListTeams(ctx, meta, identity, input)
}

// CreateTeam 创建企业团队。
func (b *DirectBackend) CreateTeam(ctx context.Context, meta RequestMeta, input TeamInput) (Team, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero Team
		return zero, err
	}
	return b.ops.CreateTeam(ctx, meta, identity, input)
}

// UpdateTeam 修改企业团队。
func (b *DirectBackend) UpdateTeam(ctx context.Context, meta RequestMeta, teamID string, input TeamInput) (Team, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero Team
		return zero, err
	}
	return b.ops.UpdateTeam(ctx, meta, identity, teamID, input)
}

// DeleteTeam 删除企业团队及其成员关系。
func (b *DirectBackend) DeleteTeam(ctx context.Context, meta RequestMeta, teamID string) error {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		return err
	}
	return b.ops.DeleteTeam(ctx, meta, identity, teamID)
}

// ListTeamMembers 返回团队成员列表。
func (b *DirectBackend) ListTeamMembers(ctx context.Context, meta RequestMeta, teamID string, input TeamMemberListInput) (TeamMemberList, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero TeamMemberList
		return zero, err
	}
	return b.ops.ListTeamMembers(ctx, meta, identity, teamID, input)
}

// ListTeamMemberCandidates 返回尚未加入团队的企业身份。
func (b *DirectBackend) ListTeamMemberCandidates(ctx context.Context, meta RequestMeta, teamID string, input TeamMemberCandidateInput) (TeamMemberCandidateList, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero TeamMemberCandidateList
		return zero, err
	}
	return b.ops.ListTeamMemberCandidates(ctx, meta, identity, teamID, input)
}

// AddTeamMembers 将企业身份批量加入团队。
func (b *DirectBackend) AddTeamMembers(ctx context.Context, meta RequestMeta, teamID string, input TeamMemberInput) (Team, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero Team
		return zero, err
	}
	return b.ops.AddTeamMembers(ctx, meta, identity, teamID, input)
}

// RemoveTeamMembers 将企业身份批量移出团队。
func (b *DirectBackend) RemoveTeamMembers(ctx context.Context, meta RequestMeta, teamID string, input TeamMemberInput) (Team, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero Team
		return zero, err
	}
	return b.ops.RemoveTeamMembers(ctx, meta, identity, teamID, input)
}

// RetryKnowledgeDocument 按当前配置重新处理文档。
func (b *DirectBackend) RetryKnowledgeDocument(ctx context.Context, meta RequestMeta, knowledgeBaseID string, documentID string) error {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		return err
	}
	return b.ops.RetryKnowledgeDocument(ctx, meta, identity, knowledgeBaseID, documentID)
}

// ListKnowledgeDocumentSegments 返回固定批次的分段页或锚点所在页。
func (b *DirectBackend) ListKnowledgeDocumentSegments(ctx context.Context, meta RequestMeta, knowledgeBaseID string, documentID string, input KnowledgeDocumentSegmentInput) (KnowledgeDocumentSegmentPage, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero KnowledgeDocumentSegmentPage
		return zero, err
	}
	return b.ops.ListKnowledgeDocumentSegments(ctx, meta, identity, knowledgeBaseID, documentID, input)
}

// ListKnowledgeDocuments 返回当前分组的文档列表。
func (b *DirectBackend) ListKnowledgeDocuments(ctx context.Context, meta RequestMeta, knowledgeBaseID string, input KnowledgeDocumentListInput) (KnowledgeDocumentList, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero KnowledgeDocumentList
		return zero, err
	}
	return b.ops.ListKnowledgeDocuments(ctx, meta, identity, knowledgeBaseID, input)
}

// GetKnowledgeDocument 返回文档详情。
func (b *DirectBackend) GetKnowledgeDocument(ctx context.Context, meta RequestMeta, knowledgeBaseID string, documentID string) (KnowledgeDocument, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero KnowledgeDocument
		return zero, err
	}
	return b.ops.GetKnowledgeDocument(ctx, meta, identity, knowledgeBaseID, documentID)
}

// CreateKnowledgeDocuments 保存最多十个已上传的文档原件。
func (b *DirectBackend) CreateKnowledgeDocuments(ctx context.Context, meta RequestMeta, knowledgeBaseID string, input KnowledgeDocumentBatchInput) (KnowledgeDocumentBatch, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero KnowledgeDocumentBatch
		return zero, err
	}
	return b.ops.CreateKnowledgeDocuments(ctx, meta, identity, knowledgeBaseID, input)
}

// MoveKnowledgeDocument 移动文档到同库分组。
func (b *DirectBackend) MoveKnowledgeDocument(ctx context.Context, meta RequestMeta, knowledgeBaseID string, documentID string, input KnowledgeDocumentMoveInput) error {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		return err
	}
	return b.ops.MoveKnowledgeDocument(ctx, meta, identity, knowledgeBaseID, documentID, input)
}

// DeleteKnowledgeDocument 删除文档并释放原件。
func (b *DirectBackend) DeleteKnowledgeDocument(ctx context.Context, meta RequestMeta, knowledgeBaseID string, documentID string) error {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		return err
	}
	return b.ops.DeleteKnowledgeDocument(ctx, meta, identity, knowledgeBaseID, documentID)
}

// GetKnowledgeDocumentPreview 签发当前文档的原件预览请求。
func (b *DirectBackend) GetKnowledgeDocumentPreview(ctx context.Context, meta RequestMeta, knowledgeBaseID string, documentID string) (KnowledgeDocumentPreviewRequest, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero KnowledgeDocumentPreviewRequest
		return zero, err
	}
	return b.ops.GetKnowledgeDocumentPreview(ctx, meta, identity, knowledgeBaseID, documentID)
}

// ListKnowledgeQAEntries 返回分组中的本地问答列表。
func (b *DirectBackend) ListKnowledgeQAEntries(ctx context.Context, meta RequestMeta, knowledgeBaseID string, input KnowledgeQAListInput) (KnowledgeQAList, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero KnowledgeQAList
		return zero, err
	}
	return b.ops.ListKnowledgeQAEntries(ctx, meta, identity, knowledgeBaseID, input)
}

// GetKnowledgeQAEntry 返回完整的本地问答。
func (b *DirectBackend) GetKnowledgeQAEntry(ctx context.Context, meta RequestMeta, knowledgeBaseID string, entryID string) (KnowledgeQAEntry, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero KnowledgeQAEntry
		return zero, err
	}
	return b.ops.GetKnowledgeQAEntry(ctx, meta, identity, knowledgeBaseID, entryID)
}

// CreateKnowledgeQAEntry 创建本地问答。
func (b *DirectBackend) CreateKnowledgeQAEntry(ctx context.Context, meta RequestMeta, knowledgeBaseID string, input KnowledgeQAInput) (KnowledgeQAEntry, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero KnowledgeQAEntry
		return zero, err
	}
	return b.ops.CreateKnowledgeQAEntry(ctx, meta, identity, knowledgeBaseID, input)
}

// UpdateKnowledgeQAEntry 修改本地问答。
func (b *DirectBackend) UpdateKnowledgeQAEntry(ctx context.Context, meta RequestMeta, knowledgeBaseID string, entryID string, input KnowledgeQAInput) (KnowledgeQAEntry, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero KnowledgeQAEntry
		return zero, err
	}
	return b.ops.UpdateKnowledgeQAEntry(ctx, meta, identity, knowledgeBaseID, entryID, input)
}

// DeleteKnowledgeQAEntry 删除本地问答。
func (b *DirectBackend) DeleteKnowledgeQAEntry(ctx context.Context, meta RequestMeta, knowledgeBaseID string, entryID string) error {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		return err
	}
	return b.ops.DeleteKnowledgeQAEntry(ctx, meta, identity, knowledgeBaseID, entryID)
}

// ListKnowledgeBases 返回当前企业的知识库列表。
func (b *DirectBackend) ListKnowledgeBases(ctx context.Context, meta RequestMeta) (KnowledgeBaseList, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero KnowledgeBaseList
		return zero, err
	}
	return b.ops.ListKnowledgeBases(ctx, meta, identity)
}

// GetKnowledgeBase 返回当前企业中的知识库详情。
func (b *DirectBackend) GetKnowledgeBase(ctx context.Context, meta RequestMeta, knowledgeBaseID string) (KnowledgeBase, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero KnowledgeBase
		return zero, err
	}
	return b.ops.GetKnowledgeBase(ctx, meta, identity, knowledgeBaseID)
}

// CreateKnowledgeBase 创建企业知识库。
func (b *DirectBackend) CreateKnowledgeBase(ctx context.Context, meta RequestMeta, input KnowledgeBaseInput) (KnowledgeBase, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero KnowledgeBase
		return zero, err
	}
	return b.ops.CreateKnowledgeBase(ctx, meta, identity, input)
}

// UpdateKnowledgeBase 修改企业知识库。
func (b *DirectBackend) UpdateKnowledgeBase(ctx context.Context, meta RequestMeta, knowledgeBaseID string, input KnowledgeBaseInput) (KnowledgeBase, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero KnowledgeBase
		return zero, err
	}
	return b.ops.UpdateKnowledgeBase(ctx, meta, identity, knowledgeBaseID, input)
}

// DeleteKnowledgeBase 删除企业知识库。
func (b *DirectBackend) DeleteKnowledgeBase(ctx context.Context, meta RequestMeta, knowledgeBaseID string) error {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		return err
	}
	return b.ops.DeleteKnowledgeBase(ctx, meta, identity, knowledgeBaseID)
}

// CreateKnowledgeGroup 创建知识库分组。
func (b *DirectBackend) CreateKnowledgeGroup(ctx context.Context, meta RequestMeta, knowledgeBaseID string, input KnowledgeGroupInput) (KnowledgeBase, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero KnowledgeBase
		return zero, err
	}
	return b.ops.CreateKnowledgeGroup(ctx, meta, identity, knowledgeBaseID, input)
}

// UpdateKnowledgeGroup 修改知识库分组。
func (b *DirectBackend) UpdateKnowledgeGroup(ctx context.Context, meta RequestMeta, knowledgeBaseID string, groupID string, input KnowledgeGroupInput) (KnowledgeBase, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero KnowledgeBase
		return zero, err
	}
	return b.ops.UpdateKnowledgeGroup(ctx, meta, identity, knowledgeBaseID, groupID, input)
}

// DeleteKnowledgeGroup 删除不含子分组和问答的知识库分组。
func (b *DirectBackend) DeleteKnowledgeGroup(ctx context.Context, meta RequestMeta, knowledgeBaseID string, groupID string) (KnowledgeBase, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero KnowledgeBase
		return zero, err
	}
	return b.ops.DeleteKnowledgeGroup(ctx, meta, identity, knowledgeBaseID, groupID)
}

// ListContacts 返回联系人列表。
func (b *DirectBackend) ListContacts(ctx context.Context, meta RequestMeta, input ContactListInput) (ContactList, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero ContactList
		return zero, err
	}
	return b.ops.ListContacts(ctx, meta, identity, input)
}

// GetContact 返回联系人详情。
func (b *DirectBackend) GetContact(ctx context.Context, meta RequestMeta, contactID string) (Contact, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero Contact
		return zero, err
	}
	return b.ops.GetContact(ctx, meta, identity, contactID)
}

// CreateContact 创建联系人。
func (b *DirectBackend) CreateContact(ctx context.Context, meta RequestMeta, input ContactInput) (Contact, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero Contact
		return zero, err
	}
	return b.ops.CreateContact(ctx, meta, identity, input)
}

// UpdateContact 修改联系人。
func (b *DirectBackend) UpdateContact(ctx context.Context, meta RequestMeta, contactID string, input ContactInput) (Contact, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero Contact
		return zero, err
	}
	return b.ops.UpdateContact(ctx, meta, identity, contactID, input)
}

// DeleteContact 将联系人移入回收站。
func (b *DirectBackend) DeleteContact(ctx context.Context, meta RequestMeta, contactID string) error {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		return err
	}
	return b.ops.DeleteContact(ctx, meta, identity, contactID)
}

// RestoreContact 恢复联系人。
func (b *DirectBackend) RestoreContact(ctx context.Context, meta RequestMeta, contactID string) (Contact, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero Contact
		return zero, err
	}
	return b.ops.RestoreContact(ctx, meta, identity, contactID)
}

// ListRoles 返回当前企业的角色和预定义权限目录。
func (b *DirectBackend) ListRoles(ctx context.Context, meta RequestMeta) (RoleList, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero RoleList
		return zero, err
	}
	return b.ops.ListRoles(ctx, meta, identity)
}

// GetRole 返回当前企业的角色详情。
func (b *DirectBackend) GetRole(ctx context.Context, meta RequestMeta, roleID string) (Role, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero Role
		return zero, err
	}
	return b.ops.GetRole(ctx, meta, identity, roleID)
}

// CreateRole 创建自定义角色。
func (b *DirectBackend) CreateRole(ctx context.Context, meta RequestMeta, input RoleInput) (Role, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero Role
		return zero, err
	}
	return b.ops.CreateRole(ctx, meta, identity, input)
}

// UpdateRole 修改角色信息和权限。
func (b *DirectBackend) UpdateRole(ctx context.Context, meta RequestMeta, roleID string, input RoleInput) (Role, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero Role
		return zero, err
	}
	return b.ops.UpdateRole(ctx, meta, identity, roleID, input)
}

// DeleteRole 删除自定义角色。
func (b *DirectBackend) DeleteRole(ctx context.Context, meta RequestMeta, roleID string) error {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		return err
	}
	return b.ops.DeleteRole(ctx, meta, identity, roleID)
}

// ListAIProviders 返回当前企业的模型服务供应商列表。
func (b *DirectBackend) ListAIProviders(ctx context.Context, meta RequestMeta) (AIProviderList, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero AIProviderList
		return zero, err
	}
	return b.ops.ListAIProviders(ctx, meta, identity)
}

// GetAIProvider 返回当前企业中的模型服务供应商详情。
func (b *DirectBackend) GetAIProvider(ctx context.Context, meta RequestMeta, providerID string) (AIProvider, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero AIProvider
		return zero, err
	}
	return b.ops.GetAIProvider(ctx, meta, identity, providerID)
}

// ListAvailableAIModels 返回指定品牌的预设模型目录。
func (b *DirectBackend) ListAvailableAIModels(ctx context.Context, meta RequestMeta, brand AIProviderBrand) (AIProviderModelList, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero AIProviderModelList
		return zero, err
	}
	return b.ops.ListAvailableAIModels(ctx, meta, identity, brand)
}

// TestAIProviderConnection 测试模型服务供应商草稿配置。
func (b *DirectBackend) TestAIProviderConnection(ctx context.Context, meta RequestMeta, input AIProviderConnectionInput) error {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		return err
	}
	return b.ops.TestAIProviderConnection(ctx, meta, identity, input)
}

// CreateAIProvider 创建模型服务供应商。
func (b *DirectBackend) CreateAIProvider(ctx context.Context, meta RequestMeta, input AIProviderInput) (AIProvider, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero AIProvider
		return zero, err
	}
	return b.ops.CreateAIProvider(ctx, meta, identity, input)
}

// UpdateAIProvider 修改模型服务供应商。
func (b *DirectBackend) UpdateAIProvider(ctx context.Context, meta RequestMeta, providerID string, input AIProviderInput) (AIProvider, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero AIProvider
		return zero, err
	}
	return b.ops.UpdateAIProvider(ctx, meta, identity, providerID, input)
}

// DeleteAIProvider 删除模型服务供应商。
func (b *DirectBackend) DeleteAIProvider(ctx context.Context, meta RequestMeta, providerID string) error {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		return err
	}
	return b.ops.DeleteAIProvider(ctx, meta, identity, providerID)
}

// ListBusinessSystems 返回当前企业配置的业务系统。
func (b *DirectBackend) ListBusinessSystems(ctx context.Context, meta RequestMeta) (BusinessSystemList, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero BusinessSystemList
		return zero, err
	}
	return b.ops.ListBusinessSystems(ctx, meta, identity)
}

// GetBusinessSystem 返回当前企业中的业务系统详情。
func (b *DirectBackend) GetBusinessSystem(ctx context.Context, meta RequestMeta, businessSystemID string) (BusinessSystem, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero BusinessSystem
		return zero, err
	}
	return b.ops.GetBusinessSystem(ctx, meta, identity, businessSystemID)
}

// CreateBusinessSystem 创建业务系统。
func (b *DirectBackend) CreateBusinessSystem(ctx context.Context, meta RequestMeta, input BusinessSystemInput) (BusinessSystem, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero BusinessSystem
		return zero, err
	}
	return b.ops.CreateBusinessSystem(ctx, meta, identity, input)
}

// UpdateBusinessSystem 修改业务系统。
func (b *DirectBackend) UpdateBusinessSystem(ctx context.Context, meta RequestMeta, businessSystemID string, input BusinessSystemInput) (BusinessSystem, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero BusinessSystem
		return zero, err
	}
	return b.ops.UpdateBusinessSystem(ctx, meta, identity, businessSystemID, input)
}

// DeleteBusinessSystem 删除业务系统。
func (b *DirectBackend) DeleteBusinessSystem(ctx context.Context, meta RequestMeta, businessSystemID string) error {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		return err
	}
	return b.ops.DeleteBusinessSystem(ctx, meta, identity, businessSystemID)
}

// ListMCPServers 返回当前企业配置的 MCP 服务。
func (b *DirectBackend) ListMCPServers(ctx context.Context, meta RequestMeta) (MCPServerList, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero MCPServerList
		return zero, err
	}
	return b.ops.ListMCPServers(ctx, meta, identity)
}

// GetMCPServer 返回当前企业中的 MCP 服务详情。
func (b *DirectBackend) GetMCPServer(ctx context.Context, meta RequestMeta, mcpServerID string) (MCPServer, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero MCPServer
		return zero, err
	}
	return b.ops.GetMCPServer(ctx, meta, identity, mcpServerID)
}

// TestMCPServerConnection 测试 MCP 草稿连接配置。
func (b *DirectBackend) TestMCPServerConnection(ctx context.Context, meta RequestMeta, input MCPServerConnectionInput) error {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		return err
	}
	return b.ops.TestMCPServerConnection(ctx, meta, identity, input)
}

// TestSavedMCPServerConnection 测试已保存的 MCP 服务。
func (b *DirectBackend) TestSavedMCPServerConnection(ctx context.Context, meta RequestMeta, mcpServerID string) error {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		return err
	}
	return b.ops.TestSavedMCPServerConnection(ctx, meta, identity, mcpServerID)
}

// RefreshMCPServerTools 提交当前企业的 MCP 工具更新任务。
func (b *DirectBackend) RefreshMCPServerTools(ctx context.Context, meta RequestMeta) error {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		return err
	}
	return b.ops.RefreshMCPServerTools(ctx, meta, identity)
}

// CreateMCPServer 创建 MCP 服务。
func (b *DirectBackend) CreateMCPServer(ctx context.Context, meta RequestMeta, input MCPServerInput) (MCPServer, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero MCPServer
		return zero, err
	}
	return b.ops.CreateMCPServer(ctx, meta, identity, input)
}

// UpdateMCPServer 修改 MCP 服务。
func (b *DirectBackend) UpdateMCPServer(ctx context.Context, meta RequestMeta, mcpServerID string, input MCPServerInput) (MCPServer, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero MCPServer
		return zero, err
	}
	return b.ops.UpdateMCPServer(ctx, meta, identity, mcpServerID, input)
}

// DeleteMCPServer 删除 MCP 服务。
func (b *DirectBackend) DeleteMCPServer(ctx context.Context, meta RequestMeta, mcpServerID string) error {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		return err
	}
	return b.ops.DeleteMCPServer(ctx, meta, identity, mcpServerID)
}

// UpdateOrganization 修改当前企业通用设置。
func (b *DirectBackend) UpdateOrganization(ctx context.Context, meta RequestMeta, input OrganizationInput) (Organization, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero Organization
		return zero, err
	}
	return b.ops.UpdateOrganization(ctx, meta, identity, input)
}

// GetS3Setting 返回当前企业的对象存储设置。
func (b *DirectBackend) GetS3Setting(ctx context.Context, meta RequestMeta) (S3Setting, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero S3Setting
		return zero, err
	}
	return b.ops.GetS3Setting(ctx, meta, identity)
}

// SaveS3Setting 保存当前企业的对象存储设置。
func (b *DirectBackend) SaveS3Setting(ctx context.Context, meta RequestMeta, input S3SettingInput) (S3Setting, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero S3Setting
		return zero, err
	}
	return b.ops.SaveS3Setting(ctx, meta, identity, input)
}

// TestS3Setting 测试对象存储连接。
func (b *DirectBackend) TestS3Setting(ctx context.Context, meta RequestMeta, input S3SettingInput) error {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		return err
	}
	return b.ops.TestS3Setting(ctx, meta, identity, input)
}
