// Code generated by appservicegen. DO NOT EDIT.

//go:build server

package appservice

import "context"

// LoadDeployment 返回部署形态与部署地址。
func (b *OperatorDirectBackend) LoadDeployment(ctx context.Context, meta OperatorRequestMeta) (OperatorDeployment, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero OperatorDeployment
		return zero, err
	}
	return withNormalizedSlices(b.ops.LoadDeployment(ctx, meta, identity))
}

// ListOrganizations 按条件分页返回工作区摘要。
func (b *OperatorDirectBackend) ListOrganizations(ctx context.Context, meta OperatorRequestMeta, input OperatorOrganizationListInput) (OperatorOrganizationList, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero OperatorOrganizationList
		return zero, err
	}
	return withNormalizedSlices(b.ops.ListOrganizations(ctx, meta, identity, input))
}

// GetOrganization 返回工作区摘要与状态。
func (b *OperatorDirectBackend) GetOrganization(ctx context.Context, meta OperatorRequestMeta, organizationID string) (OperatorOrganization, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero OperatorOrganization
		return zero, err
	}
	return withNormalizedSlices(b.ops.GetOrganization(ctx, meta, identity, organizationID))
}
