// Code generated by appservicegen. DO NOT EDIT.

//go:build server

package appservice

import "context"

// LoadDeployment 返回部署形态与企业域名后缀。
func (b *OperatorDirectBackend) LoadDeployment(ctx context.Context, meta OperatorRequestMeta) (OperatorDeployment, error) {
	identity, err := b.ops.authenticate(ctx, meta)
	if err != nil {
		var zero OperatorDeployment
		return zero, err
	}
	return withNormalizedSlices(b.ops.LoadDeployment(ctx, meta, identity))
}
