// Code generated by appservicegen. DO NOT EDIT.

package appservice

import "context"

// InstallationStatus 返回服务端初始化状态和公开企业名称。
func (s *Service) InstallationStatus(ctx context.Context, meta RequestMeta) (InstallationStatus, error) {
	return s.backend.InstallationStatus(ctx, meta)
}

// Logout 退出当前登录会话。
func (s *Service) Logout(ctx context.Context, meta RequestMeta) error {
	return s.backend.Logout(ctx, meta)
}

// UpdateProfile 修改当前用户的头像、姓名和邮箱。
func (s *Service) UpdateProfile(ctx context.Context, meta RequestMeta, input ProfileInput) (CurrentUser, error) {
	return s.backend.UpdateProfile(ctx, meta, input)
}

// CreateFileUpload 创建文件上传请求。
func (s *Service) CreateFileUpload(ctx context.Context, meta RequestMeta, input FileUploadInput) (FileUpload, error) {
	return s.backend.CreateFileUpload(ctx, meta, input)
}

// CompleteFileUpload 核验并完成文件上传。
func (s *Service) CompleteFileUpload(ctx context.Context, meta RequestMeta, fileID string) (File, error) {
	return s.backend.CompleteFileUpload(ctx, meta, fileID)
}

// ChangePassword 核验当前密码并保存新密码。
func (s *Service) ChangePassword(ctx context.Context, meta RequestMeta, input ChangePasswordInput) error {
	return s.backend.ChangePassword(ctx, meta, input)
}

// UpdateUserWorkStatus 保存当前用户主动设置的工作状态。
func (s *Service) UpdateUserWorkStatus(ctx context.Context, meta RequestMeta, input UserWorkStatusInput) (CurrentUser, error) {
	return s.backend.UpdateUserWorkStatus(ctx, meta, input)
}

// LoadInbox 返回当前用户的统一收件箱。
func (s *Service) LoadInbox(ctx context.Context, meta RequestMeta, input LoadInboxInput) (Inbox, error) {
	return s.backend.LoadInbox(ctx, meta, input)
}

// ListCustomerServiceAssignees 返回有效真人和 AI 客服。
func (s *Service) ListCustomerServiceAssignees(ctx context.Context, meta RequestMeta) (CustomerServiceAssigneeList, error) {
	return s.backend.ListCustomerServiceAssignees(ctx, meta)
}

// ListConversationMessages 返回成员可见的会话消息。
func (s *Service) ListConversationMessages(ctx context.Context, meta RequestMeta, conversationID string, input ConversationMessageListInput) (ConversationMessageList, error) {
	return s.backend.ListConversationMessages(ctx, meta, conversationID, input)
}

// MarkConversationRead 单调推进当前用户的原生会话已读水位。
func (s *Service) MarkConversationRead(ctx context.Context, meta RequestMeta, conversationID string, input MarkConversationReadInput) (ConversationReadState, error) {
	return s.backend.MarkConversationRead(ctx, meta, conversationID, input)
}

// UpdateConversationNotificationSettings 保存当前用户的原生会话提醒设置。
func (s *Service) UpdateConversationNotificationSettings(ctx context.Context, meta RequestMeta, conversationID string, input ConversationNotificationSettingsInput) (ConversationNotificationSettings, error) {
	return s.backend.UpdateConversationNotificationSettings(ctx, meta, conversationID, input)
}

// SendCustomerTextMessage 发送客户会话文本消息。
func (s *Service) SendCustomerTextMessage(ctx context.Context, meta RequestMeta, conversationID string, input CustomerTextMessageInput) (ConversationMessage, error) {
	return s.backend.SendCustomerTextMessage(ctx, meta, conversationID, input)
}

// ClaimServiceSession 领取或接管客户会话最新处理周期。
func (s *Service) ClaimServiceSession(ctx context.Context, meta RequestMeta, conversationID string) (CustomerServiceSession, error) {
	return s.backend.ClaimServiceSession(ctx, meta, conversationID)
}

// TransferServiceSession 把当前负责的处理周期转给另一位客服。
func (s *Service) TransferServiceSession(ctx context.Context, meta RequestMeta, conversationID string, input TransferServiceSessionInput) (CustomerServiceSession, error) {
	return s.backend.TransferServiceSession(ctx, meta, conversationID, input)
}

// CloseServiceSession 关闭客户会话最新处理周期。
func (s *Service) CloseServiceSession(ctx context.Context, meta RequestMeta, conversationID string) (CustomerServiceSession, error) {
	return s.backend.CloseServiceSession(ctx, meta, conversationID)
}

// ReopenServiceSession 重新打开客户会话最新处理周期并分配给当前身份。
func (s *Service) ReopenServiceSession(ctx context.Context, meta RequestMeta, conversationID string) (CustomerServiceSession, error) {
	return s.backend.ReopenServiceSession(ctx, meta, conversationID)
}

// StartDirectConversation 发起或打开企业成员内部单聊。
func (s *Service) StartDirectConversation(ctx context.Context, meta RequestMeta, input DirectConversationInput) (InboxConversation, error) {
	return s.backend.StartDirectConversation(ctx, meta, input)
}

// SendDirectTextMessage 发送内部单聊文本消息。
func (s *Service) SendDirectTextMessage(ctx context.Context, meta RequestMeta, conversationID string, input DirectTextMessageInput) (ConversationMessage, error) {
	return s.backend.SendDirectTextMessage(ctx, meta, conversationID, input)
}

// CreateGroupConversation 创建企业内部群聊。
func (s *Service) CreateGroupConversation(ctx context.Context, meta RequestMeta, input GroupConversationInput) (InboxConversation, error) {
	return s.backend.CreateGroupConversation(ctx, meta, input)
}

// GetGroupConversation 返回当前成员可见的群聊资料。
func (s *Service) GetGroupConversation(ctx context.Context, meta RequestMeta, conversationID string) (GroupConversation, error) {
	return s.backend.GetGroupConversation(ctx, meta, conversationID)
}

// UpdateGroupConversation 修改群聊资料。
func (s *Service) UpdateGroupConversation(ctx context.Context, meta RequestMeta, conversationID string, input GroupConversationProfileInput) (GroupConversation, error) {
	return s.backend.UpdateGroupConversation(ctx, meta, conversationID, input)
}

// AddGroupConversationMembers 批量增加群聊成员。
func (s *Service) AddGroupConversationMembers(ctx context.Context, meta RequestMeta, conversationID string, input GroupConversationMembersInput) (GroupConversation, error) {
	return s.backend.AddGroupConversationMembers(ctx, meta, conversationID, input)
}

// RemoveGroupConversationMember 移除单个群聊成员。
func (s *Service) RemoveGroupConversationMember(ctx context.Context, meta RequestMeta, conversationID string, input GroupConversationMemberInput) (GroupConversation, error) {
	return s.backend.RemoveGroupConversationMember(ctx, meta, conversationID, input)
}

// TransferGroupConversationOwner 转让群主。
func (s *Service) TransferGroupConversationOwner(ctx context.Context, meta RequestMeta, conversationID string, input GroupConversationOwnerInput) (GroupConversation, error) {
	return s.backend.TransferGroupConversationOwner(ctx, meta, conversationID, input)
}

// LeaveGroupConversation 退出群聊并按需转让群主。
func (s *Service) LeaveGroupConversation(ctx context.Context, meta RequestMeta, conversationID string, input GroupConversationLeaveInput) error {
	return s.backend.LeaveGroupConversation(ctx, meta, conversationID, input)
}

// SendGroupTextMessage 发送企业内部群聊文本消息。
func (s *Service) SendGroupTextMessage(ctx context.Context, meta RequestMeta, conversationID string, input GroupTextMessageInput) (ConversationMessage, error) {
	return s.backend.SendGroupTextMessage(ctx, meta, conversationID, input)
}

// ListMessageChannels 返回消息渠道列表。
func (s *Service) ListMessageChannels(ctx context.Context, meta RequestMeta) (MessageChannelList, error) {
	return s.backend.ListMessageChannels(ctx, meta)
}

// GetWebsiteChannel 返回网站渠道详情。
func (s *Service) GetWebsiteChannel(ctx context.Context, meta RequestMeta, channelID string) (WebsiteChannel, error) {
	return s.backend.GetWebsiteChannel(ctx, meta, channelID)
}

// GetTelegramChannel 返回 Telegram 渠道详情。
func (s *Service) GetTelegramChannel(ctx context.Context, meta RequestMeta, channelID string) (TelegramChannel, error) {
	return s.backend.GetTelegramChannel(ctx, meta, channelID)
}

// TestTelegramChannelConnection 测试 Telegram 草稿 Token。
func (s *Service) TestTelegramChannelConnection(ctx context.Context, meta RequestMeta, channelID string, input TelegramChannelConnectionTestInput) error {
	return s.backend.TestTelegramChannelConnection(ctx, meta, channelID, input)
}

// SaveTelegramChannelConnection 保存 Telegram 机器人和 Webhook 设置。
func (s *Service) SaveTelegramChannelConnection(ctx context.Context, meta RequestMeta, channelID string, input TelegramChannelConnectionInput) (TelegramChannel, error) {
	return s.backend.SaveTelegramChannelConnection(ctx, meta, channelID, input)
}

// GetMessageChannel 返回消息渠道基础信息。
func (s *Service) GetMessageChannel(ctx context.Context, meta RequestMeta, channelID string) (MessageChannelSummary, error) {
	return s.backend.GetMessageChannel(ctx, meta, channelID)
}

// CreateMessageChannel 创建消息渠道。
func (s *Service) CreateMessageChannel(ctx context.Context, meta RequestMeta, input CreateMessageChannelInput) (MessageChannelSummary, error) {
	return s.backend.CreateMessageChannel(ctx, meta, input)
}

// UpdateMessageChannel 修改消息渠道基础信息。
func (s *Service) UpdateMessageChannel(ctx context.Context, meta RequestMeta, channelID string, input MessageChannelInput) (MessageChannelSummary, error) {
	return s.backend.UpdateMessageChannel(ctx, meta, channelID, input)
}

// UpdateWebsiteChannelChatInterface 修改网站渠道聊天界面。
func (s *Service) UpdateWebsiteChannelChatInterface(ctx context.Context, meta RequestMeta, channelID string, input WebsiteChannelChatInterfaceInput) (WebsiteChannelChatInterface, error) {
	return s.backend.UpdateWebsiteChannelChatInterface(ctx, meta, channelID, input)
}

// UpdateWebsiteChannelAccess 修改网站渠道允许使用的网站。
func (s *Service) UpdateWebsiteChannelAccess(ctx context.Context, meta RequestMeta, channelID string, input WebsiteChannelAccessInput) (WebsiteChannelAccess, error) {
	return s.backend.UpdateWebsiteChannelAccess(ctx, meta, channelID, input)
}

// DeactivateMessageChannel 停用消息渠道。
func (s *Service) DeactivateMessageChannel(ctx context.Context, meta RequestMeta, channelID string) (MessageChannelSummary, error) {
	return s.backend.DeactivateMessageChannel(ctx, meta, channelID)
}

// ActivateMessageChannel 启用消息渠道。
func (s *Service) ActivateMessageChannel(ctx context.Context, meta RequestMeta, channelID string) (MessageChannelSummary, error) {
	return s.backend.ActivateMessageChannel(ctx, meta, channelID)
}

// ListChannelOptions 返回当前企业的渠道选择项。
func (s *Service) ListChannelOptions(ctx context.Context, meta RequestMeta) (ChannelOptionList, error) {
	return s.backend.ListChannelOptions(ctx, meta)
}

// ListMemberOptions 返回可分配的企业成员和 AI 员工。
func (s *Service) ListMemberOptions(ctx context.Context, meta RequestMeta, input MemberOptionListInput) (MemberOptionList, error) {
	return s.backend.ListMemberOptions(ctx, meta, input)
}

// ListAgentModelOptions 返回 AI 员工可使用的对话模型。
func (s *Service) ListAgentModelOptions(ctx context.Context, meta RequestMeta) (AgentModelOptionList, error) {
	return s.backend.ListAgentModelOptions(ctx, meta)
}

// CreateAgent 创建企业 AI 员工。
func (s *Service) CreateAgent(ctx context.Context, meta RequestMeta, input CreateAgentInput) (Agent, error) {
	return s.backend.CreateAgent(ctx, meta, input)
}

// ListAgents 返回企业 AI 员工目录。
func (s *Service) ListAgents(ctx context.Context, meta RequestMeta, input AgentListInput) (AgentList, error) {
	return s.backend.ListAgents(ctx, meta, input)
}

// GetAgent 返回企业 AI 员工详情。
func (s *Service) GetAgent(ctx context.Context, meta RequestMeta, agentID string) (Agent, error) {
	return s.backend.GetAgent(ctx, meta, agentID)
}

// UpdateAgent 修改企业 AI 员工。
func (s *Service) UpdateAgent(ctx context.Context, meta RequestMeta, agentID string, input UpdateAgentInput) (Agent, error) {
	return s.backend.UpdateAgent(ctx, meta, agentID, input)
}

// UpdateAgentExecution 修改企业 AI 员工的执行配置。
func (s *Service) UpdateAgentExecution(ctx context.Context, meta RequestMeta, agentID string, input AgentExecutionInput) (Agent, error) {
	return s.backend.UpdateAgentExecution(ctx, meta, agentID, input)
}

// UpdateAgentWorkStatus 修改企业 AI 员工工作状态。
func (s *Service) UpdateAgentWorkStatus(ctx context.Context, meta RequestMeta, agentID string, input AgentWorkStatusInput) (Agent, error) {
	return s.backend.UpdateAgentWorkStatus(ctx, meta, agentID, input)
}

// DeactivateAgent 禁用企业 AI 员工账号。
func (s *Service) DeactivateAgent(ctx context.Context, meta RequestMeta, agentID string) (Agent, error) {
	return s.backend.DeactivateAgent(ctx, meta, agentID)
}

// ReactivateAgent 恢复企业 AI 员工。
func (s *Service) ReactivateAgent(ctx context.Context, meta RequestMeta, agentID string) (Agent, error) {
	return s.backend.ReactivateAgent(ctx, meta, agentID)
}

// ListUsers 返回企业成员列表。
func (s *Service) ListUsers(ctx context.Context, meta RequestMeta, input UserListInput) (UserList, error) {
	return s.backend.ListUsers(ctx, meta, input)
}

// GetUser 返回企业成员详情。
func (s *Service) GetUser(ctx context.Context, meta RequestMeta, userID string) (User, error) {
	return s.backend.GetUser(ctx, meta, userID)
}

// CreateUser 创建企业成员账号。
func (s *Service) CreateUser(ctx context.Context, meta RequestMeta, input CreateUserInput) (User, error) {
	return s.backend.CreateUser(ctx, meta, input)
}

// UpdateUser 修改企业成员资料、角色和所属团队。
func (s *Service) UpdateUser(ctx context.Context, meta RequestMeta, userID string, input UpdateUserInput) (User, error) {
	return s.backend.UpdateUser(ctx, meta, userID, input)
}

// UpdateRoleAssignments 在一个事务中批量调整真人和 AI 员工角色。
func (s *Service) UpdateRoleAssignments(ctx context.Context, meta RequestMeta, input RoleAssignmentsInput) error {
	return s.backend.UpdateRoleAssignments(ctx, meta, input)
}

// DeactivateUser 禁用企业成员账号。
func (s *Service) DeactivateUser(ctx context.Context, meta RequestMeta, userID string) (User, error) {
	return s.backend.DeactivateUser(ctx, meta, userID)
}

// ReactivateUser 恢复企业成员账号。
func (s *Service) ReactivateUser(ctx context.Context, meta RequestMeta, userID string) (User, error) {
	return s.backend.ReactivateUser(ctx, meta, userID)
}

// ListTeams 返回企业团队列表。
func (s *Service) ListTeams(ctx context.Context, meta RequestMeta, input TeamListInput) (TeamList, error) {
	return s.backend.ListTeams(ctx, meta, input)
}

// CreateTeam 创建企业团队。
func (s *Service) CreateTeam(ctx context.Context, meta RequestMeta, input TeamInput) (Team, error) {
	return s.backend.CreateTeam(ctx, meta, input)
}

// UpdateTeam 修改企业团队。
func (s *Service) UpdateTeam(ctx context.Context, meta RequestMeta, teamID string, input TeamInput) (Team, error) {
	return s.backend.UpdateTeam(ctx, meta, teamID, input)
}

// DeleteTeam 删除企业团队及其成员关系。
func (s *Service) DeleteTeam(ctx context.Context, meta RequestMeta, teamID string) error {
	return s.backend.DeleteTeam(ctx, meta, teamID)
}

// ListTeamMembers 返回团队成员列表。
func (s *Service) ListTeamMembers(ctx context.Context, meta RequestMeta, teamID string, input TeamMemberListInput) (TeamMemberList, error) {
	return s.backend.ListTeamMembers(ctx, meta, teamID, input)
}

// ListTeamMemberCandidates 返回尚未加入团队的企业身份。
func (s *Service) ListTeamMemberCandidates(ctx context.Context, meta RequestMeta, teamID string, input TeamMemberCandidateInput) (TeamMemberCandidateList, error) {
	return s.backend.ListTeamMemberCandidates(ctx, meta, teamID, input)
}

// AddTeamMembers 将企业身份批量加入团队。
func (s *Service) AddTeamMembers(ctx context.Context, meta RequestMeta, teamID string, input TeamMemberInput) (Team, error) {
	return s.backend.AddTeamMembers(ctx, meta, teamID, input)
}

// RemoveTeamMembers 将企业身份批量移出团队。
func (s *Service) RemoveTeamMembers(ctx context.Context, meta RequestMeta, teamID string, input TeamMemberInput) (Team, error) {
	return s.backend.RemoveTeamMembers(ctx, meta, teamID, input)
}

// ListKnowledgeBases 返回当前企业的知识库列表。
func (s *Service) ListKnowledgeBases(ctx context.Context, meta RequestMeta) (KnowledgeBaseList, error) {
	return s.backend.ListKnowledgeBases(ctx, meta)
}

// ListExternalKnowledgeBaseOptions 返回指定连接可访问的外部知识库选项。
func (s *Service) ListExternalKnowledgeBaseOptions(ctx context.Context, meta RequestMeta, connectionID string) (ExternalKnowledgeBaseOptionList, error) {
	return s.backend.ListExternalKnowledgeBaseOptions(ctx, meta, connectionID)
}

// ListKnowledgeDocuments 返回指定外部知识库的文档列表。
func (s *Service) ListKnowledgeDocuments(ctx context.Context, meta RequestMeta, knowledgeBaseID string, input KnowledgeDocumentListInput) (KnowledgeDocumentList, error) {
	return s.backend.ListKnowledgeDocuments(ctx, meta, knowledgeBaseID, input)
}

// GetKnowledgeDocument 返回指定外部知识文档详情。
func (s *Service) GetKnowledgeDocument(ctx context.Context, meta RequestMeta, knowledgeBaseID string, documentID string) (KnowledgeDocument, error) {
	return s.backend.GetKnowledgeDocument(ctx, meta, knowledgeBaseID, documentID)
}

// ListKnowledgeDocumentSegments 返回指定外部知识文档的分段列表。
func (s *Service) ListKnowledgeDocumentSegments(ctx context.Context, meta RequestMeta, knowledgeBaseID string, documentID string, input KnowledgeDocumentSegmentListInput) (KnowledgeDocumentSegmentList, error) {
	return s.backend.ListKnowledgeDocumentSegments(ctx, meta, knowledgeBaseID, documentID, input)
}

// RetrieveKnowledgeBase 检索指定外部知识库。
func (s *Service) RetrieveKnowledgeBase(ctx context.Context, meta RequestMeta, knowledgeBaseID string, input KnowledgeRetrievalInput) (KnowledgeRetrievalResult, error) {
	return s.backend.RetrieveKnowledgeBase(ctx, meta, knowledgeBaseID, input)
}

// GetKnowledgeBase 返回当前企业中的知识库详情。
func (s *Service) GetKnowledgeBase(ctx context.Context, meta RequestMeta, knowledgeBaseID string) (KnowledgeBase, error) {
	return s.backend.GetKnowledgeBase(ctx, meta, knowledgeBaseID)
}

// CreateKnowledgeBase 创建企业知识库。
func (s *Service) CreateKnowledgeBase(ctx context.Context, meta RequestMeta, input KnowledgeBaseInput) (KnowledgeBase, error) {
	return s.backend.CreateKnowledgeBase(ctx, meta, input)
}

// UpdateKnowledgeBase 修改企业知识库。
func (s *Service) UpdateKnowledgeBase(ctx context.Context, meta RequestMeta, knowledgeBaseID string, input KnowledgeBaseInput) (KnowledgeBase, error) {
	return s.backend.UpdateKnowledgeBase(ctx, meta, knowledgeBaseID, input)
}

// DeleteKnowledgeBase 删除企业知识库。
func (s *Service) DeleteKnowledgeBase(ctx context.Context, meta RequestMeta, knowledgeBaseID string) error {
	return s.backend.DeleteKnowledgeBase(ctx, meta, knowledgeBaseID)
}

// CreateKnowledgeGroup 创建知识库分组。
func (s *Service) CreateKnowledgeGroup(ctx context.Context, meta RequestMeta, knowledgeBaseID string, input KnowledgeGroupInput) (KnowledgeBase, error) {
	return s.backend.CreateKnowledgeGroup(ctx, meta, knowledgeBaseID, input)
}

// UpdateKnowledgeGroup 修改知识库分组。
func (s *Service) UpdateKnowledgeGroup(ctx context.Context, meta RequestMeta, knowledgeBaseID string, groupID string, input KnowledgeGroupInput) (KnowledgeBase, error) {
	return s.backend.UpdateKnowledgeGroup(ctx, meta, knowledgeBaseID, groupID, input)
}

// DeleteKnowledgeGroup 删除不含子分组的知识库分组。
func (s *Service) DeleteKnowledgeGroup(ctx context.Context, meta RequestMeta, knowledgeBaseID string, groupID string) (KnowledgeBase, error) {
	return s.backend.DeleteKnowledgeGroup(ctx, meta, knowledgeBaseID, groupID)
}

// ListContacts 返回联系人列表。
func (s *Service) ListContacts(ctx context.Context, meta RequestMeta, input ContactListInput) (ContactList, error) {
	return s.backend.ListContacts(ctx, meta, input)
}

// GetContact 返回联系人详情。
func (s *Service) GetContact(ctx context.Context, meta RequestMeta, contactID string) (Contact, error) {
	return s.backend.GetContact(ctx, meta, contactID)
}

// CreateContact 创建联系人。
func (s *Service) CreateContact(ctx context.Context, meta RequestMeta, input ContactInput) (Contact, error) {
	return s.backend.CreateContact(ctx, meta, input)
}

// UpdateContact 修改联系人。
func (s *Service) UpdateContact(ctx context.Context, meta RequestMeta, contactID string, input ContactInput) (Contact, error) {
	return s.backend.UpdateContact(ctx, meta, contactID, input)
}

// DeleteContact 将联系人移入回收站。
func (s *Service) DeleteContact(ctx context.Context, meta RequestMeta, contactID string) error {
	return s.backend.DeleteContact(ctx, meta, contactID)
}

// RestoreContact 恢复联系人。
func (s *Service) RestoreContact(ctx context.Context, meta RequestMeta, contactID string) (Contact, error) {
	return s.backend.RestoreContact(ctx, meta, contactID)
}

// ListRoles 返回当前企业的角色和预定义权限目录。
func (s *Service) ListRoles(ctx context.Context, meta RequestMeta) (RoleList, error) {
	return s.backend.ListRoles(ctx, meta)
}

// GetRole 返回当前企业的角色详情。
func (s *Service) GetRole(ctx context.Context, meta RequestMeta, roleID string) (Role, error) {
	return s.backend.GetRole(ctx, meta, roleID)
}

// CreateRole 创建自定义角色。
func (s *Service) CreateRole(ctx context.Context, meta RequestMeta, input RoleInput) (Role, error) {
	return s.backend.CreateRole(ctx, meta, input)
}

// UpdateRole 修改角色信息和权限。
func (s *Service) UpdateRole(ctx context.Context, meta RequestMeta, roleID string, input RoleInput) (Role, error) {
	return s.backend.UpdateRole(ctx, meta, roleID, input)
}

// DeleteRole 删除自定义角色。
func (s *Service) DeleteRole(ctx context.Context, meta RequestMeta, roleID string) error {
	return s.backend.DeleteRole(ctx, meta, roleID)
}

// ListAIProviders 返回当前企业的模型服务供应商列表。
func (s *Service) ListAIProviders(ctx context.Context, meta RequestMeta) (AIProviderList, error) {
	return s.backend.ListAIProviders(ctx, meta)
}

// GetAIProvider 返回当前企业中的模型服务供应商详情。
func (s *Service) GetAIProvider(ctx context.Context, meta RequestMeta, providerID string) (AIProvider, error) {
	return s.backend.GetAIProvider(ctx, meta, providerID)
}

// ListAvailableAIModels 返回指定品牌的预设模型目录。
func (s *Service) ListAvailableAIModels(ctx context.Context, meta RequestMeta, brand AIProviderBrand) (AIProviderModelList, error) {
	return s.backend.ListAvailableAIModels(ctx, meta, brand)
}

// TestAIProviderConnection 测试模型服务供应商草稿配置。
func (s *Service) TestAIProviderConnection(ctx context.Context, meta RequestMeta, input AIProviderConnectionInput) error {
	return s.backend.TestAIProviderConnection(ctx, meta, input)
}

// CreateAIProvider 创建模型服务供应商。
func (s *Service) CreateAIProvider(ctx context.Context, meta RequestMeta, input AIProviderInput) (AIProvider, error) {
	return s.backend.CreateAIProvider(ctx, meta, input)
}

// UpdateAIProvider 修改模型服务供应商。
func (s *Service) UpdateAIProvider(ctx context.Context, meta RequestMeta, providerID string, input AIProviderInput) (AIProvider, error) {
	return s.backend.UpdateAIProvider(ctx, meta, providerID, input)
}

// DeleteAIProvider 删除模型服务供应商。
func (s *Service) DeleteAIProvider(ctx context.Context, meta RequestMeta, providerID string) error {
	return s.backend.DeleteAIProvider(ctx, meta, providerID)
}

// ListBusinessSystems 返回当前企业配置的业务系统。
func (s *Service) ListBusinessSystems(ctx context.Context, meta RequestMeta) (BusinessSystemList, error) {
	return s.backend.ListBusinessSystems(ctx, meta)
}

// GetBusinessSystem 返回当前企业中的业务系统详情。
func (s *Service) GetBusinessSystem(ctx context.Context, meta RequestMeta, businessSystemID string) (BusinessSystem, error) {
	return s.backend.GetBusinessSystem(ctx, meta, businessSystemID)
}

// CreateBusinessSystem 创建业务系统。
func (s *Service) CreateBusinessSystem(ctx context.Context, meta RequestMeta, input BusinessSystemInput) (BusinessSystem, error) {
	return s.backend.CreateBusinessSystem(ctx, meta, input)
}

// UpdateBusinessSystem 修改业务系统。
func (s *Service) UpdateBusinessSystem(ctx context.Context, meta RequestMeta, businessSystemID string, input BusinessSystemInput) (BusinessSystem, error) {
	return s.backend.UpdateBusinessSystem(ctx, meta, businessSystemID, input)
}

// DeleteBusinessSystem 删除业务系统。
func (s *Service) DeleteBusinessSystem(ctx context.Context, meta RequestMeta, businessSystemID string) error {
	return s.backend.DeleteBusinessSystem(ctx, meta, businessSystemID)
}

// ListIntegrationConnections 返回当前企业的连接器列表。
func (s *Service) ListIntegrationConnections(ctx context.Context, meta RequestMeta) (IntegrationConnectionList, error) {
	return s.backend.ListIntegrationConnections(ctx, meta)
}

// GetIntegrationConnection 返回当前企业中的连接器详情。
func (s *Service) GetIntegrationConnection(ctx context.Context, meta RequestMeta, connectionID string) (IntegrationConnection, error) {
	return s.backend.GetIntegrationConnection(ctx, meta, connectionID)
}

// TestIntegrationConnection 测试连接器草稿配置。
func (s *Service) TestIntegrationConnection(ctx context.Context, meta RequestMeta, input IntegrationConnectionTestInput) error {
	return s.backend.TestIntegrationConnection(ctx, meta, input)
}

// CreateIntegrationConnection 创建外部系统连接器。
func (s *Service) CreateIntegrationConnection(ctx context.Context, meta RequestMeta, input IntegrationConnectionInput) (IntegrationConnection, error) {
	return s.backend.CreateIntegrationConnection(ctx, meta, input)
}

// UpdateIntegrationConnection 修改外部系统连接器。
func (s *Service) UpdateIntegrationConnection(ctx context.Context, meta RequestMeta, connectionID string, input IntegrationConnectionInput) (IntegrationConnection, error) {
	return s.backend.UpdateIntegrationConnection(ctx, meta, connectionID, input)
}

// DeleteIntegrationConnection 删除外部系统连接器。
func (s *Service) DeleteIntegrationConnection(ctx context.Context, meta RequestMeta, connectionID string) error {
	return s.backend.DeleteIntegrationConnection(ctx, meta, connectionID)
}

// UpdateOrganization 修改当前企业通用设置。
func (s *Service) UpdateOrganization(ctx context.Context, meta RequestMeta, input OrganizationInput) (Organization, error) {
	return s.backend.UpdateOrganization(ctx, meta, input)
}

// GetS3Setting 返回当前企业的对象存储设置。
func (s *Service) GetS3Setting(ctx context.Context, meta RequestMeta) (S3Setting, error) {
	return s.backend.GetS3Setting(ctx, meta)
}

// SaveS3Setting 保存当前企业的对象存储设置。
func (s *Service) SaveS3Setting(ctx context.Context, meta RequestMeta, input S3SettingInput) (S3Setting, error) {
	return s.backend.SaveS3Setting(ctx, meta, input)
}

// TestS3Setting 测试对象存储连接。
func (s *Service) TestS3Setting(ctx context.Context, meta RequestMeta, input S3SettingInput) error {
	return s.backend.TestS3Setting(ctx, meta, input)
}
