// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AIProvider 定义企业 AI 供应商及其模型目录。
 */
export interface AIProvider {
    "id": string;
    "brand": AIProviderBrand;
    "name": string;
    "apiKey": string;
    "apiUrl": string;
    "models": AIProviderModel[] | null;
}

/**
 * AIProviderBrand 表示 AI 供应商品牌。
 */
export enum AIProviderBrand {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AIProviderBrandDeepSeek = "deepseek",
};

/**
 * AIProviderInput 定义 AI 供应商可编辑字段。
 */
export interface AIProviderInput {
    "brand": AIProviderBrand;
    "name": string;
    "apiKey": string;
    "apiUrl": string;
    "models": AIProviderModel[] | null;
}

/**
 * AIProviderList 定义企业 AI 供应商列表。
 */
export interface AIProviderList {
    "providers": AIProviderSummary[] | null;
}

/**
 * AIProviderModel 定义 AI 供应商模型目录项。
 */
export interface AIProviderModel {
    "identifier": string;
    "name": string;
    "contextWindow": number;
    "maxOutputTokens": number;
}

/**
 * AIProviderModelList 定义指定品牌的可用模型目录。
 */
export interface AIProviderModelList {
    "models": AIProviderModel[] | null;
}

/**
 * AIProviderSummary 定义企业 AI 供应商列表项。
 */
export interface AIProviderSummary {
    "id": string;
    "brand": AIProviderBrand;
    "name": string;
    "apiUrl": string;
}

/**
 * Auth 包含登录身份和访问令牌。
 */
export interface Auth {
    "identity": Identity;
    "token": string;
    "expiresAt": string;
}

/**
 * ChangePasswordInput 定义当前用户修改密码所需字段。
 */
export interface ChangePasswordInput {
    "currentPassword": string;
    "newPassword": string;
}

/**
 * ChannelList 定义渠道选择项列表。
 */
export interface ChannelList {
    "channels": ChannelSummary[] | null;
}

/**
 * ChannelSummary 定义渠道选择项。
 */
export interface ChannelSummary {
    "id": string;
    "type": ChannelType;
    "name": string;
}

/**
 * ChannelType 表示渠道类型。
 */
export enum ChannelType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ChannelTypeWebsite = "website",
};

/**
 * Contact 定义联系人完整详情。
 */
export interface Contact {
    "contact": ContactRecord;
    "sourceChannel": ContactSourceChannel;
    "methods": ContactMethod[] | null;
    "channelIdentities": ContactChannelIdentity[] | null;
}

/**
 * ContactChannelIdentity 定义联系人渠道身份。
 */
export interface ContactChannelIdentity {
    "channelId": string;
    "channelName": string;
    "externalId": string;
    "displayName": string | null;
}

/**
 * ContactInput 定义联系人可编辑字段。
 */
export interface ContactInput {
    "displayName": string;
    "channelId": string;
    "stage": ContactStage;
    "notes": string;
    "methods": ContactMethodInput[] | null;
}

/**
 * ContactList 定义联系人分页结果。
 */
export interface ContactList {
    "contacts": ContactSummary[] | null;
    "page": PageInfo;
}

/**
 * ContactListInput 定义联系人列表查询条件。
 */
export interface ContactListInput {
    "query": string;
    "stage"?: ContactStage | null;
    "channelId": string;
    "methodType"?: ContactMethodType | null;
    "sort": ContactSort;
    "page": number;
    "pageSize": number;
    "deleted": boolean;
}

/**
 * ContactMethod 定义联系人联系方式。
 */
export interface ContactMethod {
    "type": ContactMethodType;
    "value": string;
    "label": string | null;
    "isPrimary": boolean;
}

/**
 * ContactMethodInput 定义联系人联系方式输入。
 */
export interface ContactMethodInput {
    "type": ContactMethodType;
    "value": string;
    "label": string;
    "isPrimary": boolean;
}

/**
 * ContactMethodType 表示联系人联系方式类型。
 */
export enum ContactMethodType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ContactMethodTypeEmail = "email",
    ContactMethodTypePhone = "phone",
};

/**
 * ContactRecord 定义联系人详情字段。
 */
export interface ContactRecord {
    "id": string;
    "sourceChannelId": string;
    "displayName": string | null;
    "stage": ContactStage;
    "notes": string | null;
    "createdAt": string;
}

/**
 * ContactSort 表示联系人列表排序方式。
 */
export enum ContactSort {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ContactSortUpdatedAtDescending = "updatedAt.desc",
    ContactSortCreatedAtDescending = "createdAt.desc",
    ContactSortDisplayNameAscending = "displayName.asc",
};

/**
 * ContactSourceChannel 定义联系人来源渠道。
 */
export interface ContactSourceChannel {
    "id": string;
    "type": ChannelType;
    "name": string;
}

/**
 * ContactStage 表示联系人阶段。
 */
export enum ContactStage {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ContactStageVisitor = "visitor",
    ContactStageLead = "lead",
    ContactStageCustomer = "customer",
};

/**
 * ContactSummary 定义联系人列表项。
 */
export interface ContactSummary {
    "id": string;
    "displayName": string | null;
    "stage": ContactStage;
    "primaryEmail": string | null;
    "primaryPhone": string | null;
    "sourceChannelName": string;
    "createdAt": string;
    "deletedAt": string | null;
}

/**
 * Conversation 定义收件箱中的会话。
 */
export interface Conversation {
    "id": string;
    "name": string;
    "initials": string;
    "channel": string;
    "preview": string;
    "time": string;
    "status": string;
    "unread"?: number;
    "online"?: boolean;
    "messages": Message[] | null;
}

/**
 * CreateUserInput 定义新增企业成员字段。
 */
export interface CreateUserInput {
    "displayName": string;
    "email": string;
    "password": string;
    "roleId": string;
    "teamIds": string[] | null;
}

/**
 * DirectoryUser 定义企业成员目录字段。
 */
export interface DirectoryUser {
    "id": string;
    "email": string;
    "displayName": string;
    "role": RoleSummary;
    "status": UserStatus;
    "workStatus": WorkStatus;
    "teams": TeamSummary[] | null;
    "createdAt": string;
}

/**
 * File 定义前端可使用的文件元数据。
 */
export interface File {
    "id": string;
    "name": string;
    "contentType": string;
    "byteSize": number;
    "contentUrl": string;
}

/**
 * FilePurpose 表示文件上传用途。
 */
export enum FilePurpose {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    FilePurposeUserAvatar = "user_avatar",
};

/**
 * FileUpload 包含待上传文件和内容上传请求。
 */
export interface FileUpload {
    "file": File;
    "request": FileUploadRequest;
}

/**
 * FileUploadInput 定义创建上传所需的文件元数据。
 */
export interface FileUploadInput {
    "purpose": FilePurpose;
    "fileName": string;
    "contentType": string;
    "byteSize": number;
}

/**
 * FileUploadRequest 定义客户端上传文件内容所需的 HTTP 请求。
 */
export interface FileUploadRequest {
    "method": string;
    "url": string;
    "headers": { [_ in string]?: string } | null;
}

/**
 * Identity 定义当前用户及其所属企业。
 */
export interface Identity {
    "organization": Organization;
    "user": User;
}

/**
 * Inbox 定义统一收件箱结果。
 */
export interface Inbox {
    "organization": Organization;
    "user": User;
    "conversations": Conversation[] | null;
}

/**
 * InstallWorkspaceInput 定义企业初始化输入。
 */
export interface InstallWorkspaceInput {
    "organizationName": string;
    "displayName": string;
    "email": string;
    "password": string;
    "locale": Locale;
    "timeZone": string;
}

/**
 * InstallationStatus 定义企业初始化状态和公开企业名称。
 */
export interface InstallationStatus {
    "installed": boolean;
    "organizationName": string;
}

/**
 * Locale 表示应用支持的本地化语言。
 */
export enum Locale {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LocaleChineseSimplified = "zh-CN",
    LocaleEnglishUnitedStates = "en-US",
};

/**
 * LoginInput 定义登录输入。
 */
export interface LoginInput {
    "email": string;
    "password": string;
}

/**
 * MemberIdentityType 表示可以加入团队的一等身份类型。
 */
export enum MemberIdentityType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    MemberIdentityTypeUser = "user",
    MemberIdentityTypeAgent = "agent",
};

/**
 * Message 定义收件箱会话中的消息。
 */
export interface Message {
    "id": string;
    "author": MessageAuthor;
    "text": string;
    "time": string;
}

/**
 * MessageAuthor 表示消息发送方。
 */
export enum MessageAuthor {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    MessageAuthorVisitor = "visitor",
    MessageAuthorAgent = "agent",
};

/**
 * Organization 定义当前企业信息。
 */
export interface Organization {
    "id": string;
    "name": string;
}

/**
 * OrganizationInput 定义企业名称修改输入。
 */
export interface OrganizationInput {
    "name": string;
}

/**
 * PageInfo 定义分页信息。
 */
export interface PageInfo {
    "number": number;
    "size": number;
    "total": number;
}

/**
 * PermissionCode 表示一项预定义权限。
 */
export enum PermissionCode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PermissionExternalContactsView = "external_contacts.view",
    PermissionExternalContactsManage = "external_contacts.manage",
    PermissionTeamMembersView = "team_members.view",
    PermissionTeamMembersManage = "team_members.manage",
    PermissionChannelsView = "channels.view",
    PermissionChannelsManage = "channels.manage",
    PermissionRolesView = "roles.view",
    PermissionRolesManage = "roles.manage",
    PermissionOrganizationView = "organization.view",
    PermissionOrganizationManage = "organization.manage",
    PermissionStorageView = "storage.view",
    PermissionStorageManage = "storage.manage",
};

/**
 * PermissionDefinition 定义权限目录中的一项权限。
 */
export interface PermissionDefinition {
    "code": PermissionCode;
    "resource": PermissionResource;
    "level": PermissionLevel;
}

/**
 * PermissionLevel 表示权限操作层级。
 */
export enum PermissionLevel {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PermissionLevelView = "view",
    PermissionLevelManage = "manage",
};

/**
 * PermissionResource 表示权限所属功能。
 */
export enum PermissionResource {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PermissionResourceExternalContacts = "external_contacts",
    PermissionResourceTeamMembers = "team_members",
    PermissionResourceChannels = "channels",
    PermissionResourceRoles = "roles",
    PermissionResourceOrganization = "organization",
    PermissionResourceStorage = "storage",
};

/**
 * ProfileImageFile 定义原生端选择的用户头像文件。
 */
export interface ProfileImageFile {
    "name": string;
    "contentType": string;
    "dataBase64": string;
}

/**
 * ProfileInput 定义当前用户可编辑的个人资料字段。
 */
export interface ProfileInput {
    "displayName": string;
    "email": string;
    "avatarFileId": string;
}

/**
 * RequestMeta 携带一次应用服务调用的认证和本地化信息。
 */
export interface RequestMeta {
    "token": string;
    "locale": Locale;
}

/**
 * Role 定义企业角色及其权限。
 */
export interface Role {
    "id": string;
    "kind": RoleKind;
    "name": string;
    "description": string;
    "permissions": PermissionCode[] | null;
    "memberCount": number;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * RoleInput 定义角色可编辑字段。
 */
export interface RoleInput {
    "name": string;
    "description": string;
    "permissions": PermissionCode[] | null;
}

/**
 * RoleKind 表示角色类型。
 */
export enum RoleKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RoleKindAdmin = "admin",
    RoleKindCustomerService = "customer_service",
    RoleKindMember = "member",
    RoleKindCustom = "custom",
};

/**
 * RoleList 定义角色、数量上限和权限目录。
 */
export interface RoleList {
    "roles": Role[] | null;
    "permissions": PermissionDefinition[] | null;
    "maximum": number;
}

/**
 * RoleSummary 定义成员关联角色的精简字段。
 */
export interface RoleSummary {
    "id": string;
    "kind": RoleKind;
    "name": string;
}

/**
 * S3Setting 定义 S3 兼容对象存储配置。
 */
export interface S3Setting {
    "enabled": boolean;
    "provider": StorageProvider;
    "endpoint": string;
    "region": string;
    "bucket": string;
    "accessKeyId": string;
    "secretAccessKey": string;
    "forcePathStyle": boolean;
}

/**
 * Session 表示当前会话。
 */
export interface Session {
    "state": SessionState;
    "identity"?: Identity | null;
    "organizationName"?: string;
}

/**
 * SessionState 表示会话入口。
 */
export enum SessionState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SessionStateReady = "ready",
    SessionStateLogin = "login",
    SessionStateSetup = "setup",
    SessionStateConnect = "connect",
};

/**
 * StorageProvider 表示 S3 兼容对象存储提供商。
 */
export enum StorageProvider {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StorageProviderGeneric = "generic",
    StorageProviderAWS = "aws",
    StorageProviderR2 = "r2",
    StorageProviderAliyun = "aliyun",
    StorageProviderTencent = "tencent",
    StorageProviderBaidu = "baidu",
    StorageProviderQiniu = "qiniu",
    StorageProviderHuawei = "huawei",
    StorageProviderUCloud = "ucloud",
    StorageProviderMinIO = "minio",
    StorageProviderRustFS = "rustfs",
};

/**
 * Team 定义团队详情。
 */
export interface Team {
    "id": string;
    "name": string;
    "description": string;
    "memberCount": number;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * TeamInput 定义团队可编辑字段。
 */
export interface TeamInput {
    "name": string;
    "description": string;
}

/**
 * TeamList 定义团队分页结果。
 */
export interface TeamList {
    "teams": Team[] | null;
    "page": PageInfo;
}

/**
 * TeamListInput 定义团队列表查询条件。
 */
export interface TeamListInput {
    "query": string;
    "page": number;
    "pageSize": number;
}

/**
 * TeamSummary 定义团队选择项和成员所属团队字段。
 */
export interface TeamSummary {
    "id": string;
    "name": string;
}

/**
 * UpdateDirectoryUserInput 定义企业成员可编辑字段。
 */
export interface UpdateDirectoryUserInput {
    "displayName": string;
    "email": string;
    "roleId": string;
    "teamIds": string[] | null;
}

/**
 * User 定义当前企业成员信息。
 */
export interface User {
    "id": string;
    "organizationId": string;
    "email": string;
    "displayName": string;
    "roleId": string;
    "status": UserStatus;
    "locale": Locale;
    "timeZone": string;
    "workStatus": WorkStatus;
    "avatarUrl": string;
}

/**
 * UserList 定义企业成员分页结果。
 */
export interface UserList {
    "users": DirectoryUser[] | null;
    "page": PageInfo;
}

/**
 * UserListInput 定义企业成员列表查询条件。
 */
export interface UserListInput {
    "query": string;
    "status"?: UserStatus | null;
    "roleId": string;
    "teamId": string;
    "page": number;
    "pageSize": number;
}

/**
 * UserPreferencesInput 定义当前用户的语言和时区设置。
 */
export interface UserPreferencesInput {
    "locale": Locale;
    "timeZone": string;
}

/**
 * UserStatus 表示企业成员状态。
 */
export enum UserStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    UserStatusActive = "active",
    UserStatusInactive = "inactive",
};

/**
 * UserWorkStatusInput 定义当前用户主动设置的工作状态。
 */
export interface UserWorkStatusInput {
    "workStatus": WorkStatus;
}

/**
 * WebsiteChannel 定义网站渠道详情。
 */
export interface WebsiteChannel {
    "id": string;
    "organizationId": string;
    "createdByUserId": string;
    "type": ChannelType;
    "name": string;
    "description": string | null;
    "defaultLocale": Locale;
    "createdAt": string;
    "updatedAt": string;
    "deletedAt": string | null;
    "chatInterface": WebsiteChannelChatInterface;
}

/**
 * WebsiteChannelChatInterface 定义网站渠道访客界面设置。
 */
export interface WebsiteChannelChatInterface {
    "title": string;
    "subtitle": string | null;
    "greetingMessage": string | null;
    "themeColor": string;
}

/**
 * WebsiteChannelChatInterfaceInput 定义网站渠道访客界面输入。
 */
export interface WebsiteChannelChatInterfaceInput {
    "title": string;
    "subtitle": string;
    "greetingMessage": string;
    "themeColor": string;
}

/**
 * WebsiteChannelInput 定义网站渠道可编辑字段。
 */
export interface WebsiteChannelInput {
    "name": string;
    "description": string;
    "defaultLocale": Locale;
}

/**
 * WebsiteChannelList 定义网站渠道列表。
 */
export interface WebsiteChannelList {
    "channels": WebsiteChannelSummary[] | null;
}

/**
 * WebsiteChannelSummary 定义网站渠道列表项。
 */
export interface WebsiteChannelSummary {
    "id": string;
    "organizationId": string;
    "createdByUserId": string;
    "type": ChannelType;
    "name": string;
    "description": string | null;
    "defaultLocale": Locale;
    "createdAt": string;
    "updatedAt": string;
    "deletedAt": string | null;
}

/**
 * WorkStatus 表示成员主动设置的工作状态。
 */
export enum WorkStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    WorkStatusWorking = "working",
    WorkStatusAway = "away",
    WorkStatusOffDuty = "off_duty",
};
