// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AIModelInputModality 表示模型支持的输入模态。
 */
export enum AIModelInputModality {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AIModelInputModalityText = "text",
    AIModelInputModalityImage = "image",
    AIModelInputModalityAudio = "audio",
    AIModelInputModalityVideo = "video",
};

/**
 * AIModelType 表示 AI 模型用途。
 */
export enum AIModelType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AIModelTypeChat = "chat",
    AIModelTypeEmbedding = "embedding",
    AIModelTypeRerank = "rerank",
};

/**
 * AIProvider 定义企业模型服务供应商及其模型目录。
 */
export interface AIProvider {
    "id": string;
    "brand": AIProviderBrand;
    "name": string;
    "apiKey": string;
    "apiUrl": string;
    "models": AIProviderModel[] | null;
}

/**
 * AIProviderBrand 表示模型服务供应商品牌。
 */
export enum AIProviderBrand {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AIProviderBrandDeepSeek = "deepseek",
    AIProviderBrandAlibaba = "alibaba",
    AIProviderBrandOpenAI = "openai",
};

/**
 * AIProviderInput 定义模型服务供应商可编辑字段。
 */
export interface AIProviderInput {
    "brand": AIProviderBrand;
    "name": string;
    "apiKey": string;
    "apiUrl": string;
    "models": AIProviderModel[] | null;
}

/**
 * AIProviderList 定义模型服务供应商列表。
 */
export interface AIProviderList {
    "providers": AIProviderSummary[] | null;
}

/**
 * AIProviderModel 定义模型服务供应商的模型目录项。
 */
export interface AIProviderModel {
    "identifier": string;
    "name": string;
    "type": AIModelType;
    "inputModalities": AIModelInputModality[] | null;
    "contextWindow": number;
    "maxOutputTokens": number;
}

/**
 * AIProviderModelList 定义指定品牌的预设模型目录。
 */
export interface AIProviderModelList {
    "models": AIProviderModel[] | null;
}

/**
 * AIProviderModelSummary 定义供应商列表中的模型目录摘要。
 */
export interface AIProviderModelSummary {
    "identifier": string;
    "name": string;
    "type": AIModelType;
}

/**
 * AIProviderSummary 定义模型服务供应商列表项。
 */
export interface AIProviderSummary {
    "id": string;
    "brand": AIProviderBrand;
    "name": string;
    "apiUrl": string;
    "models": AIProviderModelSummary[] | null;
}

/**
 * Agent 定义 AI 员工信息。
 */
export interface Agent {
    "id": string;
    "identityId": string;
    "displayName": string;
    "status": UserStatus;
    "workStatus": WorkStatus;
    "teams": TeamSummary[] | null;
    "capability": AgentCapability;
    "createdAt": string;
}

/**
 * AgentCapability 定义 AI 员工当前生效的能力配置。
 */
export interface AgentCapability {
    "providerId": string;
    "providerName": string;
    "modelIdentifier": string;
    "modelName": string;
    "systemInstruction": string;
}

/**
 * AgentCapabilityInput 定义 AI 员工能力配置字段。
 */
export interface AgentCapabilityInput {
    "providerId": string;
    "modelIdentifier": string;
    "systemInstruction": string;
}

/**
 * AgentCapabilitySummary 定义 AI 员工当前模型摘要。
 */
export interface AgentCapabilitySummary {
    "providerId": string;
    "providerName": string;
    "modelIdentifier": string;
    "modelName": string;
}

/**
 * AgentList 定义 AI 员工分页结果。
 */
export interface AgentList {
    "agents": AgentListItem[] | null;
    "page": PageInfo;
}

/**
 * AgentListInput 定义 AI 员工目录查询条件。
 */
export interface AgentListInput {
    "query": string;
    "status"?: UserStatus | null;
    "page": number;
    "pageSize": number;
}

/**
 * AgentListItem 定义 AI 员工目录项。
 */
export interface AgentListItem {
    "id": string;
    "identityId": string;
    "displayName": string;
    "status": UserStatus;
    "workStatus": WorkStatus;
    "teams": TeamSummary[] | null;
    "capability": AgentCapabilitySummary;
    "createdAt": string;
}

/**
 * AgentModelOption 定义 AI 员工可使用的对话模型选项。
 */
export interface AgentModelOption {
    "providerId": string;
    "providerName": string;
    "modelIdentifier": string;
    "modelName": string;
}

/**
 * AgentModelOptionList 定义 AI 员工对话模型选项列表。
 */
export interface AgentModelOptionList {
    "models": AgentModelOption[] | null;
}

/**
 * AgentWorkStatusInput 定义 AI 员工工作状态修改字段。
 */
export interface AgentWorkStatusInput {
    "workStatus": WorkStatus;
}

/**
 * Auth 包含登录身份和访问令牌。
 */
export interface Auth {
    "identity": Identity;
    "token": string;
    "expiresAt": string;
}

/**
 * ChangePasswordInput 定义当前用户修改密码所需字段。
 */
export interface ChangePasswordInput {
    "currentPassword": string;
    "newPassword": string;
}

/**
 * ChannelOption 定义渠道选择项。
 */
export interface ChannelOption {
    "id": string;
    "type": ChannelType;
    "name": string;
}

/**
 * ChannelOptionList 定义渠道选择项列表。
 */
export interface ChannelOptionList {
    "channels": ChannelOption[] | null;
}

/**
 * ChannelRoutingTarget 定义渠道会话流转目标。
 */
export interface ChannelRoutingTarget {
    "type": ChannelRoutingTargetType;
    "id": string;
}

/**
 * ChannelRoutingTargetType 表示渠道会话流转目标类型。
 */
export enum ChannelRoutingTargetType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ChannelRoutingTargetTypePublicQueue = "public_queue",
    ChannelRoutingTargetTypeTeam = "team",
    ChannelRoutingTargetTypeMember = "member",
};

/**
 * ChannelType 表示渠道类型。
 */
export enum ChannelType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ChannelTypeWebsite = "website",
    ChannelTypeTelegram = "telegram",
    ChannelTypeWeChatOfficialAccount = "wechat_official_account",
};

/**
 * Contact 定义联系人完整详情。
 */
export interface Contact {
    "contact": ContactRecord;
    "sourceChannel": ContactSourceChannel;
    "methods": ContactMethod[] | null;
    "channelIdentities": ContactChannelIdentity[] | null;
}

/**
 * ContactChannelIdentity 定义联系人渠道身份。
 */
export interface ContactChannelIdentity {
    "channelId": string;
    "channelName": string;
    "externalId": string;
    "displayName": string | null;
}

/**
 * ContactInput 定义联系人可编辑字段。
 */
export interface ContactInput {
    "displayName": string;
    "channelId": string;
    "stage": ContactStage;
    "notes": string;
    "methods": ContactMethodInput[] | null;
}

/**
 * ContactList 定义联系人分页结果。
 */
export interface ContactList {
    "contacts": ContactSummary[] | null;
    "page": PageInfo;
}

/**
 * ContactListInput 定义联系人列表查询条件。
 */
export interface ContactListInput {
    "query": string;
    "stage"?: ContactStage | null;
    "channelId": string;
    "methodType"?: ContactMethodType | null;
    "sort": ContactSort;
    "page": number;
    "pageSize": number;
    "deleted": boolean;
}

/**
 * ContactMethod 定义联系人联系方式。
 */
export interface ContactMethod {
    "type": ContactMethodType;
    "value": string;
    "label": string | null;
    "isPrimary": boolean;
}

/**
 * ContactMethodInput 定义联系人联系方式输入。
 */
export interface ContactMethodInput {
    "type": ContactMethodType;
    "value": string;
    "label": string;
    "isPrimary": boolean;
}

/**
 * ContactMethodType 表示联系人联系方式类型。
 */
export enum ContactMethodType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ContactMethodTypeEmail = "email",
    ContactMethodTypePhone = "phone",
};

/**
 * ContactRecord 定义联系人详情字段。
 */
export interface ContactRecord {
    "id": string;
    "sourceChannelId": string;
    "displayName": string | null;
    "stage": ContactStage;
    "notes": string | null;
    "createdAt": string;
}

/**
 * ContactSort 表示联系人列表排序方式。
 */
export enum ContactSort {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ContactSortUpdatedAtDescending = "updatedAt.desc",
    ContactSortCreatedAtDescending = "createdAt.desc",
    ContactSortDisplayNameAscending = "displayName.asc",
};

/**
 * ContactSourceChannel 定义联系人来源渠道。
 */
export interface ContactSourceChannel {
    "id": string;
    "type": ChannelType;
    "name": string;
}

/**
 * ContactStage 表示联系人阶段。
 */
export enum ContactStage {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ContactStageVisitor = "visitor",
    ContactStageLead = "lead",
    ContactStageCustomer = "customer",
};

/**
 * ContactSummary 定义联系人列表项。
 */
export interface ContactSummary {
    "id": string;
    "displayName": string | null;
    "stage": ContactStage;
    "primaryEmail": string | null;
    "primaryPhone": string | null;
    "sourceChannelName": string;
    "createdAt": string;
    "deletedAt": string | null;
}

/**
 * Conversation 定义收件箱中的会话。
 */
export interface Conversation {
    "id": string;
    "name": string;
    "initials": string;
    "channel": string;
    "preview": string;
    "time": string;
    "status": string;
    "unread"?: number;
    "online"?: boolean;
    "messages": Message[] | null;
}

/**
 * CreateAgentInput 定义新增 AI 员工字段。
 */
export interface CreateAgentInput {
    "displayName": string;
    "teamIds": string[] | null;
    "capability": AgentCapabilityInput;
}

/**
 * CreateMessageChannelInput 定义创建消息渠道所需字段。
 */
export interface CreateMessageChannelInput {
    "name": string;
    "description": string;
    "defaultLocale": Locale;
    "newConversationTarget": ChannelRoutingTarget;
    "fallbackTarget": ChannelRoutingTarget;
    "type": ChannelType;
}

/**
 * CreateUserInput 定义新增企业成员字段。
 */
export interface CreateUserInput {
    "displayName": string;
    "email": string;
    "password": string;
    "roleId": string;
    "teamIds": string[] | null;
}

/**
 * CurrentUser 定义当前登录用户信息。
 */
export interface CurrentUser {
    "id": string;
    "identityId": string;
    "organizationId": string;
    "email": string;
    "displayName": string;
    "roleId": string;
    "status": UserStatus;
    "locale": Locale;
    "timeZone": string;
    "messageNotificationsEnabled": boolean;
    "workStatus": WorkStatus;
    "avatarUrl": string;
}

/**
 * File 定义前端可使用的文件元数据。
 */
export interface File {
    "id": string;
    "name": string;
    "contentType": string;
    "byteSize": number;
    "contentUrl": string;
}

/**
 * FilePurpose 表示文件上传用途。
 */
export enum FilePurpose {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    FilePurposeUserAvatar = "user_avatar",
};

/**
 * FileUpload 包含待上传文件和内容上传请求。
 */
export interface FileUpload {
    "file": File;
    "request": FileUploadRequest;
}

/**
 * FileUploadInput 定义创建上传所需的文件元数据。
 */
export interface FileUploadInput {
    "purpose": FilePurpose;
    "fileName": string;
    "contentType": string;
    "byteSize": number;
}

/**
 * FileUploadRequest 定义客户端上传文件内容所需的 HTTP 请求。
 */
export interface FileUploadRequest {
    "method": string;
    "url": string;
    "headers": { [_ in string]?: string } | null;
}

/**
 * Identity 定义当前用户及其所属企业。
 */
export interface Identity {
    "organization": Organization;
    "user": CurrentUser;
}

/**
 * Inbox 定义统一收件箱结果。
 */
export interface Inbox {
    "organization": Organization;
    "user": CurrentUser;
    "conversations": Conversation[] | null;
}

/**
 * InstallWorkspaceInput 定义企业初始化输入。
 */
export interface InstallWorkspaceInput {
    "organizationName": string;
    "displayName": string;
    "email": string;
    "password": string;
    "locale": Locale;
    "timeZone": string;
}

/**
 * InstallationStatus 定义企业初始化状态和公开企业名称。
 */
export interface InstallationStatus {
    "installed": boolean;
    "organizationName": string;
}

/**
 * KnowledgeBase 定义知识库详情。
 */
export interface KnowledgeBase {
    "id": string;
    "name": string;
    "category": KnowledgeBaseCategory;
    "description": string;
    "integrationConnectionId": string;
    "externalResourceId": string;
    "groups": KnowledgeGroup[] | null;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * KnowledgeBaseCategory 表示知识库类型。
 */
export enum KnowledgeBaseCategory {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    KnowledgeBaseCategoryStandard = "standard",
    KnowledgeBaseCategoryQA = "qa",
};

/**
 * KnowledgeBaseInput 定义知识库可编辑字段。
 */
export interface KnowledgeBaseInput {
    "name": string;
    "category": KnowledgeBaseCategory;
    "description": string;
    "integrationConnectionId": string;
    "externalResourceId": string;
}

/**
 * KnowledgeBaseList 定义知识库列表。
 */
export interface KnowledgeBaseList {
    "knowledgeBases": KnowledgeBase[] | null;
}

/**
 * KnowledgeGroup 定义知识库分组树节点。
 */
export interface KnowledgeGroup {
    "id": string;
    "parentId": string;
    "name": string;
    "isDefault": boolean;
    "children": KnowledgeGroup[] | null;
}

/**
 * KnowledgeGroupInput 定义知识库分组可编辑字段。
 */
export interface KnowledgeGroupInput {
    "name": string;
    "parentId": string;
}

/**
 * Locale 表示应用支持的本地化语言。
 */
export enum Locale {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LocaleChineseSimplified = "zh-CN",
    LocaleEnglishUnitedStates = "en-US",
};

/**
 * LoginInput 定义登录输入。
 */
export interface LoginInput {
    "email": string;
    "password": string;
}

/**
 * MemberOption 定义可分配的企业身份选择项。
 */
export interface MemberOption {
    "id": string;
    "type": OrganizationIdentityType;
    "displayName": string;
    "avatarUrl": string;
}

/**
 * MemberOptionList 定义企业身份选择项分页结果。
 */
export interface MemberOptionList {
    "members": MemberOption[] | null;
    "page": PageInfo;
}

/**
 * MemberOptionListInput 定义企业身份选择项查询条件。
 */
export interface MemberOptionListInput {
    "query": string;
    "page": number;
    "pageSize": number;
}

/**
 * Message 定义收件箱会话中的消息。
 */
export interface Message {
    "id": string;
    "author": MessageAuthor;
    "text": string;
    "time": string;
}

/**
 * MessageAuthor 表示消息发送方。
 */
export enum MessageAuthor {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    MessageAuthorVisitor = "visitor",
    MessageAuthorAgent = "agent",
};

/**
 * MessageChannelInput 定义消息渠道可编辑的通用字段。
 */
export interface MessageChannelInput {
    "name": string;
    "description": string;
    "defaultLocale": Locale;
    "newConversationTarget": ChannelRoutingTarget;
    "fallbackTarget": ChannelRoutingTarget;
}

/**
 * MessageChannelList 定义消息渠道列表。
 */
export interface MessageChannelList {
    "channels": MessageChannelSummary[] | null;
}

/**
 * MessageChannelSummary 定义消息渠道列表项和基础信息。
 */
export interface MessageChannelSummary {
    "id": string;
    "organizationId": string;
    "createdByUserId": string;
    "type": ChannelType;
    "name": string;
    "description": string | null;
    "defaultLocale": Locale;
    "newConversationTarget": ChannelRoutingTarget;
    "fallbackTarget": ChannelRoutingTarget;
    "enabled": boolean;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * MessageNotificationInput 定义当前设备的新消息通知内容。
 */
export interface MessageNotificationInput {
    "id": string;
    "title": string;
    "body": string;
    "soundEnabled": boolean;
}

/**
 * NotificationPermissionStatus 表示当前设备的系统通知授权状态。
 */
export enum NotificationPermissionStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    NotificationPermissionStatusPrompt = "prompt",
    NotificationPermissionStatusGranted = "granted",
    NotificationPermissionStatusDenied = "denied",
    NotificationPermissionStatusUnsupported = "unsupported",
};

/**
 * Organization 定义当前企业信息。
 */
export interface Organization {
    "id": string;
    "name": string;
}

/**
 * OrganizationIdentityType 表示企业身份类型。
 */
export enum OrganizationIdentityType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    OrganizationIdentityTypeUser = "user",
    OrganizationIdentityTypeAgent = "agent",
};

/**
 * OrganizationInput 定义企业名称修改输入。
 */
export interface OrganizationInput {
    "name": string;
}

/**
 * PageInfo 定义分页信息。
 */
export interface PageInfo {
    "number": number;
    "size": number;
    "total": number;
}

/**
 * PermissionCode 表示一项预定义权限。
 */
export enum PermissionCode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PermissionExternalContactsView = "external_contacts.view",
    PermissionExternalContactsManage = "external_contacts.manage",
    PermissionTeamMembersView = "team_members.view",
    PermissionTeamMembersManage = "team_members.manage",
    PermissionChannelsView = "channels.view",
    PermissionChannelsManage = "channels.manage",
    PermissionRolesView = "roles.view",
    PermissionRolesManage = "roles.manage",
    PermissionOrganizationView = "organization.view",
    PermissionOrganizationManage = "organization.manage",
    PermissionStorageView = "storage.view",
    PermissionStorageManage = "storage.manage",
};

/**
 * PermissionDefinition 定义权限目录中的一项权限。
 */
export interface PermissionDefinition {
    "code": PermissionCode;
    "resource": PermissionResource;
    "level": PermissionLevel;
}

/**
 * PermissionLevel 表示权限操作层级。
 */
export enum PermissionLevel {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PermissionLevelView = "view",
    PermissionLevelManage = "manage",
};

/**
 * PermissionResource 表示权限所属功能。
 */
export enum PermissionResource {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PermissionResourceExternalContacts = "external_contacts",
    PermissionResourceTeamMembers = "team_members",
    PermissionResourceChannels = "channels",
    PermissionResourceRoles = "roles",
    PermissionResourceOrganization = "organization",
    PermissionResourceStorage = "storage",
};

/**
 * ProfileImageFile 定义原生端选择的用户头像文件。
 */
export interface ProfileImageFile {
    "name": string;
    "contentType": string;
    "dataBase64": string;
}

/**
 * ProfileInput 定义当前用户可编辑的个人资料字段。
 */
export interface ProfileInput {
    "displayName": string;
    "email": string;
    "avatarFileId": string;
}

/**
 * RequestMeta 携带一次应用服务调用的认证和本地化信息。
 */
export interface RequestMeta {
    "token": string;
    "locale": Locale;
}

/**
 * Role 定义企业角色及其权限。
 */
export interface Role {
    "id": string;
    "kind": RoleKind;
    "name": string;
    "description": string;
    "permissions": PermissionCode[] | null;
    "memberCount": number;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * RoleInput 定义角色可编辑字段。
 */
export interface RoleInput {
    "name": string;
    "description": string;
    "permissions": PermissionCode[] | null;
}

/**
 * RoleKind 表示角色类型。
 */
export enum RoleKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RoleKindAdmin = "admin",
    RoleKindCustomerService = "customer_service",
    RoleKindMember = "member",
    RoleKindCustom = "custom",
};

/**
 * RoleList 定义角色、数量上限和权限目录。
 */
export interface RoleList {
    "roles": Role[] | null;
    "permissions": PermissionDefinition[] | null;
    "maximum": number;
}

/**
 * RoleSummary 定义成员关联角色的精简字段。
 */
export interface RoleSummary {
    "id": string;
    "kind": RoleKind;
    "name": string;
}

/**
 * S3Setting 定义 S3 兼容对象存储配置。
 */
export interface S3Setting {
    "enabled": boolean;
    "provider": StorageProvider;
    "endpoint": string;
    "region": string;
    "bucket": string;
    "accessKeyId": string;
    "secretAccessKey": string;
    "forcePathStyle": boolean;
}

/**
 * SessionState 表示会话入口。
 */
export enum SessionState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SessionStateReady = "ready",
    SessionStateLogin = "login",
    SessionStateSetup = "setup",
    SessionStateConnect = "connect",
};

/**
 * Startup 表示应用启动入口和企业名称。
 */
export interface Startup {
    "state": SessionState;
    "organizationName"?: string;
}

/**
 * StorageProvider 表示 S3 兼容对象存储提供商。
 */
export enum StorageProvider {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StorageProviderGeneric = "generic",
    StorageProviderAWS = "aws",
    StorageProviderR2 = "r2",
    StorageProviderAliyun = "aliyun",
    StorageProviderTencent = "tencent",
    StorageProviderBaidu = "baidu",
    StorageProviderQiniu = "qiniu",
    StorageProviderHuawei = "huawei",
    StorageProviderUCloud = "ucloud",
    StorageProviderMinIO = "minio",
    StorageProviderRustFS = "rustfs",
};

/**
 * Team 定义团队详情。
 */
export interface Team {
    "id": string;
    "name": string;
    "description": string;
    "memberCount": number;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * TeamInput 定义团队可编辑字段。
 */
export interface TeamInput {
    "name": string;
    "description": string;
}

/**
 * TeamList 定义团队分页结果。
 */
export interface TeamList {
    "teams": Team[] | null;
    "page": PageInfo;
}

/**
 * TeamListInput 定义团队列表查询条件。
 */
export interface TeamListInput {
    "query": string;
    "page": number;
    "pageSize": number;
}

/**
 * TeamMember 定义团队成员信息。
 */
export interface TeamMember {
    "identityId": string;
    "identityType": OrganizationIdentityType;
    "displayName": string;
    "workStatus": WorkStatus;
    "joinedAt": string;
}

/**
 * TeamMemberCandidate 定义可加入团队的成员。
 */
export interface TeamMemberCandidate {
    "identityType": OrganizationIdentityType;
    "identityId": string;
    "displayName": string;
    "avatarUrl": string;
}

/**
 * TeamMemberCandidateInput 定义可加入团队的成员查询条件。
 */
export interface TeamMemberCandidateInput {
    "query": string;
    "page": number;
    "pageSize": number;
}

/**
 * TeamMemberCandidateList 定义可加入团队的成员分页结果。
 */
export interface TeamMemberCandidateList {
    "members": TeamMemberCandidate[] | null;
    "page": PageInfo;
}

/**
 * TeamMemberIdentityInput 定义要变更的团队成员身份。
 */
export interface TeamMemberIdentityInput {
    "identityType": OrganizationIdentityType;
    "identityId": string;
}

/**
 * TeamMemberInput 定义批量变更团队的身份列表。
 */
export interface TeamMemberInput {
    "members": TeamMemberIdentityInput[] | null;
}

/**
 * TeamMemberList 定义团队成员分页结果。
 */
export interface TeamMemberList {
    "members": TeamMember[] | null;
    "page": PageInfo;
}

/**
 * TeamMemberListInput 定义团队成员列表查询条件。
 */
export interface TeamMemberListInput {
    "query": string;
    "workStatus"?: WorkStatus | null;
    "page": number;
    "pageSize": number;
}

/**
 * TeamSummary 定义团队选择项和成员所属团队字段。
 */
export interface TeamSummary {
    "id": string;
    "name": string;
}

/**
 * UnreadIndicatorState 定义未读数量和托盘提醒条件。
 */
export interface UnreadIndicatorState {
    "count": number;
    "attentionEnabled": boolean;
    "attentionPending": boolean;
}

/**
 * UpdateAgentInput 定义 AI 员工可编辑字段。
 */
export interface UpdateAgentInput {
    "displayName": string;
    "teamIds": string[] | null;
}

/**
 * UpdateUserInput 定义企业成员可编辑字段。
 */
export interface UpdateUserInput {
    "displayName": string;
    "email": string;
    "roleId": string;
    "teamIds": string[] | null;
}

/**
 * User 定义企业成员信息。
 */
export interface User {
    "id": string;
    "identityId": string;
    "email": string;
    "displayName": string;
    "role": RoleSummary;
    "status": UserStatus;
    "workStatus": WorkStatus;
    "teams": TeamSummary[] | null;
    "createdAt": string;
}

/**
 * UserList 定义企业成员分页结果。
 */
export interface UserList {
    "users": User[] | null;
    "page": PageInfo;
}

/**
 * UserListInput 定义企业成员列表查询条件。
 */
export interface UserListInput {
    "query": string;
    "status"?: UserStatus | null;
    "roleId": string;
    "teamId": string;
    "page": number;
    "pageSize": number;
}

/**
 * UserPreferencesInput 定义当前用户的偏好设置。
 */
export interface UserPreferencesInput {
    "locale": Locale;
    "timeZone": string;
    "messageNotificationsEnabled": boolean;
}

/**
 * UserRoleChangeInput 定义一名企业成员的目标角色。
 */
export interface UserRoleChangeInput {
    "userId": string;
    "roleId": string;
}

/**
 * UserRoleChangesInput 定义一次批量角色调整。
 */
export interface UserRoleChangesInput {
    "changes": UserRoleChangeInput[] | null;
}

/**
 * UserStatus 表示用户账号或 AI 员工的账号状态。
 */
export enum UserStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    UserStatusActive = "active",
    UserStatusInactive = "inactive",
};

/**
 * UserWorkStatusInput 定义当前用户主动设置的工作状态。
 */
export interface UserWorkStatusInput {
    "workStatus": WorkStatus;
}

/**
 * WebsiteChannel 定义网站渠道详情。
 */
export interface WebsiteChannel {
    "id": string;
    "organizationId": string;
    "createdByUserId": string;
    "type": ChannelType;
    "name": string;
    "description": string | null;
    "defaultLocale": Locale;
    "newConversationTarget": ChannelRoutingTarget;
    "fallbackTarget": ChannelRoutingTarget;
    "enabled": boolean;
    "createdAt": string;
    "updatedAt": string;
    "chatInterface": WebsiteChannelChatInterface;
    "access": WebsiteChannelAccess;
}

/**
 * WebsiteChannelAccess 定义网站渠道允许使用的网站。
 */
export interface WebsiteChannelAccess {
    "allowedHosts": string[] | null;
}

/**
 * WebsiteChannelAccessInput 定义网站渠道允许使用的网站输入。
 */
export interface WebsiteChannelAccessInput {
    "allowedHosts": string[] | null;
}

/**
 * WebsiteChannelChatInterface 定义网站渠道访客界面设置。
 */
export interface WebsiteChannelChatInterface {
    "title": string;
    "subtitle": string | null;
    "greetingMessage": string | null;
    "themeColor": string;
}

/**
 * WebsiteChannelChatInterfaceInput 定义网站渠道访客界面输入。
 */
export interface WebsiteChannelChatInterfaceInput {
    "title": string;
    "subtitle": string;
    "greetingMessage": string;
    "themeColor": string;
}

/**
 * WorkStatus 表示企业身份主动设置的工作状态。
 */
export enum WorkStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    WorkStatusWorking = "working",
    WorkStatusAway = "away",
    WorkStatusOffDuty = "off_duty",
};
