// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service 将跨平台业务调用转发给当前运行平台的 Backend。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ChangePassword 核验当前密码并保存新密码。
 */
export function ChangePassword(meta: $models.RequestMeta, input: $models.ChangePasswordInput): $CancellablePromise<void> {
    return $Call.ByID(3645111243, meta, input);
}

/**
 * ConnectServer 保存并验证原生端企业服务器地址。
 */
export function ConnectServer(meta: $models.RequestMeta, serverURL: string): $CancellablePromise<void> {
    return $Call.ByID(1075777931, meta, serverURL);
}

/**
 * CreateContact 创建联系人。
 */
export function CreateContact(meta: $models.RequestMeta, input: $models.ContactInput): $CancellablePromise<$models.Contact> {
    return $Call.ByID(2172055030, meta, input);
}

/**
 * CreateWebsiteChannel 创建网站渠道。
 */
export function CreateWebsiteChannel(meta: $models.RequestMeta, input: $models.WebsiteChannelInput): $CancellablePromise<$models.WebsiteChannelSummary> {
    return $Call.ByID(372928498, meta, input);
}

/**
 * DeleteContact 将联系人移入回收站。
 */
export function DeleteContact(meta: $models.RequestMeta, contactID: string): $CancellablePromise<void> {
    return $Call.ByID(1228681067, meta, contactID);
}

/**
 * DeleteWebsiteChannel 将网站渠道移入回收站。
 */
export function DeleteWebsiteChannel(meta: $models.RequestMeta, channelID: string): $CancellablePromise<void> {
    return $Call.ByID(2696547045, meta, channelID);
}

/**
 * GetContact 返回联系人详情。
 */
export function GetContact(meta: $models.RequestMeta, contactID: string): $CancellablePromise<$models.Contact> {
    return $Call.ByID(1550866366, meta, contactID);
}

/**
 * GetS3Setting 返回当前企业的对象存储设置。
 */
export function GetS3Setting(meta: $models.RequestMeta): $CancellablePromise<$models.S3Setting> {
    return $Call.ByID(3937581736, meta);
}

/**
 * GetUser 返回企业成员详情。
 */
export function GetUser(meta: $models.RequestMeta, userID: string): $CancellablePromise<$models.DirectoryUser> {
    return $Call.ByID(1862601569, meta, userID);
}

/**
 * GetWebsiteChannel 返回网站渠道详情。
 */
export function GetWebsiteChannel(meta: $models.RequestMeta, channelID: string): $CancellablePromise<$models.WebsiteChannel> {
    return $Call.ByID(1239161594, meta, channelID);
}

/**
 * InstallWorkspace 创建企业所有者并返回登录令牌。
 */
export function InstallWorkspace(meta: $models.RequestMeta, input: $models.InstallWorkspaceInput): $CancellablePromise<$models.Auth> {
    return $Call.ByID(3665964242, meta, input);
}

/**
 * InstallationStatus 返回服务端初始化状态和公开企业名称。
 */
export function InstallationStatus(meta: $models.RequestMeta): $CancellablePromise<$models.InstallationStatus> {
    return $Call.ByID(3480414020, meta);
}

/**
 * ListChannels 返回当前企业的渠道选择项。
 */
export function ListChannels(meta: $models.RequestMeta): $CancellablePromise<$models.ChannelList> {
    return $Call.ByID(390964174, meta);
}

/**
 * ListContacts 返回联系人列表。
 */
export function ListContacts(meta: $models.RequestMeta, input: $models.ContactListInput): $CancellablePromise<$models.ContactList> {
    return $Call.ByID(1872706983, meta, input);
}

/**
 * ListUsers 返回企业成员列表。
 */
export function ListUsers(meta: $models.RequestMeta, input: $models.UserListInput): $CancellablePromise<$models.UserList> {
    return $Call.ByID(1809185478, meta, input);
}

/**
 * ListWebsiteChannels 返回网站渠道列表。
 */
export function ListWebsiteChannels(meta: $models.RequestMeta, deleted: boolean): $CancellablePromise<$models.WebsiteChannelList> {
    return $Call.ByID(97229659, meta, deleted);
}

/**
 * LoadIdentity 返回当前登录身份。
 */
export function LoadIdentity(meta: $models.RequestMeta): $CancellablePromise<$models.Identity> {
    return $Call.ByID(430146704, meta);
}

/**
 * LoadInbox 返回当前用户的统一收件箱。
 */
export function LoadInbox(meta: $models.RequestMeta): $CancellablePromise<$models.Inbox> {
    return $Call.ByID(129302578, meta);
}

/**
 * LoadSession 返回当前应进入的会话入口。
 */
export function LoadSession(meta: $models.RequestMeta): $CancellablePromise<$models.Session> {
    return $Call.ByID(2537050686, meta);
}

/**
 * Login 校验账号密码并返回登录令牌。
 */
export function Login(meta: $models.RequestMeta, input: $models.LoginInput): $CancellablePromise<$models.Auth> {
    return $Call.ByID(3058727111, meta, input);
}

/**
 * Logout 删除当前登录令牌。
 */
export function Logout(meta: $models.RequestMeta): $CancellablePromise<void> {
    return $Call.ByID(991463980, meta);
}

/**
 * ProbeServer 检测企业服务器并返回公开企业名称，不保存地址。
 */
export function ProbeServer(meta: $models.RequestMeta, serverURL: string): $CancellablePromise<$models.InstallationStatus> {
    return $Call.ByID(885726575, meta, serverURL);
}

/**
 * RestoreContact 恢复联系人。
 */
export function RestoreContact(meta: $models.RequestMeta, contactID: string): $CancellablePromise<$models.Contact> {
    return $Call.ByID(468810132, meta, contactID);
}

/**
 * RestoreWebsiteChannel 恢复网站渠道。
 */
export function RestoreWebsiteChannel(meta: $models.RequestMeta, channelID: string): $CancellablePromise<$models.WebsiteChannelSummary> {
    return $Call.ByID(2580943420, meta, channelID);
}

/**
 * SaveS3Setting 保存当前企业的对象存储设置。
 */
export function SaveS3Setting(meta: $models.RequestMeta, input: $models.S3Setting): $CancellablePromise<$models.S3Setting> {
    return $Call.ByID(2631396075, meta, input);
}

/**
 * ServerURL 返回原生端当前配置的企业服务器地址。
 */
export function ServerURL(meta: $models.RequestMeta): $CancellablePromise<string> {
    return $Call.ByID(791180750, meta);
}

/**
 * TestS3Setting 测试对象存储连接。
 */
export function TestS3Setting(meta: $models.RequestMeta, input: $models.S3Setting): $CancellablePromise<void> {
    return $Call.ByID(944621916, meta, input);
}

/**
 * UpdateContact 修改联系人。
 */
export function UpdateContact(meta: $models.RequestMeta, contactID: string, input: $models.ContactInput): $CancellablePromise<$models.Contact> {
    return $Call.ByID(183062653, meta, contactID, input);
}

/**
 * UpdateProfile 修改当前用户的姓名和邮箱。
 */
export function UpdateProfile(meta: $models.RequestMeta, input: $models.ProfileInput): $CancellablePromise<$models.User> {
    return $Call.ByID(1804531972, meta, input);
}

/**
 * UpdateUserPreferences 保存当前用户的语言和时区设置。
 */
export function UpdateUserPreferences(meta: $models.RequestMeta, input: $models.UserPreferencesInput): $CancellablePromise<$models.User> {
    return $Call.ByID(3982988274, meta, input);
}

/**
 * UpdateWebsiteChannel 修改网站渠道。
 */
export function UpdateWebsiteChannel(meta: $models.RequestMeta, channelID: string, input: $models.WebsiteChannelInput): $CancellablePromise<$models.WebsiteChannelSummary> {
    return $Call.ByID(1921858211, meta, channelID, input);
}

/**
 * UpdateWebsiteChannelChatInterface 修改网站渠道聊天界面。
 */
export function UpdateWebsiteChannelChatInterface(meta: $models.RequestMeta, channelID: string, input: $models.WebsiteChannelChatInterfaceInput): $CancellablePromise<$models.WebsiteChannelChatInterface> {
    return $Call.ByID(1443836536, meta, channelID, input);
}
