// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service 将跨平台业务调用转发给当前运行平台的 Backend。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ActivateMessageChannel 启用消息渠道。
 */
export function ActivateMessageChannel(meta: $models.RequestMeta, channelID: string): $CancellablePromise<$models.MessageChannelSummary> {
    return $Call.ByID(991066093, meta, channelID);
}

/**
 * AddGroupConversationMembers 批量增加群聊成员。
 */
export function AddGroupConversationMembers(meta: $models.RequestMeta, conversationID: string, input: $models.GroupConversationMembersInput): $CancellablePromise<$models.GroupConversation> {
    return $Call.ByID(2648272946, meta, conversationID, input);
}

/**
 * AddTeamMembers 将企业身份批量加入团队。
 */
export function AddTeamMembers(meta: $models.RequestMeta, teamID: string, input: $models.TeamMemberInput): $CancellablePromise<$models.Team> {
    return $Call.ByID(1201335915, meta, teamID, input);
}

/**
 * CancelFileUpload 将未发送的临时文件交给清理任务。
 */
export function CancelFileUpload(meta: $models.RequestMeta, fileID: string): $CancellablePromise<void> {
    return $Call.ByID(2213374235, meta, fileID);
}

/**
 * ChangePassword 核验当前密码并保存新密码。
 */
export function ChangePassword(meta: $models.RequestMeta, input: $models.ChangePasswordInput): $CancellablePromise<void> {
    return $Call.ByID(3645111243, meta, input);
}

/**
 * CheckNotificationPermission 返回当前设备的系统通知授权状态。
 */
export function CheckNotificationPermission(meta: $models.RequestMeta): $CancellablePromise<$models.NotificationPermissionStatus> {
    return $Call.ByID(64653454, meta);
}

/**
 * ClaimServiceSession 领取或接管客户会话最新处理周期。
 */
export function ClaimServiceSession(meta: $models.RequestMeta, conversationID: string): $CancellablePromise<$models.CustomerServiceSession> {
    return $Call.ByID(104372695, meta, conversationID);
}

/**
 * CloseServiceSession 关闭客户会话最新处理周期。
 */
export function CloseServiceSession(meta: $models.RequestMeta, conversationID: string): $CancellablePromise<$models.CustomerServiceSession> {
    return $Call.ByID(3932400583, meta, conversationID);
}

/**
 * CompleteAttachmentUpload 完成文件上传并激活原附件消息。
 */
export function CompleteAttachmentUpload(meta: $models.RequestMeta, fileID: string): $CancellablePromise<void> {
    return $Call.ByID(901775053, meta, fileID);
}

/**
 * CompleteFileUpload 核验并完成文件上传。
 */
export function CompleteFileUpload(meta: $models.RequestMeta, fileID: string): $CancellablePromise<$models.File> {
    return $Call.ByID(3172652722, meta, fileID);
}

/**
 * ConnectServer 验证并保存原生端企业服务器地址。
 */
export function ConnectServer(meta: $models.RequestMeta, serverURL: string): $CancellablePromise<void> {
    return $Call.ByID(1075777931, meta, serverURL);
}

/**
 * CreateAIProvider 创建模型服务供应商。
 */
export function CreateAIProvider(meta: $models.RequestMeta, input: $models.AIProviderInput): $CancellablePromise<$models.AIProvider> {
    return $Call.ByID(3165377185, meta, input);
}

/**
 * CreateAgent 创建企业 AI 员工。
 */
export function CreateAgent(meta: $models.RequestMeta, input: $models.CreateAgentInput): $CancellablePromise<$models.Agent> {
    return $Call.ByID(3052452131, meta, input);
}

/**
 * CreateBusinessSystem 创建业务系统。
 */
export function CreateBusinessSystem(meta: $models.RequestMeta, input: $models.BusinessSystemInput): $CancellablePromise<$models.BusinessSystem> {
    return $Call.ByID(1032860109, meta, input);
}

/**
 * CreateContact 创建联系人。
 */
export function CreateContact(meta: $models.RequestMeta, input: $models.ContactInput): $CancellablePromise<$models.Contact> {
    return $Call.ByID(2172055030, meta, input);
}

/**
 * CreateFilePartUpload 创建一个分片的直传请求。
 */
export function CreateFilePartUpload(meta: $models.RequestMeta, fileID: string, input: $models.FilePartUploadInput): $CancellablePromise<$models.FileUploadRequest> {
    return $Call.ByID(4242419644, meta, fileID, input);
}

/**
 * CreateFileUpload 创建文件上传请求。
 */
export function CreateFileUpload(meta: $models.RequestMeta, input: $models.FileUploadInput): $CancellablePromise<$models.FileUpload> {
    return $Call.ByID(1790184161, meta, input);
}

/**
 * CreateGroupConversation 创建企业内部群聊。
 */
export function CreateGroupConversation(meta: $models.RequestMeta, input: $models.GroupConversationInput): $CancellablePromise<$models.InboxConversation> {
    return $Call.ByID(4060539042, meta, input);
}

/**
 * CreateKnowledgeBase 创建企业知识库。
 */
export function CreateKnowledgeBase(meta: $models.RequestMeta, input: $models.KnowledgeBaseInput): $CancellablePromise<$models.KnowledgeBase> {
    return $Call.ByID(1982019343, meta, input);
}

/**
 * CreateKnowledgeDocuments 保存最多十个已上传的文档原件。
 */
export function CreateKnowledgeDocuments(meta: $models.RequestMeta, knowledgeBaseID: string, input: $models.KnowledgeDocumentBatchInput): $CancellablePromise<$models.KnowledgeDocumentBatch> {
    return $Call.ByID(3320220084, meta, knowledgeBaseID, input);
}

/**
 * CreateKnowledgeGroup 创建知识库分组。
 */
export function CreateKnowledgeGroup(meta: $models.RequestMeta, knowledgeBaseID: string, input: $models.KnowledgeGroupInput): $CancellablePromise<$models.KnowledgeBase> {
    return $Call.ByID(2458756261, meta, knowledgeBaseID, input);
}

/**
 * CreateKnowledgeQAEntry 创建本地问答。
 */
export function CreateKnowledgeQAEntry(meta: $models.RequestMeta, knowledgeBaseID: string, input: $models.KnowledgeQAInput): $CancellablePromise<$models.KnowledgeQAEntry> {
    return $Call.ByID(2807633900, meta, knowledgeBaseID, input);
}

/**
 * CreateMCPServer 创建 MCP 服务。
 */
export function CreateMCPServer(meta: $models.RequestMeta, input: $models.MCPServerInput): $CancellablePromise<$models.MCPServer> {
    return $Call.ByID(1999587509, meta, input);
}

/**
 * CreateMessageChannel 创建消息渠道。
 */
export function CreateMessageChannel(meta: $models.RequestMeta, input: $models.CreateMessageChannelInput): $CancellablePromise<$models.MessageChannelSummary> {
    return $Call.ByID(3211569396, meta, input);
}

/**
 * CreateRole 创建自定义角色。
 */
export function CreateRole(meta: $models.RequestMeta, input: $models.RoleInput): $CancellablePromise<$models.Role> {
    return $Call.ByID(2598423454, meta, input);
}

/**
 * CreateTeam 创建企业团队。
 */
export function CreateTeam(meta: $models.RequestMeta, input: $models.TeamInput): $CancellablePromise<$models.Team> {
    return $Call.ByID(3796040671, meta, input);
}

/**
 * CreateUser 创建企业成员账号。
 */
export function CreateUser(meta: $models.RequestMeta, input: $models.CreateUserInput): $CancellablePromise<$models.User> {
    return $Call.ByID(2291845417, meta, input);
}

/**
 * DeactivateAgent 禁用企业 AI 员工账号。
 */
export function DeactivateAgent(meta: $models.RequestMeta, agentID: string): $CancellablePromise<$models.Agent> {
    return $Call.ByID(2542842753, meta, agentID);
}

/**
 * DeactivateMessageChannel 停用消息渠道。
 */
export function DeactivateMessageChannel(meta: $models.RequestMeta, channelID: string): $CancellablePromise<$models.MessageChannelSummary> {
    return $Call.ByID(3507355270, meta, channelID);
}

/**
 * DeactivateUser 禁用企业成员账号。
 */
export function DeactivateUser(meta: $models.RequestMeta, userID: string): $CancellablePromise<$models.User> {
    return $Call.ByID(3624391107, meta, userID);
}

/**
 * DeleteAIProvider 删除模型服务供应商。
 */
export function DeleteAIProvider(meta: $models.RequestMeta, providerID: string): $CancellablePromise<void> {
    return $Call.ByID(1350701494, meta, providerID);
}

/**
 * DeleteBusinessSystem 删除业务系统。
 */
export function DeleteBusinessSystem(meta: $models.RequestMeta, businessSystemID: string): $CancellablePromise<void> {
    return $Call.ByID(1285278122, meta, businessSystemID);
}

/**
 * DeleteContact 将联系人移入回收站。
 */
export function DeleteContact(meta: $models.RequestMeta, contactID: string): $CancellablePromise<void> {
    return $Call.ByID(1228681067, meta, contactID);
}

/**
 * DeleteKnowledgeBase 删除企业知识库。
 */
export function DeleteKnowledgeBase(meta: $models.RequestMeta, knowledgeBaseID: string): $CancellablePromise<void> {
    return $Call.ByID(541376414, meta, knowledgeBaseID);
}

/**
 * DeleteKnowledgeDocument 删除文档并释放原件。
 */
export function DeleteKnowledgeDocument(meta: $models.RequestMeta, knowledgeBaseID: string, documentID: string): $CancellablePromise<void> {
    return $Call.ByID(1875707654, meta, knowledgeBaseID, documentID);
}

/**
 * DeleteKnowledgeGroup 删除不含子分组和问答的知识库分组。
 */
export function DeleteKnowledgeGroup(meta: $models.RequestMeta, knowledgeBaseID: string, groupID: string): $CancellablePromise<$models.KnowledgeBase> {
    return $Call.ByID(3559839338, meta, knowledgeBaseID, groupID);
}

/**
 * DeleteKnowledgeQAEntry 删除本地问答。
 */
export function DeleteKnowledgeQAEntry(meta: $models.RequestMeta, knowledgeBaseID: string, entryID: string): $CancellablePromise<void> {
    return $Call.ByID(3628287475, meta, knowledgeBaseID, entryID);
}

/**
 * DeleteMCPServer 删除 MCP 服务。
 */
export function DeleteMCPServer(meta: $models.RequestMeta, mcpServerID: string): $CancellablePromise<void> {
    return $Call.ByID(4060692824, meta, mcpServerID);
}

/**
 * DeleteRole 删除自定义角色。
 */
export function DeleteRole(meta: $models.RequestMeta, roleID: string): $CancellablePromise<void> {
    return $Call.ByID(3214219121, meta, roleID);
}

/**
 * DeleteTeam 删除企业团队及其成员关系。
 */
export function DeleteTeam(meta: $models.RequestMeta, teamID: string): $CancellablePromise<void> {
    return $Call.ByID(798533364, meta, teamID);
}

/**
 * DissolveGroupConversation 解散群聊并保留当前成员的只读历史。
 */
export function DissolveGroupConversation(meta: $models.RequestMeta, conversationID: string): $CancellablePromise<$models.GroupConversation> {
    return $Call.ByID(3528011703, meta, conversationID);
}

/**
 * FindDirectConversation 按目标身份查找当前成员的活跃单聊。
 */
export function FindDirectConversation(meta: $models.RequestMeta, targetIdentityID: string): $CancellablePromise<$models.DirectConversationLookup> {
    return $Call.ByID(2365759803, meta, targetIdentityID);
}

/**
 * GetAIProvider 返回当前企业中的模型服务供应商详情。
 */
export function GetAIProvider(meta: $models.RequestMeta, providerID: string): $CancellablePromise<$models.AIProvider> {
    return $Call.ByID(3088524329, meta, providerID);
}

/**
 * GetAgent 返回企业 AI 员工详情。
 */
export function GetAgent(meta: $models.RequestMeta, agentID: string): $CancellablePromise<$models.Agent> {
    return $Call.ByID(1827547163, meta, agentID);
}

/**
 * GetAttachmentDownload 签发当前成员可见消息附件的下载地址。
 */
export function GetAttachmentDownload(meta: $models.RequestMeta, conversationID: string, messageID: string): $CancellablePromise<$models.FileDownload> {
    return $Call.ByID(2610529071, meta, conversationID, messageID);
}

/**
 * GetBusinessSystem 返回当前企业中的业务系统详情。
 */
export function GetBusinessSystem(meta: $models.RequestMeta, businessSystemID: string): $CancellablePromise<$models.BusinessSystem> {
    return $Call.ByID(2775361573, meta, businessSystemID);
}

/**
 * GetContact 返回联系人详情。
 */
export function GetContact(meta: $models.RequestMeta, contactID: string): $CancellablePromise<$models.Contact> {
    return $Call.ByID(1550866366, meta, contactID);
}

/**
 * GetConversationMessageContext 返回目标消息及其前后上下文。
 */
export function GetConversationMessageContext(meta: $models.RequestMeta, conversationID: string, messageID: string): $CancellablePromise<$models.ConversationMessageList> {
    return $Call.ByID(2207630407, meta, conversationID, messageID);
}

/**
 * GetConversationNavigationState 返回群聊提及进度和最新可见消息。
 */
export function GetConversationNavigationState(meta: $models.RequestMeta, conversationID: string): $CancellablePromise<$models.ConversationNavigationState> {
    return $Call.ByID(56482708, meta, conversationID);
}

/**
 * GetGroupConversation 返回当前成员可见的群聊资料。
 */
export function GetGroupConversation(meta: $models.RequestMeta, conversationID: string): $CancellablePromise<$models.GroupConversation> {
    return $Call.ByID(2704575274, meta, conversationID);
}

/**
 * GetInboxContext 返回会话锚点的当前资格和原位置邻域。
 */
export function GetInboxContext(meta: $models.RequestMeta, input: $models.InboxContextInput): $CancellablePromise<$models.InboxContext> {
    return $Call.ByID(3985152105, meta, input);
}

/**
 * GetInboxConversation 返回当前用户有权阅读的独立会话摘要。
 */
export function GetInboxConversation(meta: $models.RequestMeta, conversationID: string): $CancellablePromise<$models.InboxConversation> {
    return $Call.ByID(3164550357, meta, conversationID);
}

/**
 * GetKnowledgeBase 返回当前企业中的知识库详情。
 */
export function GetKnowledgeBase(meta: $models.RequestMeta, knowledgeBaseID: string): $CancellablePromise<$models.KnowledgeBase> {
    return $Call.ByID(3589389559, meta, knowledgeBaseID);
}

/**
 * GetKnowledgeDocument 返回文档详情。
 */
export function GetKnowledgeDocument(meta: $models.RequestMeta, knowledgeBaseID: string, documentID: string): $CancellablePromise<$models.KnowledgeDocument> {
    return $Call.ByID(593812391, meta, knowledgeBaseID, documentID);
}

/**
 * GetKnowledgeDocumentPreview 签发当前文档的原件预览请求。
 */
export function GetKnowledgeDocumentPreview(meta: $models.RequestMeta, knowledgeBaseID: string, documentID: string): $CancellablePromise<$models.KnowledgeDocumentPreviewRequest> {
    return $Call.ByID(2139314833, meta, knowledgeBaseID, documentID);
}

/**
 * GetKnowledgeQAEntry 返回完整的本地问答。
 */
export function GetKnowledgeQAEntry(meta: $models.RequestMeta, knowledgeBaseID: string, entryID: string): $CancellablePromise<$models.KnowledgeQAEntry> {
    return $Call.ByID(3966244004, meta, knowledgeBaseID, entryID);
}

/**
 * GetMCPServer 返回当前企业中的 MCP 服务详情。
 */
export function GetMCPServer(meta: $models.RequestMeta, mcpServerID: string): $CancellablePromise<$models.MCPServer> {
    return $Call.ByID(2191357229, meta, mcpServerID);
}

/**
 * GetMessageChannel 返回消息渠道基础信息。
 */
export function GetMessageChannel(meta: $models.RequestMeta, channelID: string): $CancellablePromise<$models.MessageChannelSummary> {
    return $Call.ByID(2590359100, meta, channelID);
}

/**
 * GetRole 返回当前企业的角色详情。
 */
export function GetRole(meta: $models.RequestMeta, roleID: string): $CancellablePromise<$models.Role> {
    return $Call.ByID(4002500470, meta, roleID);
}

/**
 * GetS3Setting 返回当前企业的对象存储设置。
 */
export function GetS3Setting(meta: $models.RequestMeta): $CancellablePromise<$models.S3Setting> {
    return $Call.ByID(3937581736, meta);
}

/**
 * GetTelegramChannel 返回 Telegram 渠道详情。
 */
export function GetTelegramChannel(meta: $models.RequestMeta, channelID: string): $CancellablePromise<$models.TelegramChannel> {
    return $Call.ByID(675085480, meta, channelID);
}

/**
 * GetUser 返回企业成员详情。
 */
export function GetUser(meta: $models.RequestMeta, userID: string): $CancellablePromise<$models.User> {
    return $Call.ByID(1862601569, meta, userID);
}

/**
 * GetWebsiteChannel 返回网站渠道详情。
 */
export function GetWebsiteChannel(meta: $models.RequestMeta, channelID: string): $CancellablePromise<$models.WebsiteChannel> {
    return $Call.ByID(1239161594, meta, channelID);
}

/**
 * InstallWorkspace 创建企业管理员并返回登录令牌。
 */
export function InstallWorkspace(meta: $models.RequestMeta, input: $models.InstallWorkspaceInput): $CancellablePromise<$models.Auth> {
    return $Call.ByID(3665964242, meta, input);
}

/**
 * InstallationStatus 返回服务端初始化状态和公开企业名称。
 */
export function InstallationStatus(meta: $models.RequestMeta): $CancellablePromise<$models.InstallationStatus> {
    return $Call.ByID(3480414020, meta);
}

/**
 * LeaveGroupConversation 退出普通成员参与的群聊。
 */
export function LeaveGroupConversation(meta: $models.RequestMeta, conversationID: string): $CancellablePromise<void> {
    return $Call.ByID(43150167, meta, conversationID);
}

/**
 * ListAIProviders 返回当前企业的模型服务供应商列表。
 */
export function ListAIProviders(meta: $models.RequestMeta): $CancellablePromise<$models.AIProviderList> {
    return $Call.ByID(3759328446, meta);
}

/**
 * ListAgentMCPServerOptions 返回当前企业可配置的 MCP 服务。
 */
export function ListAgentMCPServerOptions(meta: $models.RequestMeta): $CancellablePromise<$models.AgentMCPServerOptionList> {
    return $Call.ByID(4205316032, meta);
}

/**
 * ListAgentModelOptions 返回 AI 员工可使用的对话模型。
 */
export function ListAgentModelOptions(meta: $models.RequestMeta): $CancellablePromise<$models.AgentModelOptionList> {
    return $Call.ByID(968800310, meta);
}

/**
 * ListAgents 返回企业 AI 员工目录。
 */
export function ListAgents(meta: $models.RequestMeta, input: $models.AgentListInput): $CancellablePromise<$models.AgentList> {
    return $Call.ByID(2544201800, meta, input);
}

/**
 * ListAttachmentStates 读取窗口内已存在附件消息的最新状态。
 */
export function ListAttachmentStates(meta: $models.RequestMeta, conversationID: string, input: $models.AttachmentStateListInput): $CancellablePromise<$models.AttachmentStateList> {
    return $Call.ByID(2257532333, meta, conversationID, input);
}

/**
 * ListAvailableAIModels 返回指定品牌的预设模型目录。
 */
export function ListAvailableAIModels(meta: $models.RequestMeta, brand: $models.AIProviderBrand): $CancellablePromise<$models.AIProviderModelList> {
    return $Call.ByID(3483353293, meta, brand);
}

/**
 * ListBusinessSystems 返回当前企业配置的业务系统。
 */
export function ListBusinessSystems(meta: $models.RequestMeta): $CancellablePromise<$models.BusinessSystemList> {
    return $Call.ByID(1520541682, meta);
}

/**
 * ListChannelOptions 返回当前企业的渠道选择项。
 */
export function ListChannelOptions(meta: $models.RequestMeta): $CancellablePromise<$models.ChannelOptionList> {
    return $Call.ByID(1406137265, meta);
}

/**
 * ListContacts 返回联系人列表。
 */
export function ListContacts(meta: $models.RequestMeta, input: $models.ContactListInput): $CancellablePromise<$models.ContactList> {
    return $Call.ByID(1872706983, meta, input);
}

/**
 * ListConversationMessageReferences 读取当前窗口的引用摘要和回复可用状态。
 */
export function ListConversationMessageReferences(meta: $models.RequestMeta, conversationID: string, input: $models.ConversationMessageReferenceListInput): $CancellablePromise<$models.ConversationMessageReferenceList> {
    return $Call.ByID(3159624270, meta, conversationID, input);
}

/**
 * ListConversationMessages 返回成员可见的会话消息。
 */
export function ListConversationMessages(meta: $models.RequestMeta, conversationID: string, input: $models.ConversationMessageListInput): $CancellablePromise<$models.ConversationMessageList> {
    return $Call.ByID(2470800485, meta, conversationID, input);
}

/**
 * ListCustomerMessageDeliveries 读取当前窗口的外部投递状态。
 */
export function ListCustomerMessageDeliveries(meta: $models.RequestMeta, conversationID: string, input: $models.CustomerDeliveryListInput): $CancellablePromise<$models.CustomerDeliveryList> {
    return $Call.ByID(344678729, meta, conversationID, input);
}

/**
 * ListCustomerServiceAssignees 返回有效真人和 AI 客服。
 */
export function ListCustomerServiceAssignees(meta: $models.RequestMeta): $CancellablePromise<$models.CustomerServiceAssigneeList> {
    return $Call.ByID(630654755, meta);
}

/**
 * ListKnowledgeBases 返回当前企业的知识库列表。
 */
export function ListKnowledgeBases(meta: $models.RequestMeta): $CancellablePromise<$models.KnowledgeBaseList> {
    return $Call.ByID(2416994044, meta);
}

/**
 * ListKnowledgeDocumentSegments 返回固定批次的分段页或锚点所在页。
 */
export function ListKnowledgeDocumentSegments(meta: $models.RequestMeta, knowledgeBaseID: string, documentID: string, input: $models.KnowledgeDocumentSegmentInput): $CancellablePromise<$models.KnowledgeDocumentSegmentPage> {
    return $Call.ByID(63381217, meta, knowledgeBaseID, documentID, input);
}

/**
 * ListKnowledgeDocuments 返回当前分组的文档列表。
 */
export function ListKnowledgeDocuments(meta: $models.RequestMeta, knowledgeBaseID: string, input: $models.KnowledgeDocumentListInput): $CancellablePromise<$models.KnowledgeDocumentList> {
    return $Call.ByID(4195704972, meta, knowledgeBaseID, input);
}

/**
 * ListKnowledgeQAEntries 返回分组中的本地问答列表。
 */
export function ListKnowledgeQAEntries(meta: $models.RequestMeta, knowledgeBaseID: string, input: $models.KnowledgeQAListInput): $CancellablePromise<$models.KnowledgeQAList> {
    return $Call.ByID(3867410272, meta, knowledgeBaseID, input);
}

/**
 * ListMCPServers 返回当前企业配置的 MCP 服务。
 */
export function ListMCPServers(meta: $models.RequestMeta): $CancellablePromise<$models.MCPServerList> {
    return $Call.ByID(3249929290, meta);
}

/**
 * ListMemberOptions 返回可分配的企业成员和 AI 员工。
 */
export function ListMemberOptions(meta: $models.RequestMeta, input: $models.MemberOptionListInput): $CancellablePromise<$models.MemberOptionList> {
    return $Call.ByID(386066486, meta, input);
}

/**
 * ListMessageChannels 返回消息渠道列表。
 */
export function ListMessageChannels(meta: $models.RequestMeta): $CancellablePromise<$models.MessageChannelList> {
    return $Call.ByID(2169861805, meta);
}

/**
 * ListPendingConversationMentions 返回本轮待查看提及目标。
 */
export function ListPendingConversationMentions(meta: $models.RequestMeta, conversationID: string): $CancellablePromise<$models.PendingConversationMentions> {
    return $Call.ByID(1362085509, meta, conversationID);
}

/**
 * ListRoles 返回当前企业的角色和预定义权限目录。
 */
export function ListRoles(meta: $models.RequestMeta): $CancellablePromise<$models.RoleList> {
    return $Call.ByID(3773953103, meta);
}

/**
 * ListTeamMemberCandidates 返回尚未加入团队的企业身份。
 */
export function ListTeamMemberCandidates(meta: $models.RequestMeta, teamID: string, input: $models.TeamMemberCandidateInput): $CancellablePromise<$models.TeamMemberCandidateList> {
    return $Call.ByID(1106825595, meta, teamID, input);
}

/**
 * ListTeamMembers 返回团队成员列表。
 */
export function ListTeamMembers(meta: $models.RequestMeta, teamID: string, input: $models.TeamMemberListInput): $CancellablePromise<$models.TeamMemberList> {
    return $Call.ByID(3371434770, meta, teamID, input);
}

/**
 * ListTeams 返回企业团队列表。
 */
export function ListTeams(meta: $models.RequestMeta, input: $models.TeamListInput): $CancellablePromise<$models.TeamList> {
    return $Call.ByID(3776706348, meta, input);
}

/**
 * ListUsers 返回企业成员列表。
 */
export function ListUsers(meta: $models.RequestMeta, input: $models.UserListInput): $CancellablePromise<$models.UserList> {
    return $Call.ByID(1809185478, meta, input);
}

/**
 * LoadIdentity 返回当前登录身份。
 */
export function LoadIdentity(meta: $models.RequestMeta): $CancellablePromise<$models.Identity> {
    return $Call.ByID(430146704, meta);
}

/**
 * LoadInbox 返回当前用户的统一收件箱。
 */
export function LoadInbox(meta: $models.RequestMeta, input: $models.LoadInboxInput): $CancellablePromise<$models.Inbox> {
    return $Call.ByID(129302578, meta, input);
}

/**
 * LoadStartup 根据企业初始化状态返回初始化或服务器连接入口。
 */
export function LoadStartup(meta: $models.RequestMeta): $CancellablePromise<$models.Startup> {
    return $Call.ByID(3512506751, meta);
}

/**
 * Login 校验账号密码并建立登录会话。
 */
export function Login(meta: $models.RequestMeta, input: $models.LoginInput): $CancellablePromise<$models.Auth> {
    return $Call.ByID(3058727111, meta, input);
}

/**
 * Logout 退出当前登录会话。
 */
export function Logout(meta: $models.RequestMeta): $CancellablePromise<void> {
    return $Call.ByID(991463980, meta);
}

/**
 * MarkConversationMentionReviewed 确认已查看的群聊提及。
 */
export function MarkConversationMentionReviewed(meta: $models.RequestMeta, conversationID: string, input: $models.MarkConversationMentionReviewedInput): $CancellablePromise<$models.ConversationMentionReview> {
    return $Call.ByID(2481523975, meta, conversationID, input);
}

/**
 * MarkConversationRead 单调推进当前用户的会话已读水位。
 */
export function MarkConversationRead(meta: $models.RequestMeta, conversationID: string, input: $models.MarkConversationReadInput): $CancellablePromise<$models.ConversationReadState> {
    return $Call.ByID(3314752344, meta, conversationID, input);
}

/**
 * MoveKnowledgeDocument 移动文档到同库分组。
 */
export function MoveKnowledgeDocument(meta: $models.RequestMeta, knowledgeBaseID: string, documentID: string, input: $models.KnowledgeDocumentMoveInput): $CancellablePromise<void> {
    return $Call.ByID(567509100, meta, knowledgeBaseID, documentID, input);
}

/**
 * OpenExternalPage 在原生端应用内新窗口打开外部页面。
 */
export function OpenExternalPage(meta: $models.RequestMeta, input: $models.ExternalPageInput): $CancellablePromise<void> {
    return $Call.ByID(1306697186, meta, input);
}

/**
 * PrepareFileUpload 为已有文件记录准备直传请求。
 */
export function PrepareFileUpload(meta: $models.RequestMeta, fileID: string): $CancellablePromise<$models.FileUpload> {
    return $Call.ByID(3661257970, meta, fileID);
}

/**
 * ProbeServer 检测企业服务器并返回公开企业名称。
 */
export function ProbeServer(meta: $models.RequestMeta, serverURL: string): $CancellablePromise<$models.InstallationStatus> {
    return $Call.ByID(885726575, meta, serverURL);
}

/**
 * ReactivateAgent 恢复企业 AI 员工。
 */
export function ReactivateAgent(meta: $models.RequestMeta, agentID: string): $CancellablePromise<$models.Agent> {
    return $Call.ByID(2138582847, meta, agentID);
}

/**
 * ReactivateUser 恢复企业成员账号。
 */
export function ReactivateUser(meta: $models.RequestMeta, userID: string): $CancellablePromise<$models.User> {
    return $Call.ByID(2986051725, meta, userID);
}

/**
 * ReadInboxConversations 按 ID 批量返回会话摘要及当前筛选资格。
 */
export function ReadInboxConversations(meta: $models.RequestMeta, input: $models.ReadInboxConversationsInput): $CancellablePromise<$models.InboxConversationResults> {
    return $Call.ByID(2030324742, meta, input);
}

/**
 * ReadInboxWindow 重读已加载双向边界之间的完整列表范围。
 */
export function ReadInboxWindow(meta: $models.RequestMeta, input: $models.InboxWindowInput): $CancellablePromise<$models.InboxWindow> {
    return $Call.ByID(2805575182, meta, input);
}

/**
 * RefreshMCPServerTools 提交当前企业的 MCP 工具更新任务。
 */
export function RefreshMCPServerTools(meta: $models.RequestMeta): $CancellablePromise<void> {
    return $Call.ByID(3429373167, meta);
}

/**
 * RemoveGroupConversationMember 移除单个群聊成员。
 */
export function RemoveGroupConversationMember(meta: $models.RequestMeta, conversationID: string, input: $models.GroupConversationMemberInput): $CancellablePromise<$models.GroupConversation> {
    return $Call.ByID(3264103052, meta, conversationID, input);
}

/**
 * RemoveTeamMembers 将企业身份批量移出团队。
 */
export function RemoveTeamMembers(meta: $models.RequestMeta, teamID: string, input: $models.TeamMemberInput): $CancellablePromise<$models.Team> {
    return $Call.ByID(3538693274, meta, teamID, input);
}

/**
 * ReopenServiceSession 重新打开客户会话最新处理周期并分配给当前身份。
 */
export function ReopenServiceSession(meta: $models.RequestMeta, conversationID: string): $CancellablePromise<$models.CustomerServiceSession> {
    return $Call.ByID(4025586058, meta, conversationID);
}

/**
 * RequestNotificationPermission 请求当前设备允许发送系统通知。
 */
export function RequestNotificationPermission(meta: $models.RequestMeta): $CancellablePromise<$models.NotificationPermissionStatus> {
    return $Call.ByID(3018557431, meta);
}

/**
 * ResolveCustomerMessageDelivery 人工处理失败或待确认的投递。
 */
export function ResolveCustomerMessageDelivery(meta: $models.RequestMeta, conversationID: string, deliveryID: string, input: $models.CustomerDeliveryResolveInput): $CancellablePromise<void> {
    return $Call.ByID(2639604801, meta, conversationID, deliveryID, input);
}

/**
 * RestoreContact 恢复联系人。
 */
export function RestoreContact(meta: $models.RequestMeta, contactID: string): $CancellablePromise<$models.Contact> {
    return $Call.ByID(468810132, meta, contactID);
}

/**
 * RetryKnowledgeDocument 按当前配置重新处理文档。
 */
export function RetryKnowledgeDocument(meta: $models.RequestMeta, knowledgeBaseID: string, documentID: string): $CancellablePromise<void> {
    return $Call.ByID(1935547685, meta, knowledgeBaseID, documentID);
}

/**
 * SaveS3Setting 保存当前企业的对象存储设置。
 */
export function SaveS3Setting(meta: $models.RequestMeta, input: $models.S3SettingInput): $CancellablePromise<$models.S3Setting> {
    return $Call.ByID(2631396075, meta, input);
}

/**
 * SaveTelegramChannelConnection 保存 Telegram 机器人和 Webhook 设置。
 */
export function SaveTelegramChannelConnection(meta: $models.RequestMeta, channelID: string, input: $models.TelegramChannelConnectionInput): $CancellablePromise<$models.TelegramChannel> {
    return $Call.ByID(857691531, meta, channelID, input);
}

/**
 * SelectImage 在原生端选择并读取图片。
 */
export function SelectImage(meta: $models.RequestMeta): $CancellablePromise<$models.ImageFile> {
    return $Call.ByID(1896757263, meta);
}

/**
 * SendAgentTextMessage 向已有 AI 会话发送文本消息。
 */
export function SendAgentTextMessage(meta: $models.RequestMeta, conversationID: string, input: $models.AgentTextMessageInput): $CancellablePromise<$models.ConversationMessage> {
    return $Call.ByID(1168206825, meta, conversationID, input);
}

/**
 * SendAttachmentBatch 按选择顺序保存可带说明的单聊附件消息。
 */
export function SendAttachmentBatch(meta: $models.RequestMeta, input: $models.AttachmentBatchInput): $CancellablePromise<$models.AttachmentBatchResult> {
    return $Call.ByID(294445027, meta, input);
}

/**
 * SendAttachmentMessage 发送内部单聊或群聊附件消息。
 */
export function SendAttachmentMessage(meta: $models.RequestMeta, input: $models.AttachmentMessageInput): $CancellablePromise<$models.AttachmentMessageResult> {
    return $Call.ByID(115977132, meta, input);
}

/**
 * SendCustomerTextMessage 发送客户会话文本消息。
 */
export function SendCustomerTextMessage(meta: $models.RequestMeta, conversationID: string, input: $models.CustomerTextMessageInput): $CancellablePromise<$models.ConversationMessage> {
    return $Call.ByID(1986181614, meta, conversationID, input);
}

/**
 * SendDirectTextMessage 发送内部单聊文本消息。
 */
export function SendDirectTextMessage(meta: $models.RequestMeta, conversationID: string, input: $models.DirectTextMessageInput): $CancellablePromise<$models.ConversationMessage> {
    return $Call.ByID(1058328585, meta, conversationID, input);
}

/**
 * SendFirstAgentTextMessage 在首次发送时创建独立 AI 聊天。
 */
export function SendFirstAgentTextMessage(meta: $models.RequestMeta, input: $models.FirstAgentTextMessageInput): $CancellablePromise<$models.FirstAgentTextMessageResult> {
    return $Call.ByID(1367071003, meta, input);
}

/**
 * SendFirstDirectTextMessage 向目标身份发送首条单聊消息并按需创建长期会话。
 */
export function SendFirstDirectTextMessage(meta: $models.RequestMeta, input: $models.FirstDirectTextMessageInput): $CancellablePromise<$models.FirstDirectTextMessageResult> {
    return $Call.ByID(3790712855, meta, input);
}

/**
 * SendGroupTextMessage 发送企业内部群聊文本消息。
 */
export function SendGroupTextMessage(meta: $models.RequestMeta, conversationID: string, input: $models.GroupTextMessageInput): $CancellablePromise<$models.ConversationMessage> {
    return $Call.ByID(4169063283, meta, conversationID, input);
}

/**
 * SendMessageNotification 在当前设备投递一条新消息系统通知。
 */
export function SendMessageNotification(meta: $models.RequestMeta, input: $models.MessageNotificationInput): $CancellablePromise<void> {
    return $Call.ByID(4158811544, meta, input);
}

/**
 * ServerURL 返回原生端当前配置的企业服务器地址。
 */
export function ServerURL(meta: $models.RequestMeta): $CancellablePromise<string> {
    return $Call.ByID(791180750, meta);
}

/**
 * StopAgentReply 停止独立 AI 会话中指定的回复并返回实际运行状态。
 */
export function StopAgentReply(meta: $models.RequestMeta, conversationID: string, runID: string): $CancellablePromise<$models.AgentRunStatus> {
    return $Call.ByID(4044594473, meta, conversationID, runID);
}

/**
 * StopGroupAgentReply 停止群聊中指定的 AI 员工回复并返回实际运行状态。
 */
export function StopGroupAgentReply(meta: $models.RequestMeta, conversationID: string, runID: string): $CancellablePromise<$models.AgentRunStatus> {
    return $Call.ByID(4078297554, meta, conversationID, runID);
}

/**
 * TestAIProviderConnection 测试模型服务供应商草稿配置。
 */
export function TestAIProviderConnection(meta: $models.RequestMeta, input: $models.AIProviderConnectionInput): $CancellablePromise<void> {
    return $Call.ByID(840788545, meta, input);
}

/**
 * TestMCPServerConnection 测试 MCP 草稿连接配置。
 */
export function TestMCPServerConnection(meta: $models.RequestMeta, input: $models.MCPServerConnectionInput): $CancellablePromise<void> {
    return $Call.ByID(2900402005, meta, input);
}

/**
 * TestS3Setting 测试对象存储连接。
 */
export function TestS3Setting(meta: $models.RequestMeta, input: $models.S3SettingInput): $CancellablePromise<void> {
    return $Call.ByID(944621916, meta, input);
}

/**
 * TestSavedMCPServerConnection 测试已保存的 MCP 服务。
 */
export function TestSavedMCPServerConnection(meta: $models.RequestMeta, mcpServerID: string): $CancellablePromise<void> {
    return $Call.ByID(2055787012, meta, mcpServerID);
}

/**
 * TestTelegramChannelConnection 测试 Telegram 草稿 Token。
 */
export function TestTelegramChannelConnection(meta: $models.RequestMeta, channelID: string, input: $models.TelegramChannelConnectionTestInput): $CancellablePromise<void> {
    return $Call.ByID(324699684, meta, channelID, input);
}

/**
 * TransferGroupConversationOwner 转让群主。
 */
export function TransferGroupConversationOwner(meta: $models.RequestMeta, conversationID: string, input: $models.GroupConversationOwnerInput): $CancellablePromise<$models.GroupConversation> {
    return $Call.ByID(637753570, meta, conversationID, input);
}

/**
 * TransferServiceSession 把当前负责的处理周期转给另一位客服。
 */
export function TransferServiceSession(meta: $models.RequestMeta, conversationID: string, input: $models.TransferServiceSessionInput): $CancellablePromise<$models.CustomerServiceSession> {
    return $Call.ByID(2034510468, meta, conversationID, input);
}

/**
 * UpdateAIProvider 修改模型服务供应商。
 */
export function UpdateAIProvider(meta: $models.RequestMeta, providerID: string, input: $models.AIProviderInput): $CancellablePromise<$models.AIProvider> {
    return $Call.ByID(3982600252, meta, providerID, input);
}

/**
 * UpdateAgent 修改企业 AI 员工。
 */
export function UpdateAgent(meta: $models.RequestMeta, agentID: string, input: $models.UpdateAgentInput): $CancellablePromise<$models.Agent> {
    return $Call.ByID(2196616072, meta, agentID, input);
}

/**
 * UpdateAgentExecution 修改企业 AI 员工的执行配置。
 */
export function UpdateAgentExecution(meta: $models.RequestMeta, agentID: string, input: $models.UpdateAgentExecutionInput): $CancellablePromise<$models.Agent> {
    return $Call.ByID(3177846414, meta, agentID, input);
}

/**
 * UpdateAttachmentUploads 更新附件上传状态或取消尚未完成的消息。
 */
export function UpdateAttachmentUploads(meta: $models.RequestMeta, input: $models.AttachmentUploadUpdate): $CancellablePromise<void> {
    return $Call.ByID(3367707592, meta, input);
}

/**
 * UpdateBusinessSystem 修改业务系统。
 */
export function UpdateBusinessSystem(meta: $models.RequestMeta, businessSystemID: string, input: $models.BusinessSystemInput): $CancellablePromise<$models.BusinessSystem> {
    return $Call.ByID(1302951044, meta, businessSystemID, input);
}

/**
 * UpdateContact 修改联系人。
 */
export function UpdateContact(meta: $models.RequestMeta, contactID: string, input: $models.ContactInput): $CancellablePromise<$models.Contact> {
    return $Call.ByID(183062653, meta, contactID, input);
}

/**
 * UpdateConversationNotificationSettings 保存当前用户的原生会话提醒设置。
 */
export function UpdateConversationNotificationSettings(meta: $models.RequestMeta, conversationID: string, input: $models.ConversationNotificationSettingsInput): $CancellablePromise<$models.ConversationNotificationSettings> {
    return $Call.ByID(379824806, meta, conversationID, input);
}

/**
 * UpdateConversationUnreadMark 保存当前用户独立于阅读水位的未读标记。
 */
export function UpdateConversationUnreadMark(meta: $models.RequestMeta, conversationID: string, input: $models.ConversationUnreadMarkInput): $CancellablePromise<void> {
    return $Call.ByID(1934573390, meta, conversationID, input);
}

/**
 * UpdateGroupConversation 修改群聊资料。
 */
export function UpdateGroupConversation(meta: $models.RequestMeta, conversationID: string, input: $models.GroupConversationProfileInput): $CancellablePromise<$models.GroupConversation> {
    return $Call.ByID(1492390913, meta, conversationID, input);
}

/**
 * UpdateKnowledgeBase 修改企业知识库。
 */
export function UpdateKnowledgeBase(meta: $models.RequestMeta, knowledgeBaseID: string, input: $models.KnowledgeBaseInput): $CancellablePromise<$models.KnowledgeBase> {
    return $Call.ByID(103390268, meta, knowledgeBaseID, input);
}

/**
 * UpdateKnowledgeGroup 修改知识库分组。
 */
export function UpdateKnowledgeGroup(meta: $models.RequestMeta, knowledgeBaseID: string, groupID: string, input: $models.KnowledgeGroupInput): $CancellablePromise<$models.KnowledgeBase> {
    return $Call.ByID(1535726024, meta, knowledgeBaseID, groupID, input);
}

/**
 * UpdateKnowledgeQAEntry 修改本地问答。
 */
export function UpdateKnowledgeQAEntry(meta: $models.RequestMeta, knowledgeBaseID: string, entryID: string, input: $models.KnowledgeQAInput): $CancellablePromise<$models.KnowledgeQAEntry> {
    return $Call.ByID(137278157, meta, knowledgeBaseID, entryID, input);
}

/**
 * UpdateMCPServer 修改 MCP 服务。
 */
export function UpdateMCPServer(meta: $models.RequestMeta, mcpServerID: string, input: $models.MCPServerInput): $CancellablePromise<$models.MCPServer> {
    return $Call.ByID(4046277534, meta, mcpServerID, input);
}

/**
 * UpdateMessageChannel 修改消息渠道基础信息。
 */
export function UpdateMessageChannel(meta: $models.RequestMeta, channelID: string, input: $models.MessageChannelInput): $CancellablePromise<$models.MessageChannelSummary> {
    return $Call.ByID(4163765989, meta, channelID, input);
}

/**
 * UpdateOrganization 修改当前企业通用设置。
 */
export function UpdateOrganization(meta: $models.RequestMeta, input: $models.OrganizationInput): $CancellablePromise<$models.Organization> {
    return $Call.ByID(272970364, meta, input);
}

/**
 * UpdateProfile 修改当前用户的头像、姓名和邮箱。
 */
export function UpdateProfile(meta: $models.RequestMeta, input: $models.ProfileInput): $CancellablePromise<$models.CurrentUser> {
    return $Call.ByID(1804531972, meta, input);
}

/**
 * UpdateRole 修改角色信息和权限。
 */
export function UpdateRole(meta: $models.RequestMeta, roleID: string, input: $models.RoleInput): $CancellablePromise<$models.Role> {
    return $Call.ByID(747750943, meta, roleID, input);
}

/**
 * UpdateRoleAssignments 在一个事务中批量调整真人和 AI 员工角色。
 */
export function UpdateRoleAssignments(meta: $models.RequestMeta, input: $models.RoleAssignmentsInput): $CancellablePromise<void> {
    return $Call.ByID(2402672415, meta, input);
}

/**
 * UpdateTeam 修改企业团队。
 */
export function UpdateTeam(meta: $models.RequestMeta, teamID: string, input: $models.TeamInput): $CancellablePromise<$models.Team> {
    return $Call.ByID(2807681714, meta, teamID, input);
}

/**
 * UpdateUnreadIndicator 更新当前设备的未读提示。
 */
export function UpdateUnreadIndicator(meta: $models.RequestMeta, state: $models.UnreadIndicatorState): $CancellablePromise<void> {
    return $Call.ByID(4142772673, meta, state);
}

/**
 * UpdateUser 修改企业成员资料、角色和所属团队。
 */
export function UpdateUser(meta: $models.RequestMeta, userID: string, input: $models.UpdateUserInput): $CancellablePromise<$models.User> {
    return $Call.ByID(2151183832, meta, userID, input);
}

/**
 * UpdateUserPreferences 保存当前用户的偏好设置。
 */
export function UpdateUserPreferences(meta: $models.RequestMeta, input: $models.UserPreferencesInput): $CancellablePromise<$models.CurrentUser> {
    return $Call.ByID(3982988274, meta, input);
}

/**
 * UpdateUserWorkStatus 保存当前用户主动设置的工作状态。
 */
export function UpdateUserWorkStatus(meta: $models.RequestMeta, input: $models.UserWorkStatusInput): $CancellablePromise<$models.CurrentUser> {
    return $Call.ByID(1131036783, meta, input);
}

/**
 * UpdateWebsiteChannelAccess 修改网站渠道允许使用的网站。
 */
export function UpdateWebsiteChannelAccess(meta: $models.RequestMeta, channelID: string, input: $models.WebsiteChannelAccessInput): $CancellablePromise<$models.WebsiteChannelAccess> {
    return $Call.ByID(1435471417, meta, channelID, input);
}

/**
 * UpdateWebsiteChannelChatInterface 修改网站渠道聊天界面。
 */
export function UpdateWebsiteChannelChatInterface(meta: $models.RequestMeta, channelID: string, input: $models.WebsiteChannelChatInterfaceInput): $CancellablePromise<$models.WebsiteChannelChatInterface> {
    return $Call.ByID(1443836536, meta, channelID, input);
}
