// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service 将跨平台业务调用转发给当前运行平台的 Backend。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ActivateWebsiteChannel 启用网站渠道。
 */
export function ActivateWebsiteChannel(meta: $models.RequestMeta, channelID: string): $CancellablePromise<$models.WebsiteChannelSummary> {
    return $Call.ByID(141044523, meta, channelID);
}

/**
 * AddTeamMembers 将企业成员批量加入团队。
 */
export function AddTeamMembers(meta: $models.RequestMeta, teamID: string, input: $models.TeamMemberInput): $CancellablePromise<$models.Team> {
    return $Call.ByID(1201335915, meta, teamID, input);
}

/**
 * ChangePassword 核验当前密码并保存新密码。
 */
export function ChangePassword(meta: $models.RequestMeta, input: $models.ChangePasswordInput): $CancellablePromise<void> {
    return $Call.ByID(3645111243, meta, input);
}

/**
 * CompleteFileUpload 核验并完成文件上传。
 */
export function CompleteFileUpload(meta: $models.RequestMeta, fileID: string): $CancellablePromise<$models.File> {
    return $Call.ByID(3172652722, meta, fileID);
}

/**
 * ConnectServer 验证并保存原生端企业服务器地址，并返回地址是否变化。
 */
export function ConnectServer(meta: $models.RequestMeta, serverURL: string): $CancellablePromise<boolean> {
    return $Call.ByID(1075777931, meta, serverURL);
}

/**
 * CreateAIProvider 创建模型服务供应商。
 */
export function CreateAIProvider(meta: $models.RequestMeta, input: $models.AIProviderInput): $CancellablePromise<$models.AIProvider> {
    return $Call.ByID(3165377185, meta, input);
}

/**
 * CreateContact 创建联系人。
 */
export function CreateContact(meta: $models.RequestMeta, input: $models.ContactInput): $CancellablePromise<$models.Contact> {
    return $Call.ByID(2172055030, meta, input);
}

/**
 * CreateFileUpload 创建文件上传请求。
 */
export function CreateFileUpload(meta: $models.RequestMeta, input: $models.FileUploadInput): $CancellablePromise<$models.FileUpload> {
    return $Call.ByID(1790184161, meta, input);
}

/**
 * CreateRole 创建自定义角色。
 */
export function CreateRole(meta: $models.RequestMeta, input: $models.RoleInput): $CancellablePromise<$models.Role> {
    return $Call.ByID(2598423454, meta, input);
}

/**
 * CreateTeam 创建企业团队。
 */
export function CreateTeam(meta: $models.RequestMeta, input: $models.TeamInput): $CancellablePromise<$models.Team> {
    return $Call.ByID(3796040671, meta, input);
}

/**
 * CreateUser 创建企业成员账号。
 */
export function CreateUser(meta: $models.RequestMeta, input: $models.CreateUserInput): $CancellablePromise<$models.DirectoryUser> {
    return $Call.ByID(2291845417, meta, input);
}

/**
 * CreateWebsiteChannel 创建网站渠道。
 */
export function CreateWebsiteChannel(meta: $models.RequestMeta, input: $models.WebsiteChannelInput): $CancellablePromise<$models.WebsiteChannelSummary> {
    return $Call.ByID(372928498, meta, input);
}

/**
 * DeactivateUser 停用企业成员账号。
 */
export function DeactivateUser(meta: $models.RequestMeta, userID: string): $CancellablePromise<$models.DirectoryUser> {
    return $Call.ByID(3624391107, meta, userID);
}

/**
 * DeactivateWebsiteChannel 停用网站渠道。
 */
export function DeactivateWebsiteChannel(meta: $models.RequestMeta, channelID: string): $CancellablePromise<$models.WebsiteChannelSummary> {
    return $Call.ByID(1439117156, meta, channelID);
}

/**
 * DeleteAIProvider 删除模型服务供应商。
 */
export function DeleteAIProvider(meta: $models.RequestMeta, providerID: string): $CancellablePromise<void> {
    return $Call.ByID(1350701494, meta, providerID);
}

/**
 * DeleteContact 将联系人移入回收站。
 */
export function DeleteContact(meta: $models.RequestMeta, contactID: string): $CancellablePromise<void> {
    return $Call.ByID(1228681067, meta, contactID);
}

/**
 * DeleteRole 删除自定义角色。
 */
export function DeleteRole(meta: $models.RequestMeta, roleID: string): $CancellablePromise<void> {
    return $Call.ByID(3214219121, meta, roleID);
}

/**
 * DeleteTeam 删除企业团队及其成员关系。
 */
export function DeleteTeam(meta: $models.RequestMeta, teamID: string): $CancellablePromise<void> {
    return $Call.ByID(798533364, meta, teamID);
}

/**
 * GetAIProvider 返回当前企业中的模型服务供应商详情。
 */
export function GetAIProvider(meta: $models.RequestMeta, providerID: string): $CancellablePromise<$models.AIProvider> {
    return $Call.ByID(3088524329, meta, providerID);
}

/**
 * GetContact 返回联系人详情。
 */
export function GetContact(meta: $models.RequestMeta, contactID: string): $CancellablePromise<$models.Contact> {
    return $Call.ByID(1550866366, meta, contactID);
}

/**
 * GetRole 返回当前企业的角色详情。
 */
export function GetRole(meta: $models.RequestMeta, roleID: string): $CancellablePromise<$models.Role> {
    return $Call.ByID(4002500470, meta, roleID);
}

/**
 * GetS3Setting 返回当前企业的对象存储设置。
 */
export function GetS3Setting(meta: $models.RequestMeta): $CancellablePromise<$models.S3Setting> {
    return $Call.ByID(3937581736, meta);
}

/**
 * GetUser 返回企业成员详情。
 */
export function GetUser(meta: $models.RequestMeta, userID: string): $CancellablePromise<$models.DirectoryUser> {
    return $Call.ByID(1862601569, meta, userID);
}

/**
 * GetWebsiteChannel 返回网站渠道详情。
 */
export function GetWebsiteChannel(meta: $models.RequestMeta, channelID: string): $CancellablePromise<$models.WebsiteChannel> {
    return $Call.ByID(1239161594, meta, channelID);
}

/**
 * InstallWorkspace 创建企业管理员并返回登录令牌。
 */
export function InstallWorkspace(meta: $models.RequestMeta, input: $models.InstallWorkspaceInput): $CancellablePromise<$models.Auth> {
    return $Call.ByID(3665964242, meta, input);
}

/**
 * InstallationStatus 返回服务端初始化状态和公开企业名称。
 */
export function InstallationStatus(meta: $models.RequestMeta): $CancellablePromise<$models.InstallationStatus> {
    return $Call.ByID(3480414020, meta);
}

/**
 * ListAIProviders 返回当前企业的模型服务供应商列表。
 */
export function ListAIProviders(meta: $models.RequestMeta): $CancellablePromise<$models.AIProviderList> {
    return $Call.ByID(3759328446, meta);
}

/**
 * ListAvailableAIModels 返回指定品牌的预设模型目录。
 */
export function ListAvailableAIModels(meta: $models.RequestMeta, brand: $models.AIProviderBrand): $CancellablePromise<$models.AIProviderModelList> {
    return $Call.ByID(3483353293, meta, brand);
}

/**
 * ListChannels 返回当前企业的渠道选择项。
 */
export function ListChannels(meta: $models.RequestMeta): $CancellablePromise<$models.ChannelList> {
    return $Call.ByID(390964174, meta);
}

/**
 * ListContacts 返回联系人列表。
 */
export function ListContacts(meta: $models.RequestMeta, input: $models.ContactListInput): $CancellablePromise<$models.ContactList> {
    return $Call.ByID(1872706983, meta, input);
}

/**
 * ListRoles 返回当前企业的角色和预定义权限目录。
 */
export function ListRoles(meta: $models.RequestMeta): $CancellablePromise<$models.RoleList> {
    return $Call.ByID(3773953103, meta);
}

/**
 * ListTeamMemberCandidates 返回尚未加入团队的企业成员。
 */
export function ListTeamMemberCandidates(meta: $models.RequestMeta, teamID: string, input: $models.TeamMemberCandidateInput): $CancellablePromise<$models.TeamMemberCandidateList> {
    return $Call.ByID(1106825595, meta, teamID, input);
}

/**
 * ListTeams 返回企业团队列表。
 */
export function ListTeams(meta: $models.RequestMeta, input: $models.TeamListInput): $CancellablePromise<$models.TeamList> {
    return $Call.ByID(3776706348, meta, input);
}

/**
 * ListUsers 返回企业成员列表。
 */
export function ListUsers(meta: $models.RequestMeta, input: $models.UserListInput): $CancellablePromise<$models.UserList> {
    return $Call.ByID(1809185478, meta, input);
}

/**
 * ListWebsiteChannels 返回网站渠道列表。
 */
export function ListWebsiteChannels(meta: $models.RequestMeta): $CancellablePromise<$models.WebsiteChannelList> {
    return $Call.ByID(97229659, meta);
}

/**
 * LoadIdentity 返回当前登录身份。
 */
export function LoadIdentity(meta: $models.RequestMeta): $CancellablePromise<$models.Identity> {
    return $Call.ByID(430146704, meta);
}

/**
 * LoadInbox 返回当前用户的统一收件箱。
 */
export function LoadInbox(meta: $models.RequestMeta): $CancellablePromise<$models.Inbox> {
    return $Call.ByID(129302578, meta);
}

/**
 * LoadSession 返回当前应进入的会话入口。
 */
export function LoadSession(meta: $models.RequestMeta): $CancellablePromise<$models.Session> {
    return $Call.ByID(2537050686, meta);
}

/**
 * Login 校验账号密码并返回登录令牌。
 */
export function Login(meta: $models.RequestMeta, input: $models.LoginInput): $CancellablePromise<$models.Auth> {
    return $Call.ByID(3058727111, meta, input);
}

/**
 * Logout 删除当前登录令牌。
 */
export function Logout(meta: $models.RequestMeta): $CancellablePromise<void> {
    return $Call.ByID(991463980, meta);
}

/**
 * ProbeServer 检测企业服务器并返回公开企业名称，不保存地址。
 */
export function ProbeServer(meta: $models.RequestMeta, serverURL: string): $CancellablePromise<$models.InstallationStatus> {
    return $Call.ByID(885726575, meta, serverURL);
}

/**
 * ReactivateUser 恢复企业成员账号。
 */
export function ReactivateUser(meta: $models.RequestMeta, userID: string): $CancellablePromise<$models.DirectoryUser> {
    return $Call.ByID(2986051725, meta, userID);
}

/**
 * RemoveTeamMembers 将企业成员批量移出团队。
 */
export function RemoveTeamMembers(meta: $models.RequestMeta, teamID: string, input: $models.TeamMemberInput): $CancellablePromise<$models.Team> {
    return $Call.ByID(3538693274, meta, teamID, input);
}

/**
 * RestoreContact 恢复联系人。
 */
export function RestoreContact(meta: $models.RequestMeta, contactID: string): $CancellablePromise<$models.Contact> {
    return $Call.ByID(468810132, meta, contactID);
}

/**
 * SaveS3Setting 保存当前企业的对象存储设置。
 */
export function SaveS3Setting(meta: $models.RequestMeta, input: $models.S3Setting): $CancellablePromise<$models.S3Setting> {
    return $Call.ByID(2631396075, meta, input);
}

/**
 * SelectProfileImage 在原生端选择并读取用户头像图片。
 */
export function SelectProfileImage(meta: $models.RequestMeta): $CancellablePromise<$models.ProfileImageFile> {
    return $Call.ByID(1937167372, meta);
}

/**
 * ServerURL 返回原生端当前配置的企业服务器地址。
 */
export function ServerURL(meta: $models.RequestMeta): $CancellablePromise<string> {
    return $Call.ByID(791180750, meta);
}

/**
 * TestS3Setting 测试对象存储连接。
 */
export function TestS3Setting(meta: $models.RequestMeta, input: $models.S3Setting): $CancellablePromise<void> {
    return $Call.ByID(944621916, meta, input);
}

/**
 * UpdateAIProvider 修改模型服务供应商。
 */
export function UpdateAIProvider(meta: $models.RequestMeta, providerID: string, input: $models.AIProviderInput): $CancellablePromise<$models.AIProvider> {
    return $Call.ByID(3982600252, meta, providerID, input);
}

/**
 * UpdateContact 修改联系人。
 */
export function UpdateContact(meta: $models.RequestMeta, contactID: string, input: $models.ContactInput): $CancellablePromise<$models.Contact> {
    return $Call.ByID(183062653, meta, contactID, input);
}

/**
 * UpdateOrganization 修改当前企业名称。
 */
export function UpdateOrganization(meta: $models.RequestMeta, input: $models.OrganizationInput): $CancellablePromise<$models.Organization> {
    return $Call.ByID(272970364, meta, input);
}

/**
 * UpdateProfile 修改当前用户的头像、姓名和邮箱。
 */
export function UpdateProfile(meta: $models.RequestMeta, input: $models.ProfileInput): $CancellablePromise<$models.User> {
    return $Call.ByID(1804531972, meta, input);
}

/**
 * UpdateRole 修改角色信息和权限。
 */
export function UpdateRole(meta: $models.RequestMeta, roleID: string, input: $models.RoleInput): $CancellablePromise<$models.Role> {
    return $Call.ByID(747750943, meta, roleID, input);
}

/**
 * UpdateTeam 修改企业团队。
 */
export function UpdateTeam(meta: $models.RequestMeta, teamID: string, input: $models.TeamInput): $CancellablePromise<$models.Team> {
    return $Call.ByID(2807681714, meta, teamID, input);
}

/**
 * UpdateUser 修改企业成员资料、角色和所属团队。
 */
export function UpdateUser(meta: $models.RequestMeta, userID: string, input: $models.UpdateDirectoryUserInput): $CancellablePromise<$models.DirectoryUser> {
    return $Call.ByID(2151183832, meta, userID, input);
}

/**
 * UpdateUserPreferences 保存当前用户的语言和时区设置。
 */
export function UpdateUserPreferences(meta: $models.RequestMeta, input: $models.UserPreferencesInput): $CancellablePromise<$models.User> {
    return $Call.ByID(3982988274, meta, input);
}

/**
 * UpdateUserRoles 在一个事务中批量调整企业成员角色。
 */
export function UpdateUserRoles(meta: $models.RequestMeta, input: $models.UserRoleChangesInput): $CancellablePromise<void> {
    return $Call.ByID(2927672865, meta, input);
}

/**
 * UpdateUserWorkStatus 保存当前用户主动设置的工作状态。
 */
export function UpdateUserWorkStatus(meta: $models.RequestMeta, input: $models.UserWorkStatusInput): $CancellablePromise<$models.User> {
    return $Call.ByID(1131036783, meta, input);
}

/**
 * UpdateWebsiteChannel 修改网站渠道基础信息。
 */
export function UpdateWebsiteChannel(meta: $models.RequestMeta, channelID: string, input: $models.WebsiteChannelInput): $CancellablePromise<$models.WebsiteChannelSummary> {
    return $Call.ByID(1921858211, meta, channelID, input);
}

/**
 * UpdateWebsiteChannelAccess 修改网站渠道允许使用的网站。
 */
export function UpdateWebsiteChannelAccess(meta: $models.RequestMeta, channelID: string, input: $models.WebsiteChannelAccessInput): $CancellablePromise<$models.WebsiteChannelAccess> {
    return $Call.ByID(1435471417, meta, channelID, input);
}

/**
 * UpdateWebsiteChannelChatInterface 修改网站渠道聊天界面。
 */
export function UpdateWebsiteChannelChatInterface(meta: $models.RequestMeta, channelID: string, input: $models.WebsiteChannelChatInterfaceInput): $CancellablePromise<$models.WebsiteChannelChatInterface> {
    return $Call.ByID(1443836536, meta, channelID, input);
}
